### ISSUE TITLE
Crashes in guess_file_type?

### ISSUE THREAD

**Issue by mschwendt** [erikd/libsndfile#101]
Any ideas here? Fedora's libsndfile package maintainer is non-responsive also with his other packages:

1) https://bugzilla.redhat.com/1047767
Backtrace: https://bugzilla.redhat.com/attachment.cgi?id=844383

2) https://bugzilla.redhat.com/1220078
Backtrace: https://bugzilla.redhat.com/attachment.cgi?id=1023859

In both backtraces it seems to be choking at sndfile.c:2423 trying to skip ID3 tags endlessly. This is with libsndfile 1.0.25 and users trying to load some files into Audacious (and its sndfile plugin).

**Comment by erikd** [comment]
Neither of those bug reports contain the actual audio file that causes the crash. It you want me to investigate this further, I need those files.

Fortunately I'm pretty sure the fix is already in git and I am hoping to get a new release out soon.

**Comment by erikd** [comment]
Pretty sure this has been been fixed in git. If not, plreas re-open and provide and example file that re-produces the error.
