### ISSUE TITLE
seek to end ambiguous

### ISSUE THREAD

**Issue by 7890** [erikd/libsndfile#103]
current = sf_seek (file, 0, SEEK_CUR);

-> this gives different results depending on the audio format.

i.e. sf info structure reports 10 frames, then seeking to 10 frames:
-wav, ogg -> seek relative 0 returns 10
-flac -> seek relative 0 returns -1

**Comment by erikd** [comment]
Finally got a chance to look at this. Why are you using `sf_read_raw`?

**Comment by 7890** [comment]
sf_read_raw just part of the test.. it's not related to the issue at all (please see the <<<<< markers).

**Comment by erikd** [comment]
Your original text said:

> current = sf_seek (file, 0, SEEK_CUR);
>
> -> this gives different results depending on the audio format.

As for the bits marked `<<<<<<<<<`, I don't get that, I get:

    welcome to sndfile seek test. first arg is audio file.
    frames: 822922
    current pos: 0
    seeking to: 822921
    current pos: 822921 after 0.002000 ms
    seeking to: 822922
    current pos: 822922 not null
    seeking to: 822923
    current pos: -1 not null
    seeking to: end+0
    current pos: 822922
    seeking to: end-1
    current pos: 822921
    seeking to: 0
    current pos: 0
    sf_read_raw 16 bytes
    current pos: 4, read 16 bytes

I have seen issues like the one you have marked with `<<<<<<` before. They usually occur when the file us being compiled incorrectly. Have you tried switching on compiler warnings? With GCC you do that with `-Wall`. You should fix all warnings uncovered by `-Wall`.

Furthermore, If I start with a WAV file, and a FLAC file generated by converting the WAV fir FLAC, and run your seek test on both files. the only differences are the time it took to seek to the end of the file and the current position after the `sf_read_raw`.

**Comment by 7890** [comment]
Thanks for looking into this. I've removed the test program to put the focus back to the issue.
I'd expect that
```
sf_seek (file, 0, SEEK_CUR);
```
returns the same position independently of the format, for all files that report identical total frame numbers.

**Comment by 7890** [comment]
ok here is a simplified program to show the effect.

```
#include <stdlib.h>
#include <inttypes.h>
#include <sndfile.h>

//gcc -o seek_simple seek_simple.c -lsndfile

static SNDFILE *soundfile=NULL;
static SF_INFO sf_info;

int main(int argc,char *argv[])
{
        char *filename=argv[1];
        soundfile=sf_open(filename,SFM_READ,&sf_info);
        if(soundfile==NULL)
        {
                exit(1);
        }
        uint64_t frames=sf_info.frames;
        printf("frames: %"PRId64"\n",frames);
        sf_count_t pos;
        pos=sf_seek(soundfile,frames,SEEK_SET);
        fprintf(stderr, "sf_seek %"PRId64" SEEK_SET returns: %"PRId64"\n",frames,pos);
        pos=sf_seek(soundfile,0,SEEK_CUR);
        fprintf(stderr, "sf_seek 0 SEEK_CUR returns: %"PRId64"\n",pos);
        sf_close (soundfile);
        exit(0);
}
```
Take any wav file, convert it to a flac. Make sure sndfile-info shows identical "Frames" value. Start seek_simple once with the .wav file, then with the .flac file.

The output looks like this:
```
$ ./seek_simple 1.wav
frames: 12119
sf_seek 12119 SEEK_SET returns: 12119
sf_seek 0 SEEK_CUR returns: 12119
```
```
$ ./seek_simple 1.flac
frames: 12119
sf_seek 12119 SEEK_SET returns: -1
sf_seek 0 SEEK_CUR returns: -1
```

Please let me know if this gives another result at your end. Thanks again

**Comment by 7890** [comment]
after updating flac + libsndfile from github, the issue seems gone. both .wav and .flac reports now the same (12119).
sometimes waiting a bit makes error reports obsolete :)
