### ISSUE TITLE
A few undefined behaviors

### ISSUE THREAD

**Issue by xiedingbao** [erikd/libsndfile#104]
Dear developer,
after running afl-fuzzer on libsndfile for a night, I found a few undefined behaviors.
To reproduce them, first build the source code with flag '-fsanitize=undefined' and then
compile the example code 'generate.c' and link it against the static library.
At last execute command 'generate $file', you should be able to see the following error
information:

wav.c:872:42: runtime error: signed integer overflow: 8388618 * 2048 cannot be represented in type 'int'
wav.c:851:42: runtime error: signed integer overflow: 8388618 * 2048 cannot be represented in type 'int'
w64.c:566:42: runtime error: signed integer overflow: 8388618 * 2048 cannot be represented in type 'int'
w64.c:541:42: runtime error: signed integer overflow: 8388618 * 2048 cannot be represented in type 'int'
wav.c:800:57: runtime error: signed integer overflow: 1073741834 * 2 cannot be represented in type 'int'
wav.c:872:42: runtime error: signed integer overflow: 1073741834 * 2048 cannot be represented in type 'int'

wav.c:915:42: runtime error: signed integer overflow: 1073741834 * 65 cannot be represented in type 'int'
w64.c:484:58: runtime error: signed integer overflow: 1073741834 * 2 cannot be represented in type 'int'
w64.c:566:42: runtime error: signed integer overflow: 1073741834 * 2048 cannot be represented in type 'int'
w64.c:541:42: runtime error: signed integer overflow: 1073741834 * 2048 cannot be represented in type 'int'
w64.c:593:41: runtime error: signed integer overflow: 1073741834 * 65 cannot be represented in type 'int'
common.c:131:12: runtime error: negation of -2147483648 cannot be represented in type 'int'; cast to an unsigned type to negate this value to itself
wav.c:800:74: runtime error: signed integer overflow: 1459748864 * 246 cannot be represented in type 'int'
wav.c:800:57: runtime error: signed integer overflow: 1459748864 * 2 cannot be represented in type 'int'
w64.c:484:75: runtime error: signed integer overflow: 1459748864 * 246 cannot be represented in type 'int'
w64.c:539:65: runtime error: signed integer overflow: 1073741834 * 2 cannot be represented in type 'int'
w64.c:151:62: runtime error: signed integer overflow: 1073741834 * 2 cannot be represented in type 'int'
wav.c:251:62: runtime error: signed integer overflow: 1073741834 * 2 cannot be represented in type 'int'
wav.c:870:65: runtime error: signed integer overflow: 1073741834 * 2 cannot be represented in type 'int'

mat4.c:107:35: runtime error: signed integer overflow: 8 * -1027493703 cannot be represented in type 'int'
common.c:131:12: runtime error: negation of -2147483648 cannot be represented in type 'int'; cast to an unsigned type to negate this value to itself
mat4.c:318:78: runtime error: signed integer overflow: 2061836770995077120 * 8 cannot be represented in type 'long'
mat4.c:322:83: runtime error: signed integer overflow: 2061836770995077120 * 8 cannot be represented in type 'long'
mat4.c:323:41: runtime error: signed integer overflow: -2147483648 * -960117565 cannot be represented in type 'int'
mat4.c:323:48: runtime error: signed integer overflow: -2147483648 * 8 cannot be represented in type 'int'
mat4.c:320:74: runtime error: signed integer overflow: -1220011173438275349 * 8 cannot be represented in type 'long'
pcm.c:128:35: runtime error: signed integer overflow: 4 * -1027493703 cannot be represented in type 'int'

You can download the input file from this link: https://www.dropbox.com/s/faa9c1cwnm4aifu/inputs.zip?dl=0

**Comment by erikd** [comment]
I know of and use AFL myself. I have already spent well over two weeks of CPU time fuzzing libsndfile with AFL and the Address Sanitizer. That found some genuine bugs that were definitely worth fixing.

However, none of the files you provided are of any interest. When the `generate` program is run on these files, the program either

* Exits with an exit code of `0`.
* Prints an error message and exits with an exit code of `1`.

In the second case, `libsndfile` has detected some anomally in the input file, printed an error message and exited.

BTW, it would make much more sense to fuzz the `sndfile-info` program in the `programs` directory.
