### ISSUE TITLE
Problems with tags

### ISSUE THREAD

**Issue by dts350z** [erikd/libsndfile#114]
My application reads and writes files using libsndfile.

I'm not sure where this code snipit came from, but I'm using it to copy metadata (tags) from input to output:

static void
copy_metadata (SNDFILE *outfile, SNDFILE *infile, int channels)
{	SF_INSTRUMENT inst ;
	SF_BROADCAST_INFO_2K binfo ;
	const char *str ;
	int k, chanmap[256]={0} ;
	int errnum =0;
	char message[200];

	for (k = SF_STR_FIRST ; k <= SF_STR_LAST ; k++)
	{	str = sf_get_string (infile, k) ;
		if (str != NULL)
			errnum = sf_set_string (outfile, k, str);
			if (errnum != 0) {
				sprintf_s(message,200,"error writing file metadata: %d\n%s",errnum,sf_error_number (errnum));
				MessageBox(my_window_handle, TEXT((LPCSTR)message), TEXT("SpecWeb"), MB_OK|MB_ICONEXCLAMATION);
			}
		} ;

	memset (&inst, 0, sizeof (inst)) ;
	memset (&binfo, 0, sizeof (binfo)) ;

	if (channels < ARRAY_LEN (chanmap))
	{	size_t size = channels * sizeof (chanmap [0]) ;

		if (sf_command (infile, SFC_GET_CHANNEL_MAP_INFO, chanmap, size) == SF_TRUE)
			sf_command (outfile, SFC_SET_CHANNEL_MAP_INFO, chanmap, size) ;
		} ;

	if (sf_command (infile, SFC_GET_INSTRUMENT, &inst, sizeof (inst)) == SF_TRUE)
		sf_command (outfile, SFC_SET_INSTRUMENT, &inst, sizeof (inst)) ;

	if (sf_command (infile, SFC_GET_BROADCAST_INFO, &binfo, sizeof (binfo)) == SF_TRUE)
		sf_command (outfile, SFC_SET_BROADCAST_INFO, &binfo, sizeof (binfo)) ;

} /* copy_metadata */

Two problems,

libsndfile (with the above code) seems to support a subset of tags, so a lot of tags get dropped in the process.

For some files I get error 59, bad string. 

I see the note about utf8 encoding, but before trying that I want to know if there is a newer/better approach for copying ALL metadata (tags) from an input file to an output file.

**Comment by erikd** [comment]
The only place `SFE_BAD_STRING` can be set is at https://github.com/erikd/libsndfile/blob/master/src/strings.c#L34

As you can see, that error code can only be returned is you pass either a `NULL` pointer or an empty string. I therefore suspect that the problem will go away if you change your test:

      if (str != NULL)

to

     if (str != NULL && strlen (str) > 0)

Let me know how it goes.

**Comment by dts350z** [comment]
That was the same conclusion I came to. 

Thanks

**Comment by erikd** [comment]
Ok, I'll close this.
