### ISSUE TITLE
Valgrind uninitialized values

### ISSUE THREAD

**Issue by milasudril** [erikd/libsndfile#115]
I get this Valgrind error:

>  Conditional jump or move depends on uninitialised value(s)

Platform: i686, Ubuntu 15.10, libsndfile 1.0.25-9.1ubuntu0.15 ,g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010. The error does not appear on x86_64.

Compiler flags (for my project): -g -Wall -march=native -std=c++11

CPU model: Intel(R) Pentium(R) M processor 1.73GHz

The file I try to load can be found here: https://github.com/milasudril/anja/blob/master/testbank/pump_im.ogg

Source code using libsndfile: https://github.com/milasudril/anja/blob/master/wavefilereader-sndfile.cpp

Backtrace:

    (gdb) backtrace
    #0  0x04c2f631 in psf_log_printf (psf=0x61d2d68, format=0x4c5b2db " Hz\n")
    at common.c:178
    #1  0x04c2e6d7 in vorbis_read_header (psf=psf@entry=0x61d2d68, 
    log_data=log_data@entry=1) at ogg_vorbis.c:296
    #2  0x04c2eb0d in ogg_vorbis_open (psf=0x61d2d68) at ogg_vorbis.c:505
    #3  0x04c48ca1 in ogg_open (psf=0x61d2d68) at ogg.c:70
    #4  0x04c0e839 in psf_open_file (psf=<optimized out>, sfinfo=<optimized out>)
    at sndfile.c:2774
    #5  0x04c0ef82 in sf_open (
    path=0x61d2c90 "/home/torbjorr/Dokument/anja/testbank/pump_im.ogg", 
    mode=16, sfinfo=0x61d2d14) at sndfile.c:332
    #6  0x080602fc in WavefileReaderSndfile::WavefileReaderSndfile (this=0x61d2d10, 
    path=0x61d2c90 "/home/torbjorr/Dokument/anja/testbank/pump_im.ogg", 
    info=...) at wavefilereader-sndfile.cpp:36

**Comment by erikd** [comment]
Does it happen with git HEAD?

**Comment by erikd** [comment]
In my testing, this does not have with gti HEAD (commit 1755ee40794) so closing this.
