### ISSUE TITLE
can't write tags to rf64 or w64

### ISSUE THREAD

**Issue by dts350z** [erikd/libsndfile#116]
When using sf_set_string I get error 53 for rf64 and w64 files.

I need a format that supports "tags" and 32 bit float and can exceed 4GB file size. I think either rf64 or w64 should work?

caf format doesn't complain with sf_set_string but the tags don't come back when read with libsndfile.

**Comment by erikd** [comment]
Do you have examples of RF64 and/or W64 files with string data?

**Comment by dts350z** [comment]
No. I assumed since they are extensions of the wave format, and the wave format supports strings, that they would too.

Did I assume incorrectly?

**Comment by erikd** [comment]
They probably do it in a similar way, but I like to see a couple of example files before I implement. Specification documents are usually wrong, incomplete and un-reliable.

**Comment by dts350z** [comment]
OK, I have sony soundforge, so it should be a good source for w64 files (w64 being a sony file format).

I can load flac files with strings, save it as a w64, then close everything and read in the w64 and have strings in the metadata.

Soundforge lists strings in the metadata under "CD Information" and "Summary information" tabs in their metadata viewer.

One example:  (zip file contains the flac I started with and the sound forge written .w64 version.)

http://www.surroundbyus.com//sbu/download/w64%20tagged%20file.zip

**Comment by erikd** [comment]
Thanks for that.

I had a look around for CAF files with string data and found one, so I'm implementing that first and then I'll do W64.

**Comment by dts350z** [comment]
OK, great.

FYI I will need a windows build to test.

**Comment by erikd** [comment]
I'll sort that out once I get W64 working as well.

**Comment by erikd** [comment]
@dts350z I've started work on W64.

Would you be able to convert the file http://www.mega-nerd.com/erikd/strings.wav to W64 and make it available?

Thanks.

**Comment by dts350z** [comment]
http://www.surroundbyus.com//sbu/download/strings.w64

**Comment by erikd** [comment]
Thanks for the file. Unfortunately, the string metadata was not transferred to the output file in that conversion.

**Comment by dts350z** [comment]
Hmm,

Soundforge can see the tags in the .w64 version, both in the summary and in the cd information tabs.

I can also load that .w64 file and re save as wave and get the tags back:


[strings2.zip](https://github.com/erikd/libsndfile/files/76715/strings2.zip)

**Comment by erikd** [comment]
Never mind. I messed up. The file does indeed have the string data.

**Comment by erikd** [comment]
I am not able to find anything that even looks like a specification for W64. Also it seems that string data in the W64 files @dts350z provided seem to be UTF-16 which is a huge pain in the neck.

Furthermore, the specification I found for RF64 ( https://tech.ebu.ch/docs/tech/tech3306-2009.pdf ) only makes one rather confusing mention of a `LIST` chunk. I'm going to look at how easy it is to just use the `WAV` format `LIST` parser code for RF64.

**Comment by erikd** [comment]
Ok, getting string metadata working for RF64 should be relatively easy. Its mostly a matter of moving code around so it can be shared by the WAV and the RF64 code paths.

W64 however is probably not going to happen. I cannot find any specification for the W64 format (most specs are appallingly bad, W64 seems to be completely non-existant). In addition, the example files I have seems to contain UTF-16 strings which would require a lot of work to support.

@dts350z If string metadata works for CAF and RF64, is W64 really necessary?

**Comment by dts350z** [comment]
My application reads flacs or wavs, processes and writes an intermediate file @32 bit float, then does another process step on that file and writes flacs, so in my particular case I coded around the problem by saving the tags from the input file and writing them to the final output file, skipping the tagging issue in the intermediate file, so I am all good at this point.

Prior to realizing I could do that, having tags in any working 32 bit float format (that also supported larger than 4GB files) would have been fine. Also having a wav based format, such as RF64, that supports tagging should be good for libsndfile going forward. I may need that in the future.

Thanks!

**Comment by erikd** [comment]
Ok, I've pushed the code for string metadata in CAF and RF64 files.

I'll close this.
