### ISSUE TITLE
iXML metadata

### ISSUE THREAD

**Issue by danrossi** [erikd/libsndfile#117]
I'm sorry to ask you here but I'm looking at a way to read out iXML data from broadcast wave files. I looked in the code and it looks like it just logs and passes skips the chunk correct ?

**Comment by erikd** [comment]
Here is fine!

Yes, you are indeed correct. Currently it just logs the presence of an `iXML` chunk and skips it.

**Comment by danrossi** [comment]
There is minimal info. Is there a way to use sf_get_chunk_data ? I might have to fallback to bwfmetaedit if that is the case.

**Comment by danrossi** [comment]
Unless I am wrong it seems to be storing it in here psf->rchunks.chunks ?

**Comment by erikd** [comment]
No, I think you are correct. Have a look at the code in `tests/chunk_test.c` and let me know if it works.

**Comment by danrossi** [comment]
I can't build the test files. The make commands don't work on OSX.

**Comment by danrossi** [comment]
```
make chunk_test
```

running that manually worked no worries , I'll see what comes up.

**Comment by erikd** [comment]
Added #119 (Document sf_set_chunk / sf_get_chunk_size / sf_get_chunk_data) .

**Comment by danrossi** [comment]
Sorry to bug you about this. There isn't a working test on a current file but I'm hoping this brings up something. I'll try and build one. 

```
memset (&chunk_info, 0, sizeof (chunk_info)) ;
	snprintf (chunk_info.id, sizeof (chunk_info.id), "iXML") ;
	chunk_info.id_size = 4 ;

	iterator = sf_get_chunk_iterator (file, &chunk_info) ;
	err = sf_get_chunk_size (iterator, &chunk_info) ;
chunk_info.data = malloc (chunk_info.datalen) ;
	err = sf_get_chunk_data (iterator, &chunk_info) ;
```

**Comment by erikd** [comment]
You should not need a specific `iXML` test. The functions `sf_set_chunk`, `sf_get_chunk_iterator`, `sf_get_chunk_size` and `sf_get_chunk_data` are supposed to be generic enough to get/set any chunk type, including `iXML`.

**Comment by danrossi** [comment]
I mean make a test file for it because the tests don't use external files. 

It seems I've run into a small issue. I'm trying to work with builds version 1.0.25 which most systems would have including the linux packages. It does not have said chunk functions. 

I'm trying to not have to build for different systems and I'm working with python c interface also.

**Comment by erikd** [comment]
That chunk stuff was a new feature for libsndfile 1.0.26 which was released 15 months ago.

**Comment by danrossi** [comment]
yes its ok I'll deal with it. I'm trying to port something to NAS file server systems like Synology and it seems they use can run debian compiled binaries ok.  So in production this feature isn't available yet sadly. 

This works perfectly although the printing part isn't correct, not a c person. 

```
file = test_open_file_or_die ("/path/to/fil", SFM_READ, &sfinfo, SF_TRUE, __LINE__) ;

	memset (&chunk_info, 0, sizeof (chunk_info)) ;
	snprintf (chunk_info.id, sizeof (chunk_info.id), "iXML") ;
	chunk_info.id_size = 4 ;

	iterator = sf_get_chunk_iterator (file, &chunk_info) ;
	err = sf_get_chunk_size (iterator, &chunk_info) ;




	chunk_info.data = malloc (chunk_info.datalen) ;
	err = sf_get_chunk_data (iterator, &chunk_info) ;

	printf ("%.*s\n", (int) sizeof (chunk_info.data), chunk_info.data);
	printf ("%d", chunk_info.datalen);

	free (chunk_info.data) ;

	sf_close (file) ;
```

**Comment by erikd** [comment]
The value `chunk_info.data` is a pointer so it will have a size of 8 on a 64 bit CPU (4 on a 32 bit).

You probably should do something like (untested):

```
printf ("%d", chunk_info.datalen);
printf ("%.*s\n", (int) chunk_info.datalen, chunk_info.data);
```

**Comment by danrossi** [comment]
It's OK , this is working for me now in my program, but on the python side. I have to allocate the data first before reading and call the size method or nothing get's printed. 

I'm now trying to work out if the chunk is there before trying to dig into it. Is there a size property  I can use or I have to make a few calls and check "datalen" ?

**Comment by erikd** [comment]
Try the `sf_get_chunk_size` function which is defined in the `src/sndfile.h` header file.

**Comment by danrossi** [comment]
That looks correct mate. If 

```
= sf_get_chunk_size (iterator, &chunk_info) ;
```

is not called no data chunk is read into, and chunk_info.datalen is empty. So I make the call here and check chunk_info.datalen. The return from that method is always zero ?

**Comment by erikd** [comment]
Sorry, I don't understand that response. More code maybe?

**Comment by danrossi** [comment]
```
file = test_open_file_or_die ("/path/to/fil", SFM_READ, &sfinfo, SF_TRUE, __LINE__) ;

    memset (&chunk_info, 0, sizeof (chunk_info)) ;
    snprintf (chunk_info.id, sizeof (chunk_info.id), "iXML") ;
    chunk_info.id_size = 4 ;

    iterator = sf_get_chunk_iterator (file, &chunk_info) ;
    err = sf_get_chunk_size (iterator, &chunk_info) ;

    printf ("%d", err);


    chunk_info.data = malloc (chunk_info.datalen) ;
    err = sf_get_chunk_data (iterator, &chunk_info) ;

    printf ("%.*s\n", (int) sizeof (chunk_info.data), chunk_info.data);
    printf ("%d", chunk_info.datalen);

    free (chunk_info.data) ;

    sf_close (file) ;
```

The return from sf_get_chunk_size is always zero. The size check has to happen in chunk_info.datalen it seems which I then use before calling sf_get_chunk_data. 

No worries. 

This is actually my working function within python cffi, I've tested it processing on many wav files in a directory for indexing metadata and it's very fast. 

I don't know what the equivalent is for malloc so I have to call it directly for now to setup the data pointer. 

```
        chunk_info = _ffi.new("SF_CHUNK_INFO*")
        chunk_info.id = b'iXML'
        chunk_info.id_size = 4;

        iterator = _snd.sf_get_chunk_iterator(self._file, chunk_info)

        err = _snd.sf_get_chunk_size(iterator, chunk_info)

        if (chunk_info.datalen > 0):
            chunk_info.data = _snd.malloc (chunk_info.datalen) ;
            _snd.sf_get_chunk_data(iterator, chunk_info)
            self.ixml_info = _ffi.buffer(chunk_info.data, chunk_info.datalen)[:].decode()
            _snd.free(chunk_info.data)
```

You may close this for now it was more a documentation question, hopefully the snippets are helpful. Thanks.

**Comment by erikd** [comment]
Glad to see its working for you. There's another ticket open for documenting these functions so I'm closing this one.
