### ISSUE TITLE
sf_read_float never returns less than items

### ISSUE THREAD

**Issue by dts350z** [erikd/libsndfile#120]
I am trying to troubleshoot a problem with my app (which reads and writes files using libsndfile) where the last ~100 ms of the output file is missing.

I am reading input files with sf_read_float, and I notice that I NEVER get a return value less than the the number of items I asked for, which seems suspicious. I'm reading in a while loop where the value returned by sf_read_float > 0.
I would expect that in the last loop I would get less that the number of items I asked for, and that sf_read_float would return the number of items I actually got, vs. 0.

Is this not the case? If not, how am I supposed to now how many items got read into the buffer so I can process a partially filled buffer at the end of a file?

if so, then why do I never see a return value between zero and items asked for. I can't believe that every file magically ends on a buffer boundary.

**Comment by dts350z** [comment]
OK I see the problem was actually in the sprintf statement to show the number of samples read. You can ignore this. My bad.

I still don't know where my 100ms of audio is going. When/where do you use sf_write_sync? Right before the close of an file you are writing?

**Comment by erikd** [comment]
Under normal situations it is not necessary to call `sf_write_sync` at all. It was added to the API to allow the caller to flush the file systems in-memory buffers to disk. This *may* be useful in some special situations like writing very large files, or writing multiple files at the same time.

**Comment by erikd** [comment]
Closing this.
