### ISSUE TITLE
Validation of AIFF can be improved

### ISSUE THREAD

**Issue by mrserb** [erikd/libsndfile#123]
According to documentation the sndfile_info[1] can validate the data of audio file. 

This validation can be improved in case of AIFF container. According the specification[2] the number of 
sample frames should be stored in the COMM chunk:
numSampleFrames - contains the number of sample frames in the Sound Data Chunk. Note that numSampleFrames is the number of sample frames, not the number of bytes nor the number of sample points in the Sound Data Chunk. The total number of sample points in the file is numSampleFrames times numChannels. 
This way is used in libsndfile for some audio formats, see aiff.c:1004
       psf->sf.frames = comm_fmt->numSampleFrames ;

The same data can be obtained from the Sound Data Chunk.  This way is used in libsndfile most of the time. For example check pcm.c:274
      psf->sf.frames = psf->blockwidth > 0 ? psf->datalength / psf->blockwidth : 0 ;

This is a request to add a check that these two values are equal.

[1] http://www.mega-nerd.com/libsndfile/sndfile_info.html
[2] http://groovit.disjunkt.com/analog/aiff/h_aiff13.html

**Comment by erikd** [comment]
Please test this fix: https://github.com/erikd/libsndfile/commit/f628398146fcd5318d09c0900391413199f66f64

You can test by cloning the repo and then checking out the "aiff-validation" branch.

**Comment by mrserb** [comment]
It works, I got this warning below.
I guess message have a typo. "calculated from length if 'SSND' chunk".

Also I am not sure about a standard format of such warnings in libssndfile. Sometimes it is start from "Warning : " or  "***", sometimes it is just a text, and in some cases it is reported as "(should be 199946)",

========================================
File : /var/folders/09/s3xtd3gx2gv_r9lkldd71zbw0000gn/T/sound1765826196234420222.aiff
Length : 94
FORM : 86
 AIFF
 COMM : 18
  Sample Rate : 44100
  Frames      : 14
  Channels    : 2
  Sample Size : 11
  Encoding    : NONE
 SSND : 48
  Offset     : 0
  Block Size : 0
*** Frame count read from 'COMM' chunk (14) not equal to frame count
*** calculated from length if 'SSND' chunk (10).

----------------------------------------
Sample Rate : 44100
Frames      : 10
Channels    : 2
Format      : 0x00020002
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:00.000
Signal Max  : 32768 (0.00 dB)

**Comment by erikd** [comment]
The `found X (should be Y)` messages are emitted when at the place it reads `X` it can easily calculate `Y`.

In the case we're looking at, we can't check the value of the value of `comm_fmt->numSampleFrames` until we get to the `SSND` chunk.

The '`Warning` message (I think) is only used during audio decoding, not during header parsing.

In the test suite, I check the log buffer for `***` and `should be`.
