### ISSUE TITLE
"Seekable" is not set correctly

### ISSUE THREAD

**Issue by cnliao** [erikd/libsndfile#124]
**System:** Archlinux
**libsndfile version:** 1.0.26 (I tested both the version in system repo and self-compiled version)
**Issue description:** Using sndfile-info to  check whether a sound file is seekable, one finds that the "Seekable" field is always "False". The same field is "True" for the same file with libsndfile version 1.0.25

Here follows some sample output.
###  sndfile-info sample.wav ----- 1.0.26

> Length : 394301084
> RIFF : 394301076
> WAVE
> fmt  : 16
>   Format        : 0x1 => WAVE_FORMAT_PCM
>   Channels      : 2
>   Sample Rate   : 44100
>   Block Align   : 4
>   Bit Width     : 16
>   Bytes/sec     : 176400
> data : 394301040
> End
> 
> ----------------------------------------
> Sample Rate : 44100
> Frames      : 98575260
> Channels    : 2
> Format      : 0x00010002
> Sections    : 0
> Seekable    : FALSE
> Duration    : 00:37:15.267
> Signal Max  : 31658 (-0.30 dB)

###  sndfile-info sample.wav ----- 1.0.25

> Length : 394301084
> RIFF : 394301076
> WAVE
> fmt  : 16
>   Format        : 0x1 => WAVE_FORMAT_PCM
>   Channels      : 2
>   Sample Rate   : 44100
>   Block Align   : 4
>   Bit Width     : 16
>   Bytes/sec     : 176400
> data : 394301040
> End
> 
> ----------------------------------------
> Sample Rate : 44100
> Frames      : 98575260
> Channels    : 2
> Format      : 0x00010002
> Sections    : 1
> Seekable    : TRUE
> Duration    : 00:37:15.267
> Signal Max  : 31658 (-0.30 dB)

###  ./configure output
`
-=-=-=-=-=-=-=-=-=-= Configuration Complete =-=-=-=-=-=-=-=-=-=-

 

>  Configuration summary :
> 
>     libsndfile version : .................. 1.0.26
> 
>     Host CPU : ............................ x86_64
>     Host Vendor : ......................... pc
>     Host OS : ............................. linux-gnu
> 
>     Experimental code : ................... no
>     Using ALSA in example programs : ...... yes
>     External FLAC/Ogg/Vorbis : ............ yes
> 
>   Tools :
> 
>     Compiler is Clang : ................... no
>     Compiler is GCC : ..................... yes
>     GCC version : ......................... 5.3.0
>     Sanitizer enabled : ................... no
>     Stack smash protection : .............. no
> 
>   Installation directories :
> 
>     Library directory : ................... /usr/local/lib
>     Program directory : ................... /usr/local/bin
>     Pkgconfig directory : ................. /usr/local/lib/pkgconfig
>     HTML docs directory : ................. /usr/local/share/doc/
> 
> Compiling some other packages against libsndfile may require
> the addition of '/usr/local/lib/pkgconfig' to the
> PKG_CONFIG_PATH environment variable.
> 
> make: Nothing to be done for 'genfiles'.
> make: Nothing to be done for 'genfiles'.

`

**Comment by erikd** [comment]
I'm pretty sure this was fixed in commits 776308d728 and f29c0dc209 . These will be in the next release.

**Comment by zaps166** [comment]
> These will be in the next release.

When we can expect the new release?

Unfortunately "seekable" breaks `libmirage` which causes that `cdemu` can't mount any Audio CD image which uses CUE and FLAC/WAVE file (it thinks that file is not seekable)...

**Comment by MaycneSonahoz** [comment]
This also causes an issue in Blender VSE.
https://bugs.archlinux.org/task/48679

**Comment by erikd** [comment]
Version 1.0.27 has been released and its at http://www.mega-nerd.com/libsndfile/#Download ,
