### ISSUE TITLE
api documentation does not explain writef / write difference

### ISSUE THREAD

**Issue by archenemies** [erikd/libsndfile#129]
I just installed the latest 'libsndfile' from the Arch repos.

It doesn't look like the API documentation explains the difference between write and writef, or read and readf. Perhaps it's obvious if you know the difference between "frames" and "items", but I don't...

Let me know if I'm missing something!

file:///usr/share/doc/libsndfile/api.html#writef

Also, there seems to be a lot of copy/pasted material at this point in the documentation, which makes it a bit hard to tell when I should skim and when I should read carefully.

**Comment by erikd** [comment]
`items` and `frames` are explained in the FAQ : http://www.mega-nerd.com/libsndfile/FAQ.html#Q012

I been hackin on this library for nearly 20 years and I know it inside and out. I am therefore the very worst person to choose to write the documentation. Good quality patches gladly accepted.

**Comment by archenemies** [comment]
So, with two channels, the only difference between sf_read_short and
sf_readf_short is that the second version expects the count (the last
argument) to be half as large?

**Comment by erikd** [comment]
That's correct and furthermore, for N channels, the argument passed to `sf_read_X` would be `N` times as large as the value passed to `sf_readf_X`.

**Comment by archenemies** [comment]
How about this. I did some de-duplication and included your explanation on the difference between the items and frames functions. I edited the HTML directly because it didn't seem to be generated from another format.

[api.patch.txt](https://github.com/erikd/libsndfile/files/206774/api.patch.txt)

(Strangely, github doesn't allow us to attach files called ".patch" so I called it .patch.txt...)

**Comment by archenemies** [comment]
Thank you.

**Comment by erikd** [comment]
Thank you!
