### ISSUE TITLE
How can one use an array of Shorts containing IFFT Data to write a 16bit WAV file using Libsndfile?

### ISSUE THREAD

**Issue by DCooksey** [erikd/libsndfile#131]
I am new to Audio Programming and have been having quite some trouble using Libsndfile to write a 16bit wav file. So the part where I am showing the code is from after the IFFT data has been retrieved. At the moment I'm managing to create "test.wav" But is of size 0, containing no information; a junk file. Any help would be astronomically appreciated, thank you!

The extracted relevant code:

 short audioStream[65536];
 float ifftData[65536];

 //Represent float data as short
 for(int i = 0; i < 65536; i++) {
    audioStream[i] = ifftData[i] * 32767;
 }

 const char *fname = "test.wav";

 //SNDFILE 
 create_file (fname, SF_FORMAT_WAV | SF_FORMAT_PCM_16) ;

 void create_file (const char * fname, int format) {

 SNDFILE *file2;
 SF_INFO x;

 x.samplerate = 44100;
 x.frames = 65536;
 x.format = format;
 x.channels = 1;

 file2 = sf_open(fname,SFM_WRITE,&x);

 sf_write_short(file2, audioStream, 65536);

 sf_close(file2);

 }

**Comment by erikd** [comment]
Your problems have nothing to do with libsndfile and everything to do with being an inexperienced C programmer.

A number of problems:

* Your program has bugs but your compiler is not warning you about them. If you are using GCC or Clang, I recommend that you add `-Wall` to the command line to turn on basic warnings. Once truned on fix all the issuess. (There are also other warnings enabled by `-Wextra`.)

* Your code had zero error checking. Error checking would have help you debug the problem. For example:

```
file2 = sf_open(fname,SFM_WRITE,&x);
if (file2 == NULL)
    printf ("sf_open failed : %s\n", sf_strerror (file2));
```

* You didn't seem to read the documentation (http://www.mega-nerd.com/libsndfile/api.html, specifically Notes 1 and 2, which would explain that even if you have `float` data you can write it to a 16 bit WAV file by having libsndfile do the conversion).

* You didn't look at the example programs : https://github.com/erikd/libsndfile/tree/master/examples

**Comment by DCooksey** [comment]
Thank you very much for responding to me, it means a lot. Apologies, I am an inexperienced C programmer. I am an CS undergraduate trying to complete a audio denoising project in C++, I am new to the language. Trying as best as I can to learn autonomously as C++ programming was not a provided course. I will look into everything you have mentioned. 

Massive respect for your work,
Dean.

**Comment by erikd** [comment]
Thanks. Closing this.
