### ISSUE TITLE
libtoolize fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by memnochproxy** [erikd/libsndfile#132]
I don't know how to get around this error. Any suggestions?
```
jreynolds@localhost ~/libsndfile $ libtoolize
/usr/bin/libtoolize: 1: eval: hookable_fns+=: not found
/usr/bin/libtoolize: 1: eval: hookable_fns+=: not found
/usr/bin/libtoolize: 1: eval: hookable_fns+=: not found
/usr/bin/libtoolize: 1: eval: hookable_fns+=: not found
libtoolize:   error: 'func_options_prep' does not accept hook functions.
```

**Comment by erikd** [comment]
That really does not look like a libsndfile problem. It looks much more like a libtool problem.

However, I never run libtool directly I use the `autogen.sh` script thats in the repo. Try doing just:

```
./autogen.sh
```

and see if that works.

**Comment by memnochproxy** [comment]
That's a good suggestion. I made sure that libtool and libtool-bin were installed, but libtool doesn't appear to be found.

```
> which libtool
/usr/bin/libtool

 > libtool --version
libtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

 > ./autogen.sh 
checking for autogen ... yes
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... nope.

You must have libtool installed to compile libsndfile.
Download the appropriate package for your system,
or get the source from one of the GNU ftp sites
listed in http://www.gnu.org/order/ftp.html
checking for pkg-config ... yes
checking for python ... yes
```

**Comment by erikd** [comment]
What does `dpkg -l | grep libtool` say?

**Comment by erikd** [comment]
I just installed Xenial in a chroot and everything works fine here.

**Comment by erikd** [comment]
Can I close this?

**Comment by nixomose** [comment]
had the same problem, ran as root and it went away.

**Comment by memnochproxy** [comment]
@nixmose interesting, running as root fixes it for me as well.
@erikd sorry for not staying closer to this thread, got pulled away. 
Closing is OK with me.

**Comment by princeofdream** [comment]
edit libtoolize，chang first line from /bin/sh to /bin/bash will work
