### ISSUE TITLE
Binaries for Windows

### ISSUE THREAD

**Issue by jrmoore** [erikd/libsndfile#134]
Currently there are no binaries for Windows available in the website (1.0.26 or the newer 1.0.27), are they still going to be provided?

On a side note, what would be the build procedure for Windows? Cross-compiling is the only way right?

Thank you for your time.

**Comment by erikd** [comment]
Have you looked at http://www.mega-nerd.com/libsndfile/#Download which in turn has links to

http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.27-w32-setup.exe
http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.27-w64-setup.exe

> On a side note, what would be the build procedure for Windows? Cross-compiling is the only way right?

It's probably possible to build natively but I haven't done that in over a decade. The only method of building for Windows I personally support is cross compiling from Linux.

**Comment by erikd** [comment]
Just realised that in http://www.mega-nerd.com/libsndfile/files/ you will also find the binaries bundled into a Zip file.

**Comment by jrmoore** [comment]
Oh! Thank you very much, I just downloaded it.

It's greatly appreciated the provided binaries for Windows, Linux distributions generally have the package in their repositories and it's easy to build it there natively. I wish it was that easy for us Windows users.

**Comment by erikd** [comment]
I'll close this issue then.
