### ISSUE TITLE
potential minor bug in alac_close

### ISSUE THREAD

**Issue by rryan** [erikd/libsndfile#135]
https://github.com/erikd/libsndfile/blob/master/src/alac.c#L173

```c
uint8_t *kuki_data [plac->kuki_size] ;
```

I may be wrong, but based on my read of alac_get_magic_cookie, this was intended to be:

```c
uint8_t kuki_data [plac->kuki_size] ;
```

**Comment by erikd** [comment]
RJ Ryan wrote:

> https://github.com/erikd/libsndfile/blob/master/src/alac.c#L173
> 
> ```c
> uint8_t *kuki_data [plac->kuki_size] ;
> ```
> 
> I may be wrong, but based on my read of alac_get_magic_cookie, this was intended to be:
> 
> ```c
> uint8_t kuki_data [plac->kuki_size] ;

Indeed, you are correct. How did you find this? was it just by inspection?

Erik
-- 
----------------------------------------------------------------------
Erik de Castro Lopo
http://www.mega-nerd.com/

**Comment by rryan** [comment]
I was replacing it with an alloca for compiling with MSVC (which if I understand correctly, does not seem to support the C99 variable length array feature relied on here).

**Comment by erikd** [comment]
What version of MSVC doesn't support C99 variable arrays? I keep getting people telling me that MSVC does support C99 now.

**Comment by rryan** [comment]
We're using Visual Studio Express 2015 Desktop.

I'm not sure where to find a definitive reference on what is supported, but you may have heard that they added C99 library support, not language features:
https://msdn.microsoft.com/en-us/library/hh409293.aspx#BK_CRT

> C99 Conformance Visual Studio 2015 fully implements the C99 Standard Library, with the exception of any library features that depend on compiler features not yet supported by the Visual C++ compiler (for example, <tgmath.h> is not implemented).

This SO post seems to suggest variable length arrays were not among the features implemented in VS2013. http://stackoverflow.com/a/28118893
