### ISSUE TITLE
Remove usage of Variable Length Arrays

### ISSUE THREAD

**Issue by erikd** [erikd/libsndfile#140]
VLAs are a bad idea and should be replaced. Once they're gone,  `-Wvla` added to the default compile flags.

**Comment by erikd** [comment]
This has been fixed in the latest set of patches. Also updated `configure.ac` to add `-Wvla` to `CFLAGS`.

**Comment by evpobr** [comment]
@erikd, now libsndfile can be compiled with MSVC 2015 native compiler.
