### ISSUE TITLE
`truncate` is missing under Win32

### ISSUE THREAD

**Issue by evpobr** [erikd/libsndfile#143]
`truncate` is POSIX function and may not be available. MSVC 2015 doesn't have it. We must solve this problem to get a working test suite under Win32.

**Comment by erikd** [comment]
I presume this is for the tests, because the library itself there is a `psf_truncate` with a Win32 implementation.

If it is for the tests, I suggest you copy the code from `psf_truncate` into a file in `tests/` and adapt it.

**Comment by evpobr** [comment]
Yes, it's about tests. Look at [`write_read_test`](https://github.com/erikd/libsndfile/blob/master/tests/write_read_test.tpl#L862). No matter Win32 platform or not, this code is always used. I have no idea how to deal with it and how to test dependent features under Win32.

**Comment by erikd** [comment]
First you need a windows inplementation of `truncate`. You can then put is in `tests/utils.tpl` wrapped in an `@if  USE_WINDOWS_API`. You will need the a function prototype in the header section as well.

**Comment by erikd** [comment]
This was fixed in:
```
commit 08dfe89c61918cd1bc59d95b589ec841b90c68c1
Author: Erik de Castro Lopo <erikd@mega-nerd.com>
Date:   Fri Sep 9 19:12:39 2016 +1000

    tests: Remove need for POSIX `truncate` function
    
    Windows doesn't have `truncate` and since it was only being used
    to truncate the file to zero length, implement a cross platform
    `truncate_file_to_zero`.
    
    Based on an idea from <evpobr@gmail.com>.
```
