### ISSUE TITLE
Figure out how to auto-generate files on Windows

### ISSUE THREAD

**Issue by erikd** [erikd/libsndfile#154]
@evpobr In order to get the Travis build working on Linux and OSX, I had to revert a commit that added auto-generated files to repo. The revert commit was:

```
commit 260af75a1dd47d29eb831335757ae03f2c5bb6cd
Author: Erik de Castro Lopo <erikd@mega-nerd.com>
Date:   Sun Sep 11 10:15:21 2016 +1000

    Revert "Added in autogened files"
```

The Travis build script now uses `./autogen.sh && ./configure` to generate these files before doing a CMake based build followed by an Autotool based build.

Interested in any suggestions you may have.

**Comment by erikd** [comment]
One thing that should work now (and should always work) is using the autotool based build to generated a source code tarball (`make dist`) and then transferring that generated tarball to a Windows system and using CMake to build it.

**Comment by evpobr** [comment]
Nice work @erikd, but my opinion is to get rid of all autogen code, if there is nothing platform specific. I as understand, it just generates some similar functions by template.

It we want real cross-platform configuring, we must remove as much external program dependencies as we can. User must just type `cmake` and get working project or makefile.

Another candidate is Python. Generating DEF-file and Sym-files is cool, but we can simply add all these files and remove Python dependency.

These changes will not harm Autotools build system but will help CMake to be much more portable.

**Comment by erikd** [comment]
*Really* not keen on the idea of committing the templated output files to revision control.

While I agree that making source distribution source tarballs as portable as possible is a good idea, I am not convinced about that for the sources here on Github, especially if it comes at the cost of increasing the maintenance burden.

**Comment by evpobr** [comment]
OK, i stuck here. If you want MSVC solution, how to get autogen-generated  sources?  Install MinGW, run autogen there, then run CMake?

**Comment by erikd** [comment]
How important is it for people to build with MSVC from a git checkout?

**Comment by evpobr** [comment]
I see two ways:

First is to commit generated sources, remove autogen step from scripts, delete autogen's def and tpl files. Autotools works, Windows users happy.

Second way is to use autogen under CMake, Windows users must install autogen for Windows and add it to PATH. Linux users are happy, Windows users are not, but they can get their solution at least.

**Comment by evpobr** [comment]
> How important is it for people to build with MSVC from a git checkout?

I don't know. But they can try and will get errors.

**Comment by erikd** [comment]
What scripting environments could one reasonably assume someone with MSVC on Window would have?

**Comment by evpobr** [comment]
We must avoid any new scripting environment, CMake itself is scripting environment. I can write CMake script to generate symbols files. It is possible to create CMake script, that will do autogen work, but it is much harder.

**Comment by erikd** [comment]
Ok, lets think about it some more. We should not rush to a solution. There are more important things to work on at the moment like the test suite.

**Comment by evpobr** [comment]
Yes, tests are very important, I will start to implement them today. At this moment I will add autogen to CMake requirements, script will fail if no autogen found. At least user will see, where is the problem.

**Comment by evpobr** [comment]
Didn't found any `autogen` distributions for Win32 and it is really bad. It seems like people who wants to build `libsndfile` with MSVC must build Win32 version of `autogen` first. I think no one will use this solution, it is much easier to use MinGW.

**Comment by chadwackerman** [comment]
Just poking my head in to make sure @erikd is still shooting himself in the foot regarding running a git project that actually builds when you check it out. Confirmed.

Dude... simplicity! You spent two years dicking with cmake and you *still* have to install autotools to use the cmake build? Good lord.

**Comment by evpobr** [comment]
This proglem is related to #71.

**Comment by evpobr** [comment]
I will add autogeneration of sources to CMake buildsystem, but it will work under Linux and probably under MacOSX.

**Comment by evpobr** [comment]
@erikd, any news about python based autogen replacement?

**Comment by erikd** [comment]
Unfortunately I have not had sufficient time or morivation.

**Comment by evpobr** [comment]
@madebr, i really hope you will continue the work begun in #210.
