### ISSUE TITLE
Improve C inline support

### ISSUE THREAD

**Issue by evpobr** [erikd/libsndfile#157]
Some related checks exists to enable inline support in GCC, but nothing is done to to support `__inline__` or `__inline`. I guess MS supports `inline` from VS2015 only, but has `__inline`.

**Comment by erikd** [comment]
`common.h` could have something like
```
#if defined _MSVC && ! defined (inline)
#define inline __inline
#endif
```

**Comment by evpobr** [comment]
VS2013 build failed - it doesn't know what is `inline`. Yes, we detect and configure `inline` properly, but some code do not use global `config.h`. It is `libgsm` and `libalac`. `libg72x` is affected too, but it doesn't use `inline`.

**Comment by erikd** [comment]
Would it be possible to just say VS2013 is not supported?

**Comment by evpobr** [comment]
I thought about it. It is better to fix this. Any compiler in C90-compatibility mode will suffer.

**Comment by erikd** [comment]
Absolutely. C99 is a 16+ year old standard. Its more than OK to require it.
