### ISSUE TITLE
Problem with wav file?

### ISSUE THREAD

**Issue by timmyL17** [erikd/libsndfile#167]
Hi,

I'm trying to load an amb file using libsndfile, and I'm getting an error

Error on opening file: Error in WAV file. No 'data' chunk marker.

Specifically, this is the file I'm trying to use

http://ambisonic-files.s3.amazonaws.com/JL/When_Geese_Go_Bad.amb

However, it seems to be file specific. There is another amb file from the same collection that loads ok

http://ambisonics.dreamhosters.com/AMB/pink_pan_H.amb

Is there something wrong with the first file?

**Comment by erikd** [comment]
What version of libsndfile are you using? What does the `sndfile-info` program say about the file?

**Comment by timmyL17** [comment]
I'm using version 1.0.27, on 64 bit Windows 10. sndfile-info says:

Error : Not able to open input file data\When_Geese_Go_Bad.amb.
File : data\When_Geese_Go_Bad.amb
Length : 48499288
RIFF : 48499280
WAVE
fmt  : 40
  Format        : 0xFFFE => WAVE_FORMAT_EXTENSIBLE
  Channels      : 4
  Sample Rate   : 48000
  Block Align   : 12
  Bit Width     : 24
  Bytes/sec     : 576000
  Valid Bits    : 24
  Channel Mask  : 0x0 (should not be zero)
  Subformat
    esf_field1 : 0x1
    esf_field2 : 0x721
    esf_field3 : 0x11D3
    esf_field4 : 0x86 0x44 0xC8 0xC1 0xCA 0x0 0x0 0x0
    format : pcm (Ambisonic B)
PEAK : 40
  version    : 1
  time stamp : 1145527493
    Ch   Position       Value
     0   1820876        1
     1   1820475        1
     2   1821202        1
     3   450827         1
cue  : 28
  Count : 1
   Cue ID : 1718183539  Pos :     0  Chunk : data  Chk Start : 0  Blk Start : 0  Offset :     0
LIST : 2016
  adtl
  *** note : 2004 (too big)
Have 0 marker at position 2188 (0x88C).

Error in WAV file. No 'data' chunk marker.


However, in cygwin using libsndfile version 1.0.25, sndfile-info does not give this error:

Version : libsndfile-1.0.25

========================================
File : data/When_Geese_Go_Bad.amb
Length : 48499288
RIFF : 48499280
WAVE
fmt  : 40
  Format        : 0xFFFE => WAVE_FORMAT_EXTENSIBLE
  Channels      : 4
  Sample Rate   : 48000
  Block Align   : 12
  Bit Width     : 24
  Bytes/sec     : 576000
  Valid Bits    : 24
  Channel Mask  : 0x0 (should not be zero)
  Subformat
    esf_field1 : 0x1
    esf_field2 : 0x721
    esf_field3 : 0x11D3
    esf_field4 : 0x86 0x44 0xC8 0xC1 0xCA 0x0 0x0 0x0
    format : pcm (Ambisonic B)
PEAK : 40
  version    : 1
  time stamp : 1145527493
    Ch   Position       Value
     0   1820876        1
     1   1820475        1
     2   1821202        1
     3   450827         1
cue  : 28
  Count : 1
   Cue ID : 1718183539  Pos :     0  Chunk : data  Chk Start : 0  Blk Start : 0  Offset :     0
LIST : 2016
  adtl
    note : 2004
data : 48497112
End

----------------------------------------
Sample Rate : 48000
Frames      : 4041426
Channels    : 4
Format      : 0x00130003
Sections    : 1
Seekable    : TRUE
Duration    : 00:01:24.196
Signal Max  : 8.38861e+06 (0.00 dB)


Maybe it is a problem with the windows build? I can try the 32 bit windows library if you think that could be the issue.

**Comment by erikd** [comment]
Version 1.0.27 works correctly on 64 bit Linux. I'd be curious to see if the 32 bit version works correctly on WIndows.

**Comment by timmyL17** [comment]
The 32 bit version gives the same error.

(I miss the days when I could solely use Linux...)

**Comment by erikd** [comment]
Ok, that's useful info. Give a day or two to look into this.

**Comment by timmyL17** [comment]
Thanks for your help, let me know if I can help with testing at all.

**Comment by evpobr** [comment]
@timmyL17, can you check [my build](https://github.com/evpobr/libsndfile/releases/tag/1.0.28)?

**Comment by erikd** [comment]
I've reproduced it with git HEAD on Linux. When I tested earlier I was inadvertently using the 1.0.25 release version of `sndfie-info`.

I also have a fix, but I'd prefer not to commit it until I have a test to go with it.

**Comment by timmyL17** [comment]
Ok. The build you sent also has the error, but I'm assuming that is a build without your fix yet. This isn't urgent, I can import then export the files using Adobe Audition to get libsndfile to read them currently.

**Comment by erikd** [comment]
@timmyL17 Correct, @evpobr 's build does not have the fix.

**Comment by erikd** [comment]
And my "fix" doesn't work for both files.

**Comment by erikd** [comment]
Ok, now I really do think I have a fix. In the process of writing a test for this as well.
