### ISSUE TITLE
libsndfile-dev install on mac

### ISSUE THREAD

**Issue by cherishsantosh** [erikd/libsndfile#187]
Getting error on Mac

making install mod_sndfile
Makefile:907: **\* You must install libsndfile-dev to build mod_sndfile.  Stop.
make[3]: **\* [mod_sndfile-install] Error 1
make[2]: **\* [install-recursive] Error 1
make[1]: **\* [install-recursive] Error 1
make: **\* [install] Error 2

**Comment by erikd** [comment]
The is problem with the Makefile for `mod_sndfile`. I suggest you raise an issue there.

**Comment by erikd** [comment]
Closing this.
