### ISSUE TITLE
Documentation of dither is missing

### ISSUE THREAD

**Issue by JosepMaJAZ** [erikd/libsndfile#188]
The documentation of the dither option is missing.

In the documentation there's a dither.html file which is just an outdated copy of the command.html file with a comment that the dither option needs to be added.

The only "documentation" in existence is the dither_test.c file.

**Comment by erikd** [comment]
The dithering code was never completed and hence never documented.

**Comment by erikd** [comment]
I've deleted the file `doc/dither.html` from the repo. It can be resurrected when and if dither is actually implemented.
