### ISSUE TITLE
website broken

### ISSUE THREAD

**Issue by yupengfei** [erikd/libsndfile#192]
http://www.mega-nerd.com/libsndfile/ is now down and can not be opened.

**Comment by erikd** [comment]
Please explain what symptoms you are see that suggest it "is now down and can not be opened".

As a test, I just accessed this via the Tor network and it was fine.

**Comment by uklauer** [comment]
Works fine for me, too. An issue with the Great Firewall perhaps?

**Comment by yupengfei** [comment]
No, it is down, I can visit google and I can not visit www.mega-nerd.com/libsndfile/, it can be opened about ten hour ago but not now.@erikd @uklauer

**Comment by erikd** [comment]
Sorry, its not. I tested again just now, both directly and via the Tor network.

Are you trying to access the website from within China?

**Comment by yupengfei** [comment]
yes, maybe because the Great Firewall, I will close this issue.

**Comment by erikd** [comment]
The website is on a Linode VPS which is incredibly reliable.
