### ISSUE TITLE
utf8 or unicode or something in filename won't load

### ISSUE THREAD

**Issue by dts350z** [erikd/libsndfile#195]
I've got a file with some kind of "special" characters in the name I can't load with sf_open or sf_wchar_open, but it may be that I just don't understand how to use sf_wchar_open.

Here is the hex representation of the filename:

30 32 2E 20 43 61 6E 20 41 74 69 6C 6C 61 20 2D 20 48 61 6D 61 6D 64 61 20 00 6C 6B 20 47 6F 7A 79 61 73 6C 61 72 00

copy and paste from my en locale computer looks like this:

02. Can Atilla - Hamamda İlk Gozyasları.flac

If I rename the file it works fine, but I want my application to support all kinds of filenames and this file also loads in adobe audition, foobar2000, etc.

My program has command line arguments made from const char* so maybe I need to start there? I've done lots of googling and tried different narrow to wide, multiyte to utf, etc. but I can't find anything that works.

Thanks

**Comment by erikd** [comment]
What OS are you on?

**Comment by dts350z** [comment]
Windows 7 64bit

**Comment by erikd** [comment]
Unfortunately I know very little about file system character encodings on Windows. I use Linux almost exclusively.

There is an example of the use of `sf_wchar_open` at https://github.com/erikd/libsndfile/blob/master/tests/locale_test.c#L57 but I'm not sure how much that will help.

**Comment by evpobr** [comment]
@dts350z , [GetCommandLineW](https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms683156(v=vs.85).aspx) function to get unicode command line and `sf_wchar_open`.

**Comment by dts350z** [comment]
I've spent hours on this and I can't figure it out.

There are so many options, Unicode, Multibyte, Utf-8, etc. etc. and so many
techniques, but I don't know which of those the filename is in and which of
those works with sf_wchar_open.

Following the Microsoft Instructions for unicode:

int main(int ac, LPCTSTR av[]) {
...
if (! (file = sf_wchar_open(av[i + 1], SFM_READ, &file_info))) {

compiles but doesn't work for any filename

I'm still stumped.

**Comment by evpobr** [comment]
No, you use ANSI 'main' function. Use unicode 'wmain' version. Or use 'Get
CommandLineW'.

16 февр. 2017 г. 7:40 пользователь "dts350z" <notifications@github.com>
написал:

> I've spent hours on this and I can't figure it out.
>
> There are so many options, Unicode, Multibyte, Utf-8, etc. etc. and so many
> techniques, but I don't know which of those the filename is in and which of
> those works with sf_wchar_open.
>
> Following the Microsoft Instructions for unicode:
>
> int main(int ac, LPCTSTR av[]) {
> ...
> if (! (file = sf_wchar_open(av[i + 1], SFM_READ, &file_info))) {
>
> compiles but doesn't work for any filename
>
> I'm still stumped.
>
>
>

**Comment by dts350z** [comment]
OK that's a working combination for both "regular" files and the file I
couldn't open!

int wmain( int ac, wchar_t *av[ ], wchar_t *envp[ ] ) {
...
if (! (file = sf_wchar_open(av[i + 1], SFM_READ, &file_info))) {


Now I just have to teach the rest of my program to deal with those changes.

Thanks!

**Comment by erikd** [comment]
Thanks @evpobr !

@dts350z ok to close this?

**Comment by dts350z** [comment]
sorry, yes, OK to close
