### ISSUE TITLE
Incomplete documentation distibution

### ISSUE THREAD

**Issue by evpobr** [erikd/libsndfile#201]
It seems like some documentation files are not listed in `/doc/Makefile.am` `html_DATA` variable:

    print.css
    development.html
    donate.html
    linux_games_programming.txt

**Comment by bagong** [comment]
Yea, and dither.html seems not to exist anymore

**Comment by evpobr** [comment]
> Yea, and dither.html seems not to exist anymore

It is deleted from `/doc/Makefile.am`, but i didn't reflect these changes in `CMakeLists.txt`.

**Comment by bagong** [comment]
ah, okay...

**Comment by evpobr** [comment]
When @erikd will confirm we must add all these files, i will merge evpobr/libsndfile#7 to my `cmake-config` branch.

**Comment by bagong** [comment]
If he'd prefer not to have another contributor you can just copy my stuff and add it to yours.

**Comment by evpobr** [comment]
@bagong , important feature is not complete yet, so i don't want merge something before it is not ready. Just wait a little.

**Comment by bagong** [comment]
Sure...

**Comment by erikd** [comment]
The only one of those file that is actually worth added is `print.css`.
