### ISSUE TITLE
Uninitialized format in error_test

### ISSUE THREAD

**Issue by yugr** [erikd/libsndfile#209]
`error_value_test` function in error_test.c does not zero-initialize `sfinfo.format` field before passing it to `sf_open`:

    SF_INFO sfinfo ;
    ...
    file = sf_open (filename, SFM_READ, &sfinfo) ;

This later triggeres uninitialized read in `psf_open_file`:

    if (psf->file.mode == SFM_READ)
    {	if ((SF_CONTAINER (sfinfo->format)) == SF_FORMAT_RAW)

Valgrind report is

    ==22949== Conditional jump or move depends on uninitialised value(s)
    ==22949==    at 0x524E82D: psf_open_file (/build/libsndfile-1.0.25/src/sndfile.c:2591)
    ==22949==    by 0x40186E: error_value_test (/build/libsndfile-1.0.25/tests/error_test.c:86)
    ==22949==    by 0x40186E: main (/build/libsndfile-1.0.25/tests/error_test.c:236)

The issue has been found using Valgrind and [debian_pkg_test](https://github.com/yugr/debian_pkg_test).

**Comment by erikd** [comment]
Thanks!
