### ISSUE TITLE
Cross-compilation issues with symbol files generation

### ISSUE THREAD

**Issue by evpobr** [erikd/libsndfile#211]
ae272b5 causes build failures when cross-compiling, as described in #207. CMake toolchain is not affected, since it uses autogenerated DEF for Windows and visibility control for other platforms.

**Comment by erikd** [comment]
I've reverted the change that switched the `create_symbols_file.py` script to a C program. Will need this for the upcoming release anyway. Could also switch the the `SNDFILE_API` way of doing things but I know this with work.

**Comment by erikd** [comment]
Restoring `create_symbol_files.py` fixes this.

**Comment by evpobr** [comment]
@erikd, some tips: If the name of the 6c401c6 commit would be "Switch back to create_symbols_file.py **#211**", then a reference to it would appear here.

 If the name would be "Switch back to create_symbols_file.py, **closes #211**", then after merging into the master branch this issue would be closed automatically. [More info](https://guides.github.com/features/issues/).
