### ISSUE TITLE
How to read WAV file?

### ISSUE THREAD

**Issue by ProgrammingLife** [erikd/libsndfile#214]
As I see the example on how to read wave files here: https://github.com/erikd/libsndfile/blob/master/examples/sndfilehandle.cc#L63
I don't understand what to do next. Is it only 1024 bytes that read from the file? But what if file is larger than 1024 bytes? How to loop it?

**Comment by evpobr** [comment]
Look at `sndfile.hh`, `SndfileHandle::read` is wrapper of C `sf_read_XXXX` functions, and then you have documentation to [read](http://www.mega-nerd.com/libsndfile/api.html).

> The sf_read_XXXX and sf_readf_XXXX functions return the number of items or frames read, respectively. Unless the end of the file was reached during the read, the return value should equal the number of objects requested. Attempts to read beyond the end of the file will not result in an error but will cause the read functions to return less than the number of objects requested or 0 if already at the end of the file.

Short answer:

```cpp
while (file.read (buffer, BUFFER_LEN) != 0) {
    ...
}
```
