### ISSUE TITLE
pkg-config (XIPH CFLAGS) are not honored

### ISSUE THREAD

**Issue by x42** [erikd/libsndfile#215]
Since libsndfile 1.0.28 `EXTERNAL_XIPH_CFLAGS` are no longer honored. This is due to the addition of explicit `libsndfile_la_CFLAGS` in 1bff04b3aea3b433af079d70bc9bb20b8e502775 which overrides the default flags. The following patch fixes this:

```
diff --git a/src/Makefile.am b/src/Makefile.am
index e7640cd..0465e6e 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -35,7 +35,7 @@ else
 WIN_VERSION_FILE =
 endif
 
-libsndfile_la_CFLAGS = $(CFLAG_VISIBILITY)
+libsndfile_la_CFLAGS = $(CFLAG_VISIBILITY) $(EXTERNAL_XIPH_CFLAGS)
 libsndfile_la_CPPFLAGS = -DSNDFILE_EXPORTS
 
 #===============================================================================
```

Before applying this change, it would be prudent to verify that other CFLAGS are passed through as well.

PS. removing the line `libsndfile_la_CPPFLAGS` also fixes the issue, in that case the default `AM_CPPFLAGS` are used.

**Comment by evpobr** [comment]
@x42 , thanks.

@erikd, i can make pull request to close it.

**Comment by erikd** [comment]
No need. I already pulled the patch and tested it before I left for work this morning. Just need to put a commit message on it.

**Comment by erikd** [comment]
The other CFLAGS do get passed through.  It was really just a problem of `AM_CPPFLAGS` being ignored once `libsndfile_la_CPPFLAGS` was added.
