### ISSUE TITLE
rf64 regression in string_multi_set_test

### ISSUE THREAD

**Issue by mhlavink** [erikd/libsndfile#229]
Hi,
there seems to be a regression in latest release 1.0.28 when compared to 1.0.27

  libsndfile-1.0.28 passed tests on W64 files.
----------------------------------------------------------------------
    pcm_test_char                  : char.rf64 ............... ok
    pcm_test_short                 : short.rf64 .............. ok
    pcm_test_24bit                 : 24bit.rf64 .............. ok
    pcm_test_int                   : int.rf64 ................ ok
    pcm_test_float                 : float.rf64 .............. ok
    pcm_test_double                : double.rf64 ............. ok
    empty_file_test                : empty_char.rf64 ......... ok
    empty_file_test                : empty_short.rf64 ........ ok
    empty_file_test                : empty_float.rf64 ........ ok
    update_header_test             : header.rf64 ............. ok
    update_seek_short_test         : header_short.rf64 ....... ok
    update_seek_int_test           : header_int.rf64 ......... ok
    update_seek_float_test         : header_float.rf64 ....... ok
    update_seek_double_test        : header_double.rf64 ...... ok
    zero_data_test                 : zerolen.rf64 ............ ok
    filesystem_full_test           : /dev/full ............... ok
    permission_test                : readonly.rf64 ........... ok
    rf64_downgrade_test            : downgrade.wav ........... ok
    string_start_test              : strings.rf64 ............ ok
    string_start_end_test          : strings.rf64 ............ ok
    string_multi_set_test          : multi.rf64 .............. 
Line 520: sf_open (SFM_READ) failed : Error in RF64 file. No 'data' chunk marker.
File : multi.rf64
Length : 2458
RF64
  WAVE
ds64 : 28
  Riff size : 2450
  Data size : 2048
  Frames    : 1024
  Table length : 0
fmt  : 40
  Format        : 0xFFFE => WAVE_FORMAT_EXTENSIBLE
  Channels      : 1
  Sample Rate   : 44100
  Block Align   : 2
  Bit Width     : 16
  Bytes/sec     : 88200
  Valid Bits    : 16
  Channel Mask  : 0x4 (C)
  Subformat
    esf_field1 : 0x1
    esf_field2 : 0x0
    esf_field3 : 0x10
    esf_field4 : 0x80 0x0 0x0 0xAA 0x0 0x38 0x9B 0x71 
    format : pcm
*** PAD  : 0 (unknown marker)
Have 0 marker at position 112 (0x70).
make[1]: Leaving directory '/builddir/build/BUILD/libsndfile-1.0.28/tests'
RPM build errors:
make[1]: *** [Makefile:1213: check] Error 1
make: *** [Makefile:531: check-recursive] Error 1

This regression happens only on armv7hl architecture, other usual architectures (like i686,x86_64) pass this test.

This seems to be caused by this commit:
https://github.com/erikd/libsndfile/commit/9a844f2e7b775c329153af6ca468ab994d468898
as reverting this change causes this test to pass on arm (and other architectures).

**Comment by erikd** [comment]
Do you happen to know if this works on `armv7hf`?

**Comment by erikd** [comment]
Also, please attach the file `multi.rf64` generated during that test.

**Comment by mhlavink** [comment]
hunfortunately, I can't verify if it works on armv7hf 
[multi.rf64.gz](https://github.com/erikd/libsndfile/files/917391/multi.rf64.gz)

**Comment by erikd** [comment]
Can you please test the fix on the `topic/rf64-bug` branch? Specifically, commit 78c7e80e .

**Comment by erikd** [comment]
Managed to verify that this was also a bug on armhf (using a Debian / Qemu chroot) and that the linked commit does not fix it.

**Comment by erikd** [comment]
Ok, actually fixed in commit e05b01fc4d of the `topic/rf64-bug` branch.

**Comment by awilfox** [comment]
Just wanted to note this is also an issue on 32-bit PowerPC as well.
