### ISSUE TITLE
Deprecate USE_WINDOWS_API

### ISSUE THREAD

**Issue by evpobr** [erikd/libsndfile#236]
Got some tests today - VS2017 can build libsndfile with POSIX API only. ~~Also most of tests are passed, `pcm_test` fails only, i guess i can fix it~~. All tests are passed.

Some MS-specific workarounds:

off_t is 32-bit
lseek -> _lseeki64
ftruncate -> _chsize_s
fflush -> _commit

I think it could be nice to have unified (more or less) API across all platforms.

No milestone yet, VS2017 is required (probably also VS2015).

**Comment by erikd** [comment]
> VS2017 can build libsndfile with POSIX API only.

In the past Microsoft's POSIX API compatibility was terrible, the functions were there but that had strange bugs, bugs that I spend many hours tracking down and working around. The `USE_WINDOWS_API` stuff works.

>  off_t is 32-bit

libsndfile supports many file format which are specifically designed to allow file sizes of larger than 4 gigabytes. Full support for those file types is not possible if `off_t` is only 32 bits.

**Comment by evpobr** [comment]
> libsndfile supports many file format which are specifically designed to allow file sizes of larger than 4 gigabytes. Full support for those file types is not possible if `off_t` is only 32 bits.

Yes. But we can set `sf_off_t` to `__int64` under Win32, [`_lseeki64`](https://msdn.microsoft.com/en-US/library/1yee101t.aspx) and [`_telli64`](https://msdn.microsoft.com/en-US/library/c3kc5e7a.aspx) can be used to work with large files.
