### ISSUE TITLE
Extraneous bytes after DATA chunk using RF64_AUTO_DOWNGRADE

### ISSUE THREAD

**Issue by CausticYarn** [erikd/libsndfile#238]
I am using libsndfile-1.0.28 with the RF64_AUTO_DOWNGRADE functionality (after this issue was fixed: https://github.com/erikd/libsndfile/issues/198).  

I am having an issue where after the downgrade, there are four extraneous zero bytes after the length field of the data chunk (so instead of 0xFFFFFFFF per the spec it is 0xFFFFFFFF00000000).  These bytes don't appear when not using the AUTO_DOWNGRADE functionality.

I am using the same code as in issue 198 except I changed the following line:

`memset(buffer, 0, sizeof(buffer));`

to 

`memset(buffer, 127, sizeof(buffer));`

to clearly demonstrate these four zero bytes are not part of the audio data.

![image](https://cloud.githubusercontent.com/assets/3424005/25066530/22e45200-21f6-11e7-870c-979a83f244cc.png)
![image](https://cloud.githubusercontent.com/assets/3424005/25066534/2ef529ca-21f6-11e7-9dab-39b68ef39cee.png)

Please let me know if you need any more information.

**Comment by CausticYarn** [comment]
I tested this on both Windows 10 x64 and Red Hat 7.

**Comment by erikd** [comment]
The fact that the ascii part of the hexdump of the file starts  with `RF64` means that no downgrade occurred.

**Comment by CausticYarn** [comment]
That's correct; both of these files are over 4GB. Sorry if I didn't make that clear.

When the downgrade does occur, the regular WAVE file is fine. But when the file is over 4GB, the RF64 contains these extraneous bytes when the RF64_AUTO_DOWNGRADE is enabled.

**Comment by erikd** [comment]
Pretty sure I've fixed this in commit 78c7e80 on the `topic/rf64-bug` branch?

**Comment by CausticYarn** [comment]
I built the current HEAD and tested, and the RF64 with RF64_AUTO_DOWNGRADE enabled does not have the extraneous bytes.

I did notice that when RF64_AUTO_DOWNGRADE is enabled, the RF64 has a `PAD ` chunk before the data section, which is not present when it is not enabled. Audacity had trouble reading the file with the `PAD `, although other tools seem ok with it. It's certainly within spec, but I wonder if it might be more compatible if the chunk is not there, since it doesn't seem to have any purpose.

**Comment by erikd** [comment]
> Audacity had trouble reading the file 

Audacity uses libsndfile. Either your are using an old version of Audacity or Audacity is being built against an old version of libsndfile (there are CVEs against versions < 1.0.27).

> I wonder if it might be more compatible if the chunk is not there, since it doesn't seem to have any purpose.

The chunk is there *because* of the downgrade. The RF64 headers are longer than than the RIFF/WAVE headers. Without re-writing the whole file, adding the `PAD` chunk is the only way to solve this problem. It is also the method *recommended* in the RF64 spec.

**Comment by erikd** [comment]
Sure enough, the Audacity [source tree](https://github.com/audacity/audacity/blob/master/lib-src/libsndfile/configure.ac) is using libsndfile 1.0.24. Version 1.0.25 was released in 2011.

**Comment by CausticYarn** [comment]
My understanding of the spec is that yes, you need to pad it with a `JUNK` chunk in the case that the file ends up being under 4GB. If the file is over 4GB, this `JUNK` chunk becomes the `ds64` chunk in the RF64.

However, the RF64 files created by the HEAD branch have _both_ a `JUNK` chunk and a `PAD ` chunk. It seems like the `ds64` chunk should be 28 bytes (8 bytes * 3 fields + 4 bytes for the table size which seems to be zero in the usual case), which should make the `JUNK` chunk 28 bytes if the wave file is under 4GB.  

In the tests that I ran, when the downgrade happens, the `JUNK` chunk is 24 bytes, and there is a `fact` chunk in the `RIFF` before the `data` chunk; the `fact` chunk seems to be for compressed audio so it's not clear why it's being written for a potential RF64 downgraded to RIFF.  It seems like to get the `data` chunk of either the RIFF with the `fact` chunk or the RF64 header to line up, there is the `PAD ` chunk with zero length.

I don't see a lot of details about the `PAD ` chunk; it seems to be just like the `JUNK` chunk so a compliant parser should just ignore it. However, I did try with the latest version of Audacity (v2.1.3) and it was able to handle an RF64 without the RF64_AUTO_DOWNGRADE option (and without the `PAD ` chunk) but not the one with the `PAD ` chunk. So I am still thinking that it's most compatible to have the `JUNK` chunk take care of all the necessary padding.

**Comment by erikd** [comment]
> Audacity (v2.1.3) 

Unless Audacity is using libsndfile 1.0.27 or libsndfile from git, it is using a version with *known* bugs that have been fixed.

> there is a fact chunk in the RIFF before the data chunk; the fact chunk seems to be for compressed audio so it's not clear why it's being written for a potential RF64 downgraded to RIFF

Thats not quite right. According to http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Docs/RIFFNEW.pdf (page 12), the `fact` chunks is required whenever the format is not `WAVE_FORMAT_PCM`.

Obviously there is a bit more to sort out on this issue.

**Comment by erikd** [comment]
I've investigated some more and decided there is nothing to do here. Any `RF64` parser which does not accepted `PAD` and/or `JUNK` chunks is faulty (including the ancient version of libsndfile that Audacity uses).

**Comment by CausticYarn** [comment]
Yes, the file definitely seems to be compliant, and I will submit a bug report on Audacity's tracker, hopefully they will be willing to update their version of libsndfile.

I've spent a little more time looking at the specs, and it's not 100% clear to me if the `fact` chunk is necessary when `fmt ` chunk is WAVE_FORMAT_EXTENSIBLE; some documents seem to say that it's only needed for non-PCM data and some say that it's for any format that is not specifically WAV_FORMAT_PCM.  

Since the `fact` chunk is related to the `fmt ` and not whether it's RF64 or not, shouldn't the RF64 also have the `fact` chunk, since it has the WAVE_FORMAT_EXTENSIBLE format?  Currently the `fact` chunk is only added after downgrading.

Also, I am curious if there is a specific reason for choosing WAVE_EX as the format for RF64.  I am in the broadcast world and unfortunately I have at least one vendor with some ancient piece of software where I have to give them WAVE_FORMAT_PCM, and I was wondering if there is any option for selecting the wave format for RF64.

**Comment by erikd** [comment]
> some documents seem to say that it's only needed for non-PCM data

I think thats what the pre version 3.0 spec said. 

>  and some say that it's for any format that is not specifically WAV_FORMAT_PCM.

The version 3.0 spec which I linked above is pretty un-ambiguous about it being required when the format is anything other than ` WAVE_FORMAT_PCM`.

> Since the fact chunk is related to the fmt and not whether it's RF64 or not, shouldn't the RF64 also have the fact chunk

No, because the `ds64` chunk has a sample count field that is 64 bits. The `fact` chunk of a RIFF/WAVE file only has a 32 bit sample count field.

> Also, I am curious if there is a specific reason for choosing WAVE_EX as the format for RF64.

I have no recollection of this. It may well have been arbitrary.

>  I am in the broadcast world and unfortunately I have at least one vendor with some ancient piece of software where I have to give them WAVE_FORMAT_PCM, and I was wondering if there is any option for selecting the wave format for RF64.

Being able to downgrade to `WAVE_FORMAT_PCM` is at this stage very low on my list of priorites. That means you have two options:

* Convert the file using the `sndfile-convert` program.
* Use  `WAVE_FORMAT_PCM` format from the whole chain.
