### ISSUE TITLE
Replace psf_binheader_readf/writef with something type safe.

### ISSUE THREAD

**Issue by erikd** [erikd/libsndfile#241]
I'm sick of fixing variations on the same bug over and over again. Most recently commit 9d470ee5577d3c.

The problem was passing `int64_t` via stdargs where the expected type was `int32_t`. This worked correctly on `x86_64` and `x86` but failed on Arm. I'm not even sure why.

**Comment by erikd** [comment]
It seems there are zero good alternatives to `<stdargs.h>`.

At the moment, the best option seems to be to keep the variable argument list but to check it more throughly with the `binheader_writef_check.py` script or something better. Leaving the code as it is and checking the types is difficult as it needs a full C parser with proper handling of scope, name lookup etc.

However the problem can be made much simpler if all parameters passed to `psf_binheader_writef` were required to be passed via macros that do explicit type casts.

In this scheme, something like:
```
   psf_binheader_writef (psf, "em422", marker, a, b, c) ;
```
would be rewritten as:
```
#define HWM(x) ((uint32_t) (x))
#define HW4(x) ((uint32_t) (x))
#define HW2(x) ((uint16_t) (x))
   psf_binheader_writef (psf, "em422", HWM(marker), HW4(a), HW2(b), HW2(c)) ;
```
In these scheme, all the context required is within the parentheses. Then, all that needs to be checked is that the format character and the specific macro agree.

Would be nice to do this in Python because then its possible to run it in Travis CI, but would be much easier to write and get right in Haskell.

**Comment by evpobr** [comment]
Hm. Is C11 [`_Generic`](http://www.robertgamble.net/2012/01/c11-generic-selections.html) suitable here?

**Comment by erikd** [comment]
`_Generic` may solve part of the problem but not all of it, and I would not like to be tied to C11 compliant compilers or have to work around compilers that are not compliant.
