### ISSUE TITLE
checksum_test fails with VS2017 in debug mode

### ISSUE THREAD

**Issue by evpobr** [erikd/libsndfile#248]

**Comment by evpobr** [comment]
`validate_sfinfo` fails at line:

```c
if (sfinfo->frames < 0)
	return 0 ;
```

The bug is in `gsm610_init`, `sfinfo->frames` is calculalted only if `psf->file.mode` = `SFM_READ`. In debug mode under VS `sfinfo->frames` is uninitialized and contains garbage value < 0.

@erikd, i don't know what it should be, can you fix it?

**Comment by evpobr** [comment]
Yep, setting `psf->file.mode = 0` in `SFM_WRITE` mode helps.

**Comment by erikd** [comment]
> Yep, setting psf->file.mode = 0 in SFM_WRITE mode helps.

"Helps" in this case means "hides the problem".

The only valid values for `psf->file.mode` are `SFM_READ`, `SFM_WRITE` or `SFM_RDWR`.

**Comment by erikd** [comment]
> In debug mode under VS sfinfo->frames is uninitialized and contains garbage value < 0.

Funny thing is, valgrind (a Linux tool that usually picks up stuff like this says this code is clean:
```
> valgrind tests/checksum_test
==4442== Memcheck, a memory error detector
==4442== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==4442== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==4442== Command: tests/checksum_test
==4442== 
    checksum_test                  : checksum.ulaw ........... ok
    checksum_test                  : cksum_ulaw.pcm16 ........ ok
    checksum_test                  : checksum.alaw ........... ok
    checksum_test                  : cksum_alaw.pcm16 ........ ok
    checksum_test                  : checksum.gsm ............ ok
    checksum_test                  : cksum_gsm.pcm16 ......... ok
    checksum_test                  : checksum.vox ............ ok
    checksum_test                  : cksum_vox.pcm16 ......... ok
==4442== 
==4442== HEAP SUMMARY:
==4442==     in use at exit: 0 bytes in 0 blocks
==4442==   total heap usage: 47 allocs, 47 frees, 199,776 bytes allocated
==4442== 
==4442== All heap blocks were freed -- no leaks are possible
==4442== 
==4442== For counts of detected and suppressed errors, rerun with: -v
==4442== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by erikd** [comment]
Nevermind, found it using the Clang's [Memory Sanitizer](https://clang.llvm.org/docs/MemorySanitizer.html). Will have a fix soon.

**Comment by evpobr** [comment]
> "Helps" in this case means "hides the problem".

That's why i asked your help.

**Comment by erikd** [comment]
I was wrong. It happens all the time :).

**Comment by erikd** [comment]
Wow, C is such a completely horrible programming language!

Found a huge bunch of new bugs using Memory Sanitizer. And not just bugs in libsndfile but in FLAC as well.

**Comment by evpobr** [comment]
Bad news.
