### ISSUE TITLE
Msys2 still at version 1.0.26

### ISSUE THREAD

**Issue by bagong** [erikd/libsndfile#251]
msys2 is a pretty nifty mingw build-environment for libraries with a unix background that like to use autotools on Windows. I observed that they are still on libsndfile version 1.0.26. They control builds via a scriptfile PKGBUILD, which for libsndfile is here:

https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-libsndfile

It is actually easy to update to 1.0.28, and as far as I can see the patches they currently use are not required for 1.0.28 (and they don't apply anymore on 1.0.28). I can make a PR to their repo (without patches and updated download) if that is welcome here.

**Comment by erikd** [comment]
I'm totally fine with you fixing Msys2, but I don't see why this should be an issue here.

**Comment by evpobr** [comment]
Of course you can do and thanks for that. Create issue in Msys2 repo.

**Comment by bagong** [comment]
Just asking if its welcome... thanks.

**Comment by erikd** [comment]
@bagong Why would I or @evpobr have any problem with that? Quite the contrary, we are keen to see the products of our labors widely used.  In fact, I encourage you to track down and find projects using old and buggy versions of libsndfile and encourage them to upgrade.

**Comment by bagong** [comment]
Great...
