### ISSUE TITLE
Read 24-bit .wav into 32-bit buffer without changing numeric values

### ISSUE THREAD

**Issue by MGarvinNYC** [erikd/libsndfile#256]
Reading a 24-bit .wav into a 32-bit buffer shifts ints so that the bottom byte is zeros.  IOW, all 24-bit values are multiplied by 256.  Is it possible to avoid this, and keep the exact integer values?  (zero-fill the top byte rather than shifting the 24-bit value)

I noticed a couple options that looked promising, but they did not work as expected.  I've had to divide the values back down, but that seems wasteful.

**Comment by erikd** [comment]
> Is it possible to avoid this

Sorry, its not. libsndfile does what it does.

To get what you want, you have two options

* Use the [sf_read_raw](http://mega-nerd.com/libsndfile/api.html#raw) functionality and unpack the raw data yourself.
* Use `sf_read_int` and modify the data yourself.
