### ISSUE TITLE
Convert stereo to mono?

### ISSUE THREAD

**Issue by Paril** [erikd/libsndfile#260]
Is there any way to implement an automated conversion from stereo to mono during processing? I couldn't find a way in the documentation.

Rationale is that files coming from user input might be stereo, but OpenAL can only spatialize mono sounds, and I'd like to be able to still process these files and use them without having to force the user to fix their sound files for them.

**Comment by erikd** [comment]
> Is there any way to implement an automated conversion from stereo to mono during processing?

Not there is not.

libsndfile is about file I/O and converting between in-memory formats and disk formats.
