### ISSUE TITLE
make_lite.py?

### ISSUE THREAD

**Issue by pmeerw** [erikd/libsndfile#263]
I tried to reduce the footprint of the libsndfile library for an embedded project; is make_lite.py included for this purpose? I unsuccessfully tried to find documentation...

the script fails early trying to extract the tar file, a fix is below, but many files are not found anymore; wondering if it should still be included in the repo...

diff --git a/make_lite.py b/make_lite.py
index eee69fc8..f92a2e3e 100644
--- a/make_lite.py
+++ b/make_lite.py
@@ -194,7 +194,7 @@ def find_configure_version (filename):
                        break
        file.close ()
        # version = re.escape (version)
-       return package, version
+       return package.strip('[]'), version.strip('[]')

**Comment by erikd** [comment]
Yes, that script should be fixed or removed from the respository.
