### ISSUE TITLE
ABI broken by 5c6129fce69d0976b22d15cc695fc1d8521ceae7

### ISSUE THREAD

**Issue by nickalcock** [erikd/libsndfile#268]
This commit stops generating libsndfile.so.1.0 with a symbol version script.

This, unfortunately, constitutes an ABI break: the dynamic linker will cause every shared library and binary linked against a libsndfile predating the change to fail to load with e.g.

/lib/libsndfile.so.1: no version information available (required by /usr/lib/pulseaudio/libpulsecommon-5.0.so)

Please revert or reintroduce a version script some other way (or bump the soname, but doing that without good cause, and this does not seem to me to be good cause, will cause a small army of annoyed packagers to roam the land with murder in their eyes.)

**Comment by erikd** [comment]
Are you building from Git or from release tarball?

**Comment by nickalcock** [comment]
Straight out of git as of a few minutes before I raised this bug.

(The general rule with shared libraries -- as I'm sure you know, but just in case you don't -- is that once you start using a given version you can't stop without breaking everything that uses symbols with that version: so you can't just drop the version script: everything will break.)

**Comment by erikd** [comment]
I am well aware of shared library versioning.

@evpobr Can you please take a look at this?

**Comment by nickalcock** [comment]
Thought so :)

The errant bit of the diff is this hunk:

-               linux*|kfreebsd*-gnu*|gnu*)
-                       SHLIB_VERSION_ARG="-Wl,--version-script=\$(srcdir)/Symbols.gnu-binutils"
-                       ;;

which removes the version script (and indeed the generator that creates it), replacing it with nothing. The commit log says "Use unified visibility control for other platforms", but a better description appears to be "Use no visibility control for other platforms".

**Comment by evpobr** [comment]
Tested now:

On my Ununtu 16.04.2 LTS `libsndfile.so.1.0` is never generated with CMake or Autotools, `libsndfile.so`, `libsndfile.so.1` & `libsndfile.so.1.0.X` only.

BUT it is not generated with v1.0.27 and Autootools with symbol script.

```nm --defined-only -g`` output`:

**Git master with Autotools (no symbol file):**

```
0000000000000000 A libsndfile.so.1.0
0000000000007170 T sf_close
0000000000007d90 T sf_command
0000000000008d00 T sf_current_byterate
00000000000072f0 T sf_error
0000000000007210 T sf_error_number
00000000000073d0 T sf_error_str
0000000000007470 T sf_format_check
000000000000ca40 T sf_get_chunk_data
000000000000c800 T sf_get_chunk_iterator
000000000000c960 T sf_get_chunk_size
0000000000008c40 T sf_get_string
000000000000c8a0 T sf_next_chunk_iterator
000000000000c320 T sf_open
000000000000c3f0 T sf_open_fd
000000000000c4c0 T sf_open_virtual
0000000000007350 T sf_perror
0000000000009c10 T sf_read_double
0000000000009e20 T sf_readf_double
0000000000009a10 T sf_readf_float
0000000000009600 T sf_readf_int
0000000000009800 T sf_read_float
00000000000091f0 T sf_readf_short
00000000000093f0 T sf_read_int
0000000000008e00 T sf_read_raw
0000000000008fe0 T sf_read_short
0000000000007a90 T sf_seek
000000000000c740 T sf_set_chunk
0000000000008c70 T sf_set_string
0000000000007280 T sf_strerror
0000000000007a80 T sf_version_string
000000000000aed0 T sf_write_double
000000000000b100 T sf_writef_double
000000000000acd0 T sf_writef_float
000000000000a8a0 T sf_writef_int
000000000000aaa0 T sf_write_float
000000000000a470 T sf_writef_short
000000000000a670 T sf_write_int
000000000000a020 T sf_write_raw
000000000000a240 T sf_write_short
00000000000071f0 T sf_write_sync
```

**Git master with CMake  (no symbol file):**

```
000000000029ec3e B __bss_start
000000000029ec3e D _edata
00000000002a1260 B _end
0000000000080990 T _fini
0000000000006050 T _init
000000000002d40e T sf_close
000000000002e45b T sf_command
0000000000030004 T sf_current_byterate
000000000002d62a T sf_error
000000000002d4dc T sf_error_number
000000000002d7c1 T sf_error_str
000000000002d8b7 T sf_format_check
0000000000035249 T sf_get_chunk_data
0000000000034fa5 T sf_get_chunk_iterator
0000000000035152 T sf_get_chunk_size
000000000002ff00 T sf_get_string
000000000003506e T sf_next_chunk_iterator
000000000002cf7d T sf_open
000000000002d075 T sf_open_fd
000000000002d16d T sf_open_virtual
000000000002d6e5 T sf_perror
0000000000031692 T sf_read_double
0000000000031996 T sf_readf_double
0000000000031387 T sf_readf_float
0000000000030d78 T sf_readf_int
0000000000031083 T sf_read_float
000000000003076f T sf_readf_short
0000000000030a74 T sf_read_int
00000000000301b8 T sf_read_raw
0000000000030471 T sf_read_short
000000000002fb03 T sf_seek
0000000000034eb9 T sf_set_chunk
000000000002ff50 T sf_set_string
000000000002d590 T sf_strerror
000000000002e44e T sf_version_string
00000000000330d8 T sf_write_double
00000000000333c7 T sf_writef_double
0000000000032dff T sf_writef_float
0000000000032837 T sf_writef_int
0000000000032b10 T sf_write_float
000000000003226f T sf_writef_short
0000000000032548 T sf_write_int
0000000000031ca1 T sf_write_raw
0000000000031f80 T sf_write_short
000000000002d4af T sf_write_sync
```

**v1.0.27 with Automake  (no symbol file):**

```
0000000000000000 A libsndfile.so.1.0
00000000000070e0 T sf_close
0000000000007d30 T sf_command
0000000000008cb0 T sf_current_byterate
0000000000007270 T sf_error
0000000000007180 T sf_error_number
0000000000007370 T sf_error_str
0000000000007410 T sf_format_check
000000000000c8d0 T sf_get_chunk_data
000000000000c690 T sf_get_chunk_iterator
000000000000c7f0 T sf_get_chunk_size
0000000000008bf0 T sf_get_string
000000000000c730 T sf_next_chunk_iterator
000000000000c190 T sf_open
000000000000c260 T sf_open_fd
000000000000c340 T sf_open_virtual
00000000000072e0 T sf_perror
0000000000009be0 T sf_read_double
0000000000009df0 T sf_readf_double
00000000000099e0 T sf_readf_float
00000000000095d0 T sf_readf_int
00000000000097d0 T sf_read_float
00000000000091c0 T sf_readf_short
00000000000093c0 T sf_read_int
0000000000008db0 T sf_read_raw
0000000000008fb0 T sf_read_short
0000000000007a30 T sf_seek
000000000000c5d0 T sf_set_chunk
0000000000008c20 T sf_set_string
00000000000071f0 T sf_strerror
0000000000007a20 T sf_version_string
000000000000ad90 T sf_write_double
000000000000afa0 T sf_writef_double
000000000000abc0 T sf_writef_float
000000000000a7e0 T sf_writef_int
000000000000a9b0 T sf_write_float
000000000000a400 T sf_writef_short
000000000000a5d0 T sf_write_int
0000000000009ff0 T sf_write_raw
000000000000a1f0 T sf_write_short
0000000000007160 T sf_write_sync
```

So new [visibility control](https://gcc.gnu.org/wiki/Visibility) works, @nickalcock, only public function are exported. I see real difference with CMake, no ```A libsndfile.so.1.0``` and it is subject to check. But you use Autotools, right?

**Comment by erikd** [comment]
@nickalcock It might help if you provide the steps required to reproduce the problem you are seeing.

**Comment by nickalcock** [comment]
Version definitions are not shown by nm: they are not properties of individual symbols but of the library as a whole. Try running "eu-readelf -V" on the library. With the old library, you will see (in part):

Version definition section [ 6] '.gnu.version_d' contains 2 entries:
 Addr: 0x00000000000021b0  Offset: 0x0021b0  Link to section: [ 4] '.dynstr'
  000000: Version: 1  Flags: BASE   Index: 1  Cnt: 1  Name: libsndfile.so.1
  0x001c: Version: 1  Flags: none  Index: 2  Cnt: 1  Name: libsndfile.so.1.0

In the new library, this is gone, breaking anything that contains a version needs section naming libsndfile.so.1.0.

**Comment by evpobr** [comment]
I don't see it with master (sorry for russian output):

```
Раздел описания версии '.gnu.version_d' содержит 2 элементов:
  Адрес: 0x0000000000002170  Offset: 0x002170  Link: 4 (.dynstr)  000000: Ревизия: 1  Флаги: BASE   Индекс: 1  Счетчик: 1  Имя: libsndfile.so.1
  0x001c: Ревизия: 1  Флаги: нет  Индекс: 2  Счетчик: 1  Имя: libsndfile.so.1.0
  Версия definition past end раздела
```

**Comment by nickalcock** [comment]
Well I don't understand why not. Do you see your linker passing in a version script or not? If not, how can you explain a version definition section appearing? If it is... where's it coming from? You removed the only code which passes in a version script in the commit I cite, and added nothing to replace it (except if it's something you forgot to push, I suppose). When I build with your commit in place, the -Wl,--version-script is gone, so there is no version definition section.

**Comment by evpobr** [comment]
In `configure.ac`:

```
VERSION_MAJOR=`echo $PACKAGE_VERSION | $SED "s/\..*//"`
VERSION_MINOR=`echo $CLEAN_VERSION | $SED "s/.*\.//"`

SHARED_VERSION_INFO="$VERSION_MAJOR:$VERSION_MINOR:0"
```

In `src/Makefile.am`:

```
libsndfile_la_LDFLAGS = -no-undefined -version-info  $(SHARED_VERSION_INFO) $(SHLIB_VERSION_ARG)
```

**Comment by erikd** [comment]
@evpobr It seems that the old way of doing shared library versioning with the version script had features that the new version does not.

**Comment by nickalcock** [comment]
evpobr: --version-info sets the SONAME (DT_SONAME tag, set via -Wl,-soname). This is *not* the same as the version definition section (.gnu.version_d, set via a linker script passed in via -Wl,--version-script). You cannot replace one with the other. Dropping a linker script and leaving only an SONAME the same as it was before will produce a broken system with libraries that claim to link with the library in question but that fail at startup, as above.

(Ulrich Drepper's DSO howto at https://software.intel.com/sites/default/files/m/a/1/e/dsohowto.pdf is worth a read for more on this subject and many others than I can possibly put in this comment. :) )

**Comment by evpobr** [comment]
@nickalcock , thanks for link. But i wonder why i see the same `gnu.version_d` section with Git master. I will make clean build and check again. 

And you please provide more info: command file with all the flags, and `readelf -V` output with Git master code.

**Comment by evpobr** [comment]
@erikd, just compiled clean Git master and output is different, no `gnu.version_d` in `eu-readelf` output. I think ABI is broken.

It is about first line in `Symbols.gnu-binutils`. If you omit it, version script only defines global and local functions. But if you add it, that version tag will be added to each function. We have `libsndfile.so.1.0` version tag, but is could be `VERS_1`, `ABI_01`, whatever you want. But it should be the same for every library release for this functions set.

This feature is not mandatory, but we cannot remove it without breaking ABI.

I didn't know about it. I thought `SONAME` is the thing to care about.

**Comment by erikd** [comment]
SONAME is the main, but not only thing to care about.

I think the only solution is to revert the commit as suggested.

**Comment by evpobr** [comment]
Agreed. We need to create branch to fix it both for Autotools and CMake builds.

**Comment by evpobr** [comment]
@erikd, i will fix it (`with create_symbols_file.py`). One note - do we still support OS/2? Last version was released in 2001.

**Comment by evpobr** [comment]
Nevermind, i will restore all back. CMake part is done, branch [`bugfix/symbols`](https://github.com/erikd/libsndfile/tree/bugfix/symbols).

**Comment by evpobr** [comment]
I think it is done now. @erikd, @nickalcock , check that branch please.

**Comment by erikd** [comment]
Looks about right. When others have had their say, submit a PR and let Travis build it.

**Comment by evpobr** [comment]
> When others have had their say, submit a PR and let Travis build it.

The branch [passes tests](https://travis-ci.org/erikd/libsndfile/builds/235654418).

Do we need PR here? It is branch in your repo. You can edit and merge it without PR.

Waiting for @nickalcock's response.

**Comment by nickalcock** [comment]
Looks good to me, the version defs are back :)
