### ISSUE TITLE
Is it possible to read non-RAW audio data with no header?

### ISSUE THREAD

**Issue by tgarc** [erikd/libsndfile#270]
I'd like to read audio files (ogg) that have no header. The channels/sample rate/format are known but I don't know of any way to pass these onto libsndfile while telling it to ignore the header. Is this even possible?

FWIW, in my application I have a file-like object (a socket) that is getting data over the network; hence the need to decode audio data without a header.

**Comment by erikd** [comment]
For your purposes, using libogg and libvorbis directly is a better bet.

**Comment by tgarc** [comment]
No doubt. The thing is though, is that I'm using python bindings (PySoundFile) and I'd like to avoid depending on any additional libraries. If there's a way I can hack it, it would be quite useful for me.

**Comment by erikd** [comment]
libnsdfile is not capable of what you want. It would be considerable effort to make it do what you want.

I'd be happy to accept a clean patch to add this capability, if you want to implement it.

**Comment by tgarc** [comment]
Okay, that's what I expected. It would be a nice feature because libsndfile
already provides a unified interface for all these decoder libraries. Plus
the only other solid seeming python libraries for decoding audio are either
built into a library with a bunch of other dependencies, or depend on
ffmpeg. I may look into adding this sometime in the future but it would
probably take quite a bit of effort to get it up to snuff with the rest of
your code :) Thanks.
