### ISSUE TITLE
sf_open_fd sometimes leaves filehandle open, even if `close_desc` is TRUE

### ISSUE THREAD

**Issue by umlaeute** [erikd/libsndfile#278]
(This was originally reported as a sub-issue in https://bugs.debian.org/#761307)

`sf_open_fd` returns in two cases with an error without closing fd  when `close_desc` is TRUE, whereas most other cases go though `psf_open_file` which does close it.

This means a user can't know if they need to close fd on their own on error.

**Comment by evpobr** [comment]
@umlaeute , can you look at this #566 ?

**Comment by umlaeute** [comment]
it appears that #566 fixes the problem reported here.

otoh, i'm not entirely sure whether the filehandle should be closed *at all* if the `sf_open_fd()` call fails.

i think that the behaviour should be consistent: if NULL is returned that the filehandle should either always be kept open, or always be closed:

if the former, how about this?:

~~~diff
--- a/src/sndfile.c
+++ b/src/sndfile.c
@@ -354,7 +354,7 @@ sf_open     (const char *path, int mode, SF_INFO *sfinfo)
 SNDFILE*
 sf_open_fd     (int fd, int mode, SF_INFO *sfinfo, int close_desc)
 {      SF_PRIVATE      *psf ;
+       SNDFILE  *result ;

        if ((SF_CONTAINER (sfinfo->format)) == SF_FORMAT_SD2)
        {       sf_errno = SFE_SD2_FD_DISALLOWED ;
                return  NULL ;
@@ -373,10 +373,12 @@ sf_open_fd        (int fd, int mode, SF_INFO *sfinfo, int close_desc)
        psf->is_pipe = psf_is_pipe (psf) ;
        psf->fileoffset = psf_ftell (psf) ;
 
-       if (! close_desc)
+       result = psf_open_file (psf, sfinfo) ;
+
+       if (result != NULL && ! close_desc)
                psf->file.do_not_close_descriptor = SF_TRUE ;
 
-       return psf_open_file (psf, sfinfo) ;
+       return result;
 } /* sf_open_fd */
 
 SNDFILE*
~~~

(i'm not the original reporter of the problem; rather i forwarded the issue from the Debian bug-tracker, without doing a full assessment of the validity of the bug-report - assuming that some libsndfile people would do so ;-)).

probably @erikd could comment on this issue.

**Comment by evpobr** [comment]
Thanks, added commit.

**Comment by umlaeute** [comment]
sorry, this was really meant to start a discussion rather than changing your PR.

**Comment by evpobr** [comment]
Ok, let's wait @erikd
