### ISSUE TITLE
Support for Ircam 24 bits

### ISSUE THREAD

**Issue by severino65** [erikd/libsndfile#283]
Hello.

Inside the chart of supported formats of the libsndfile documentation, the IRCAM 24 bits appears to be marked as R/W: looking into the source code of the ircam.c file, this doesn't seem to be the case: is this an error of the documentation or a lack of coverage of the 24 bits encoding inside the code for this specific format?

Thanks in advance and Kind regards

Severino

**Comment by erikd** [comment]
This is a documentation bug. As far as I am aware, the IRCAM file format specified a way to encode 24 bit samples.
