### ISSUE TITLE
Test failures on ARM

### ISSUE THREAD

**Issue by SoapGentoo** [erikd/libsndfile#287]
Hi @erikd 
For the different archs on Gentoo, when running the test suite on ARM, we get failures:
https://bugs.gentoo.org/show_bug.cgi?id=618452

```
    string_start_end_test          : strings.rf64 ............ ok
    string_multi_set_test          : multi.rf64 .............. 

Line 520: sf_open (SFM_READ) failed : Error in RF64 file. No 'data' chunk marker.
```

Could you maybe have a look? Thanks

**Comment by erikd** [comment]
Is that the release? Pretty sure this is fixed in HEAD.

**Comment by SoapGentoo** [comment]
That's 1.0.28, the full release, yes. Ok so if fixed, we wait for the next release?

**Comment by erikd** [comment]
Either wait for the next release or backport 9d470ee5577d3ccedb .

**Comment by SoapGentoo** [comment]
Thanks, backported...
