### ISSUE TITLE
Windows msvc cmake pkg-config: tiny bug in libname generation

### ISSUE THREAD

**Issue by bagong** [erikd/libsndfile#289]
Hi,

the sndfile.pc generated in the msvc/cmake build gives sndfile as name for the library, while the real name is libsndfile-1. This causes pkg-config lookups to produce wrong data and linking to fail. Admittedly using pkg-config in msvc builds is not exactly common, but I managed to bump into a case, trying to build aubio. Aubio uses the waf buildsystem and depends on pkg-config to detect libsndfile.

As we are at it: the build option `ENABLE_PACKAGE_CONFIG` seems to have no effect. My understanding is that it controls if the sndfile.pc file is generated or not (I might misunderstand though). Fortunately the file is always generated, so no prob ;)

**Comment by evpobr** [comment]
> the sndfile.pc generated in the msvc/cmake build gives sndfile as name for the library, while the real name is libsndfile-1.

The name itself is correct, it must be `sndfile`. `PkgConfig` knows how to handle that, but it is designed for Unix systems, it is almost never used under Windows without `MSYS` or` Cygwin`. I think we must disable `sndfile.pc` generation for MSVC.

> As we are at it: the build option `ENABLE_PACKAGE_CONFIG` seems to have no effect. My understanding is that it controls if the sndfile.pc file is generated or not (I might misunderstand though). Fortunately the file is always generated, so no prob ;)

No, it is about [package configuration files](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#package-configuration-file). It is very close to PkgConfig's pc files, but for CMake.

> Aubio uses the waf buildsystem and depends on pkg-config to detect libsndfile.

I'm pretty sure you must use `waf` and `MSYS/MinGW` toolchain under Windows (look at `aubio/scripts/build_mingw`).

**Comment by bagong** [comment]
>> the sndfile.pc generated in the msvc/cmake build gives sndfile as name for the library, while the real name is libsndfile-1.

> The name itself is correct, it must be sndfile. PkgConfig knows how to handle that, but it is designed for Unix systems, it is almost never used under Windows without MSYS orCygwin. I think we must disable sndfile.pc generation for MSVC.

Please don't. Currently I just patch the library name. If you disable it I will have to patch the system to reenable it. Make it an option... ;) See below my comment on "pkgconfig does not know how to handle that in an msvc environment)

> No, it is about package configuration files. It is very close to PkgConfig's pc files, but for CMake.

Ah, good to know. I've come across those but haven't quite activated them in my mindset ;)

>> Aubio uses the waf buildsystem and depends on pkg-config to detect libsndfile.

> I'm pretty sure you must use waf and MSYS/MinGW toolchain under Windows (look at aubio/scripts/build_mingw).

In this case you are wrong ;) Waf supports msvc, it even has an option to generate msbuild/VS project files. But it is possible that projects don't make "proper" use of it. And yet "proper" is also defined by what people do in the field.

As to pkg-config in a native windows/non mingw environment: the fact that it does not derive a prefix - root - postfix library name from the root can be interpreted in two ways: a) that Windows or pkg-config on Windows have a deficiency or b) that the *import*-library name in a windows-native/msvc environment should *not* use prefix and postfix. I've raised that issue a few months back here when the cmake system was developped, saying that the name generation in the msvc build should not use mingw-logic (but Erik just answered "libsndfile-1" was correct). I think the "proper" way in msvc would be 

a ) to keep the root as import library name
b) add a postfix to static library, or (in my view better) output the static library to a separate folder
c) make the corresponding entries in the sndfile.pc

The actual .dll can carry version information in the filename, important is just that the import library addresses it correctly. You could even distinguish debug-libraries somehow, if you wanted, but no obligation, at least vcpkg can handle that by itself.

I think libsndfile in a public msvc-environment is so new that one could still adjust to these Windows native conventions. This would allow msvc users to work the way they are used to, and pkg-config to work on Windows native.

Thanks for your consideration.

**Comment by bagong** [comment]
Bumped into another small one, the output-name of the static library is missing the "-1" for Windows:

    set_target_properties (${SNDFILE_STATIC_TARGET} PROPERTIES OUTPUT_NAME "sndfile)

should be

    set_target_properties (${SNDFILE_STATIC_TARGET} PROPERTIES OUTPUT_NAME "sndfile-${PROJECT_VERSION_MAJOR}")

Of course this is only relevant if you really want to stick to unix/mingw naming convention in msvc builds as well. I do think that is unfortunate, though...

Also the REQUIRES field is not filled in (it should contain ogg, flac, vorbis, vorbisenc) - otherwise static builds with libsndfile as dependency will fail

Also I think it would be more robust to fill in all dependent libs in Libs.private, i.e. ogg, flac, vorbis, vorbisenc, and not depend on flac and vorbisenc to have proper pkgconfig files.

Thanks for your consideration.

PS: I am aware that these trivial issues are a PITA. In my defence I can only say that builds failing because of mistakes in the files and naming are a PITA as well ;)

PPS: if you decide adjusting to standard naming convention for msvc, please don't forget that the cmake config files currently also contain the fully pre- and postfixed names.

**Comment by evpobr** [comment]
> In this case you are wrong ;) Waf supports msvc, it even has an option to generate msbuild/VS project files. But it is possible that projects don't make "proper" use of it. And yet "proper" is also defined by what people do in the field.

Ok, it supports MSVC, i knows. But does it support MSVC + pkg-config?

I still think it is `Aubio` bug, to try to use `pkg-config` in MSVC builds. You don't try to Autotools with MSVC compiler, right? Some tools cannot be used in Windows environment, and then you use MinGW or Cygwin. See here for [example](https://stackoverflow.com/questions/10810279/finding-libraries-using-pkg-config-in-windows).

>  I've raised that issue a few months back here when the cmake system was developped, saying that the name generation in the msvc build should not use mingw-logic (but Erik just answered "libsndfile-1" was correct).

> I think libsndfile in a public msvc-environment is so new that one could still adjust to these Windows native conventions. This would allow msvc users to work the way they are used to, and pkg-config to work on Windows native.

There are no native library naming conventions for Windows at all. Library name can be `libsndfile.dll`, or `sndfile.dll` or `libsndfile-1.dll`. CMake under MinGW produces `libsndfile.dll`. Which one is correct? Hell knows. I vote for `libsndfile.dll`, but `libsndfile-1.dll` is widly used, so we use it for now everywhere. Compatibility, you know. @erikd is very serious about it.

> Bumped into another thing: the REQUIRES field is not filled in (it should contain ogg, flac, vorbis, vorbisenc) - otherwise static builds with libsndfile as dependency will fail

I follow the same rules as Autotools build does. It doesn't fill `REQUIRES` section. Probably it should.

> Also I think it would be more robust to fill in all dependent libs in Libs.private, i.e. ogg, flac, vorbis, vorbisenc, and not depend on flac and vorbisenc to have proper pkgconfig files.

They aren't?

sndfile.pc.cmake.in:

```
Libs.private: @PC_PRIVATE_LIBS@
```

CMakeLists.txt:

```cmake
if (EXTERNAL_XIPH_LIBS)
	set (PC_PRIVATE_LIBS "-lFLAC  -lvorbisenc")
endif ()
```

If you don't see them in your pc-file then CMake didn't found them.

**Comment by bagong** [comment]
> Ok, it supports MSVC, i knows. But does it support MSVC + pkg-config?

Well, it works if the pkgconfig.pc's are correct. I guess that can be called support ;)

if (EXTERNAL_XIPH_LIBS)
	set (PC_PRIVATE_LIBS "-lFLAC  -lvorbisenc")
endif ()

I was referring to missing is ogg and vorbis ;)

Let's not get into a feud about naming conventions. Look at vcpkg and you will see that 90% of library names are without pre- and suffix (e.g. ogg, vorbis, flac). The ones that don't, do it because they carry a mingw-logic into a msvc context where this whole lib-xxx-number thingy is simply not known, it's a total unix thing. The only thing on msvc is a version string suffix in the *dll* - not the implib!. The fact that implib and static lib have the same name is considered a feature in msvc logic ;). It allows to seemlessly switch between linking dynamically and statically. Btw., the fact that pkg-config doesn not expand the library name root with a pre- and suffix shows what the convention on native Windows is. 

But never mind, I'll propose a patch on vcpkg to generate working pkg-config-libname generation with your filenames in the vcpkg port, I already have it locally.

**Comment by evpobr** [comment]
@erikd , can we use `libsndfile.dll` or `sndfile.dll` name under Windows with MSVC? It is native for VC compiler. `libsndfile-1.dll` is MinGW specific. And CygWin produces `cygsndfile-1.dll` DLL name even with Autotools. CMake developers told we they never planned to add library version suffix for DLLs.

**Comment by erikd** [comment]
As long as MSVC does something vaguely sensible I'm not too concerned (especially since I personally do not support MSVC).

**Comment by bagong** [comment]
@evpobr , the name of the dll isn't really all that important. It's the import- and static lib that should both be called sndfile.lib if you want to be totally conformant.

**Comment by evpobr** [comment]
@bagong :

To make it clear:

- DLL: `sndfile.dll`
- Import library: `sndfile.lib`
- Static library: `sndfile.lib`

That's what you want?

We cannot use `sndfile.lib` for static library - CMake puts all the LIBs in one directory, and one of the libs will overwrite another one.

We have all that problems because we want both static and shared builds at once. The real CMake's way is the only target `sndfile`, static by default, and `BUILD_SHARED_LIBS` to build DLL. And yes, output names with VC are exactly as you said before - `sndfile`.

**Comment by bagong** [comment]
I feel a bit pedantic here, sorry, but as you ask ;). I said the dll-name isn't that important because it's the import-lib that finds the dll, so if the import lib contains the correct dll name, any name is fine. For dll's I quite commonly see a version-suffix, e.g. icuid59.dll. In that case the impor-lib will still be called icuid.lib and thus be properly found by cmake, pkg-config etc with the default root-name icuid. Adding a version suffix to the dll gives some transparency, but it's not required.

As to import- vs static-lib name: In totally conformant msvc builds you will only have either dynamic- + import-libs, or a single static lib, so a name-clash is not possible. 

In fact it is quite common to rename the static lib because many packages are created in the "all in one folder"-unix-logic, but in an msvc environment that is considered not ideal. As I said above, the name identity is considered a feature in msvc logic :smile:. There are two more alternatives to handle this: a) create a separate output folder for the static lib for msvc-builds b) name the static target different from the import lib *only* if both static and dynamic libraries are both built in the same build, *and* do not build both static and dynamic by default, when building with msvc. I can see that this could be considered overly complicated, but really it is only so because a unix-logic/tradition is applied to Windows. But never mind, a non-conformant behaviour could easily/with minimum invasion be overridden in the vcpkg build.

**Comment by evpobr** [comment]
@bagong, soon i will make PR to fix this problem. Some highlights:

1. DLL name under WIN32 is still `libsndfile-1.dll` for compatibility reasons
2. Export & static library names are CMake's defaults on all platforms, for Windows it is `sndfile.lib`.
3. `pkg-config` must work now
4. `BUILD_STATIC_LIBS` does nothing now, use `BUILD_SHARED_LIBS` to configure static\shared build

To avoid name clashes i removed separate `sndfile-static` and `sndfile-shared` targets, it is the only `sndfile` target now. It was not good idea anyway:

1. Possible name collisions (we fixed that under Windows, but it is possible to get it on other platforms), so CMake devs recommend it
2. It was slow
3. Overcompicated CMake script
4. No real world scenario when this behaviour is required
