### ISSUE TITLE
Random artificial crackles when giving floating point samples to libsndfile to write into a 24bit flac file

### ISSUE THREAD

**Issue by parcolee** [erikd/libsndfile#294]
We are experiencing some random artificial crackles which destroying waveform in random places when we give floating point samples to libsndfile to write into a 24bit flac file, but we never experience the same crackle situation when we give FP samples to libsndfile to write into a 24bit wav file…. 

What’s wrong inside the libsndfile? 

And the crackles only appear when there are some clippings in the source audio, but crackles never appear when I encode the same clipping wav source by the official libflac encoder from xiph.org…… 

The complete detail of this bug is inside this thread here of Cakewalk forum: 
http://forum.cakewalk.com/A-serious-bug-from-FLAC-encoder-of-SONAR-Platinum-when-dithering-out-24bit-audio-output-m3607265.aspx

**Comment by erikd** [comment]
The crackles will happen when writing floating point samples to an integer format if any of your samples out less than `-1.0` or greater than `+1.0`.

It is your responsibility to make sure no samples are outside that range.

**Comment by parcolee** [comment]
And so how should I give 24bit pcm samples to libsndfile to write into wav or flac files? with what value types? int or float? and how should I do to ensure 24bit samples are written inside the audio files correctly?

**Comment by parcolee** [comment]
this is the waveform I converted to 24bit wav file by libsndfile and encoded with official flac.exe
https://7qipda-dm2306.files.1drv.com/y4peG-Z1c6zRx9d_c5eHGq7A0klelxljKuIZ4g7UX6VznZfUjWHV7x6s8Qe6SzO_WiICjXbETpgYTU9Ud7b5p6EiNt94C9XkTdzg5K6Ex0OWsWuvcUrJW6t7hxs0LZ99YYokTQkLQ63aM6Xa7FeNO3clqkcMxh6jLrcyyUMTh_DTBcK7PvvqwjlhiIVR_bUKIKi528SQ6vZyH25g6PJAlfZkw/flac_1_3_2_24.jpg?psid=1


And this is the waveform I converted to 24bit flac file with libsndfile from floating point samples, and I don't think those crackles are clippings..........
https://7qipda-dm2306.files.1drv.com/y4p0tOPf8AJ-63IqK22slzp0wAR3hQn5qnNNMvOvhDfslUlVNrVHOCc5SnD4xTQ9ib3wPzNZrqanuXe7XGulfWnF0ls_9wCCS7L9adH_o9ehcxEL9La6zgZC0UekeRZf4LRJwgTzvlHLoNfxpbhoiuLB7saXxSTHJ0Qp01l_FB4DurffwB-uElGnHic-oJSwWl3MCx9fYW4UoFXTuEIAoWy2w/sonar_flac_24_crackles.jpg?psid=1

**Comment by erikd** [comment]
The second image is a perfect example of what happens when you encode floating point samples outside the range `[-1.0, 1.0]` to an integer format.

> And so how should I give 24bit pcm samples to libsndfile to write into wav or flac files?

That depends. How are you doing it now?

**Comment by parcolee** [comment]
> The second image is a perfect example of what happens when you encode floating point samples outside the range [-1.0, 1.0] to an integer format.

So should I add a level filter for every pcm sample, something like:
`if (sample > 1) then { sample = 1 }`
or?
`if (sample >= 1) then { sample = 0.99999999...... }`


> That depends. How are you doing it now?

Just sending 24bit samples with float type, so any correct types should I use and what should I do to keep all values of every 24bit pcm sample exactly unchanged and write into pcm files [24bit sample][24bit sample][24bit sample][24bit sample][24bit sample][24bit sample][24bit sample]....... correctly?

**Comment by erikd** [comment]
> So should I add a level filter for every pcm sample, something like:
> `if (sample > 1) then { sample = 1 }`
> or?
> `if (sample >= 1) then { sample = 0.99999999...... }`

If you are willing to accept clipping then yes, that would work, as would using [`SFC_SET_CLIPPING`](http://www.mega-nerd.com/libsndfile/command.html#SFC_SET_CLIPPING).

A much better solution is to find out the maximum absolute value of your signal from start to finish and if it is greater than `1.0`, then divide all sample values by that absolute maximum value (its called normalisation). If you wish to this in real time, then a combination of using a limiter and the clipping solution above is best.

> Just sending 24bit samples with float type, so any correct types should I use and what should I do to keep all values of every 24bit pcm sample exactly unchange

As far as I am concerned that is a fools errand, but [this note](http://www.mega-nerd.com/libsndfile/api.html#note1) hints at the solution.

**Comment by parcolee** [comment]
So how does libsndfile officially expect us to write a 24bit file? with?  And what steps we should do?

**Comment by erikd** [comment]
I gave my advice in my last response.

The time delta between my response and yours was 14 minutes. That is not sufficient time for you to read the two parts of the documentation I linked and write yourself a test program to see if your understanding of that documentation is correct.

**Comment by parcolee** [comment]
So and, does libsndfile apply any internal dithering while giving 64bit or 32bit samples to libsndfile and require libsndfile to write 24bit files? or only truncation will be done?

**Comment by erikd** [comment]
Truncation only.

Dithering on 24 bit files is completely useless as 24 bit audio has 144dB of dynamic range between maximum signal and minimum non-zero values. The human ear has a dynamic range orf hearing of about 130dB.

**Comment by parcolee** [comment]
And last question, so all I have to do is just adding 8 zeros on the right hand side (the 8 least significant bits) of the 24bit number and store as a int variable for sending to libsndfile?
And libsndfile is going to auto truncate those 8 zeros on the right hand side (the 8 least significant bits) away when writing into a 24bit audio files?

**Comment by erikd** [comment]
Yes.

**Comment by parcolee** [comment]
Thank you for your helpful explanation!

I think the technical staffs of Cakewalk should have a look on this thread here..........

**Comment by erikd** [comment]
Can I close this?

**Comment by parcolee** [comment]
Just give them at least a week of time to read this first.

**Comment by erikd** [comment]
Closing.
