### ISSUE TITLE
Build for Android

### ISSUE THREAD

**Issue by RuolunWeng** [erikd/libsndfile#295]
Hello all,

one question for compilation for Android, anyone has succeed?
I try to follow the instruction: 
<
export ANDROID_TOOLCHAIN_HOME=/path/to/android/toolchain
./Scripts/android-configure.sh
make
>

BUT I got error:

/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       libsndfile_la-sndfile.lo
In file included from sndfile.c:26:0:
sndfile.h:340:10: warning: type defaults to 'int' in declaration of 'sf_count_t'
 typedef  sf_count_t ;
          ^
sndfile.c: In function 'psf_open_file':
sndfile.c:2968:34: error: expected expression before ';' token
   psf->filelength = SF_COUNT_MAX ;
                                  ^
sndfile.c:3001:37: error: expected expression before ')' token
  if (psf->filelength == SF_COUNT_MAX)
                                     ^
make[2]: *** [libsndfile_la-sndfile.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

Thank you for your response!!

Best
Allen

**Comment by erikd** [comment]
Please post the output of the `./Scripts/android-configure.sh` command.

**Comment by RuolunWeng** [comment]
ok, here it is

**Comment by erikd** [comment]
No it isn't. Just attaching it to an email is not going to work.

**Comment by RuolunWeng** [comment]
oh sorry, so how can I post?

**Comment by erikd** [comment]
Its not possible to do it via email. You have to do it on the github website in the browser.

**Comment by RuolunWeng** [comment]
[Résultat de Terminal.zip](https://github.com/erikd/libsndfile/files/1080185/Resultat.de.Terminal.zip)

Voila

**Comment by erikd** [comment]
Can you *paste* the output of `V=1 make` ?

**Comment by RuolunWeng** [comment]
like this?

MBPdeWengAllen:libsndfile-1.0.28 Weng_Allen$ V=1 make
Making all in M4
make[1]: Nothing to be done for `all'.
Making all in Win32
make[1]: Nothing to be done for `all'.
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
/bin/sh ../libtool  --tag=CC   --mode=compile /opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -DSNDFILE_EXPORTS -gstabs --sysroot=/opt/android/ndk/platforms/android-23/arch-arm -I/opt/android/ndk/platforms/android-23/arch-arm/usr/include -I/opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/include -D_FORTIFY_SOURCE=2 -fvisibility=hidden -gstabs --sysroot=/opt/android/ndk/platforms/android-23/arch-arm -I/opt/android/ndk/platforms/android-23/arch-arm/usr/include -I/opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/include -std=gnu99 -Wall -Wextra -Wdeclaration-after-statement -Wpointer-arith     -Wcast-align -Wcast-qual -Wshadow -Wwrite-strings -Wundef -Wuninitialized -Winit-self -Wbad-function-cast -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Waggregate-return -Wvla -pipe  -MT libsndfile_la-sndfile.lo -MD -MP -MF .deps/libsndfile_la-sndfile.Tpo -c -o libsndfile_la-sndfile.lo `test -f 'sndfile.c' || echo './'`sndfile.c
libtool: compile:  /opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc -std=gnu99 -DHAVE_CONFIG_H -I. -DSNDFILE_EXPORTS -gstabs --sysroot=/opt/android/ndk/platforms/android-23/arch-arm -I/opt/android/ndk/platforms/android-23/arch-arm/usr/include -I/opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/include -D_FORTIFY_SOURCE=2 -fvisibility=hidden -gstabs --sysroot=/opt/android/ndk/platforms/android-23/arch-arm -I/opt/android/ndk/platforms/android-23/arch-arm/usr/include -I/opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/include -std=gnu99 -Wall -Wextra -Wdeclaration-after-statement -Wpointer-arith -Wcast-align -Wcast-qual -Wshadow -Wwrite-strings -Wundef -Wuninitialized -Winit-self -Wbad-function-cast -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Waggregate-return -Wvla -pipe -MT libsndfile_la-sndfile.lo -MD -MP -MF .deps/libsndfile_la-sndfile.Tpo -c sndfile.c  -fPIC -DPIC -o .libs/libsndfile_la-sndfile.o
In file included from sndfile.c:26:0:
sndfile.h:340:10: warning: type defaults to 'int' in declaration of 'sf_count_t'
 typedef  sf_count_t ;
          ^
sndfile.c: In function 'psf_open_file':
sndfile.c:2968:34: error: expected expression before ';' token
   psf->filelength = SF_COUNT_MAX ;
                                  ^
sndfile.c:3001:37: error: expected expression before ')' token
  if (psf->filelength == SF_COUNT_MAX)
                                     ^
make[2]: *** [libsndfile_la-sndfile.lo] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
MBPdeWengAllen:libsndfile-1.0.28 Weng_Allen$

**Comment by erikd** [comment]
And the generated file `src/config.h`?

**Comment by RuolunWeng** [comment]
[config.h.zip](https://github.com/erikd/libsndfile/files/1080261/config.h.zip)

**Comment by grosalex** [comment]
Hi, I'm having the same issu did you find a way out?

Regards,

**Comment by erikd** [comment]
There are at least two problems with the provided `config.h` file:
```
/* Set to maximum allowed value of sf_count_t type. */
#define SF_COUNT_MAX 
```
and
``/* Set to long if unknown. */
#define TYPEOF_SF_COUNT_T 
```
`

**Comment by RuolunWeng** [comment]
ok…. so?  What we can do?

**Comment by RuolunWeng** [comment]
haha, of cause,  we are here to answer, test and provide the things you want.

Thanks

**Comment by erikd** [comment]
Well, if you would like my help, you need to provide answers to the questions I ask, because I *cannot* help without those answers.

**Comment by erikd** [comment]
The reason you didn't see my question is probably because you are do this on a mobile phone or via email. If you use use a web browser, I'm prettty sure you will find my question.

**Comment by RuolunWeng** [comment]
ok, i am using the browser now, you mean the question is you want me to post the code of config.h instead of .zip?


/* src/config.h.  Generated from config.h.in by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* Set to 1 if the compile is GNU GCC. */
#define COMPILER_IS_GCC 1

/* Target processor clips on negative float to int conversion. */
#define CPU_CLIPS_NEGATIVE 0

/* Target processor clips on positive float to int conversion. */
#define CPU_CLIPS_POSITIVE 0

/* Target processor is big endian. */
#define CPU_IS_BIG_ENDIAN 0

/* Target processor is little endian. */
#define CPU_IS_LITTLE_ENDIAN 1

/* Set to 1 to enable experimental code. */
#define ENABLE_EXPERIMENTAL_CODE 0

/* Define to 1 if you have the <alsa/asoundlib.h> header file. */
/* #undef HAVE_ALSA_ASOUNDLIB_H */

/* Define to 1 if you have the <byteswap.h> header file. */
#define HAVE_BYTESWAP_H 1

/* Define to 1 if you have the `calloc' function. */
#define HAVE_CALLOC 1

/* Define to 1 if you have the `ceil' function. */
#define HAVE_CEIL 1

/* Set to 1 if S_IRGRP is defined. */
#define HAVE_DECL_S_IRGRP 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <endian.h> header file. */
#define HAVE_ENDIAN_H 1

/* Will be set to 1 if flac, ogg and vorbis are available. */
#define HAVE_EXTERNAL_XIPH_LIBS 0

/* Define to 1 if you have the `floor' function. */
#define HAVE_FLOOR 1

/* Define to 1 if you have the `fmod' function. */
#define HAVE_FMOD 1

/* Define to 1 if you have the `free' function. */
#define HAVE_FREE 1

/* Define to 1 if you have the `fstat' function. */
#define HAVE_FSTAT 1

/* Define to 1 if you have the `fstat64' function. */
#define HAVE_FSTAT64 1

/* Define to 1 if you have the `fsync' function. */
#define HAVE_FSYNC 1

/* Define to 1 if you have the `ftruncate' function. */
#define HAVE_FTRUNCATE 1

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the `gmtime' function. */
#define HAVE_GMTIME 1

/* Define to 1 if you have the `gmtime_r' function. */
#define HAVE_GMTIME_R 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the `localtime' function. */
#define HAVE_LOCALTIME 1

/* Define to 1 if you have the `localtime_r' function. */
#define HAVE_LOCALTIME_R 1

/* Define if you have C99's lrint function. */
#define HAVE_LRINT 1

/* Define if you have C99's lrintf function. */
#define HAVE_LRINTF 1

/* Define to 1 if you have the `lround' function. */
#define HAVE_LROUND 1

/* Define to 1 if you have the `lseek' function. */
#define HAVE_LSEEK 1

/* Define to 1 if you have the `lseek64' function. */
#define HAVE_LSEEK64 1

/* Define to 1 if you have the `malloc' function. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mmap' function. */
#define HAVE_MMAP 1

/* Define to 1 if you have the `open' function. */
#define HAVE_OPEN 1

/* Define to 1 if you have the `pipe' function. */
#define HAVE_PIPE 1

/* Define to 1 if you have the `read' function. */
#define HAVE_READ 1

/* Define to 1 if you have the `realloc' function. */
#define HAVE_REALLOC 1

/* Define to 1 if you have the `setlocale' function. */
#define HAVE_SETLOCALE 1

/* Set to 1 if <sndio.h> is available. */
#define HAVE_SNDIO_H 0

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Set to 1 if you have libsqlite3. */
#define HAVE_SQLITE3 0

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 or 0, depending whether the compiler supports simple visibility
   declarations. */
#define HAVE_VISIBILITY 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define to 1 if you have the `waitpid' function. */
#define HAVE_WAITPID 1

/* Define to 1 if you have the `write' function. */
#define HAVE_WRITE 1

/* The host triplet of the compiled binary. */
#define HOST_TRIPLET "arm-unknown-linux-androideabi"

/* Define to the sub-directory where libtool stores uninstalled libraries. */
#define LT_OBJDIR ".libs/"

/* Set to 1 if compiling for OpenBSD */
#define OS_IS_OPENBSD 0

/* Set to 1 if compiling for Win32 */
#define OS_IS_WIN32 0

/* Name of package */
#define PACKAGE "libsndfile"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "sndfile@mega-nerd.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libsndfile"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libsndfile 1.0.28"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libsndfile"

/* Define to the home page for this package. */
#define PACKAGE_URL "http://www.mega-nerd.com/libsndfile/"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0.28"

/* Set to maximum allowed value of sf_count_t type. */
#define SF_COUNT_MAX 

/* The size of `double', as computed by sizeof. */
#define SIZEOF_DOUBLE 8

/* The size of `float', as computed by sizeof. */
#define SIZEOF_FLOAT 4

/* The size of `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of `int64_t', as computed by sizeof. */
#define SIZEOF_INT64_T 8

/* The size of `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of `off_t', as computed by sizeof. */
#define SIZEOF_OFF_T 4

/* Set to sizeof (long) if unknown. */
#define SIZEOF_SF_COUNT_T 0

/* The size of `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* The size of `size_t', as computed by sizeof. */
#define SIZEOF_SIZE_T 4

/* The size of `void*', as computed by sizeof. */
#define SIZEOF_VOIDP 4

/* The size of `wchar_t', as computed by sizeof. */
#define SIZEOF_WCHAR_T 4

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Set to long if unknown. */
#define TYPEOF_SF_COUNT_T 

/* Enable extensions on AIX 3, Interix.  */
#ifndef _ALL_SOURCE
# define _ALL_SOURCE 1
#endif
/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
/* Enable threading extensions on Solaris.  */
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
/* Enable extensions on HP NonStop.  */
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif
/* Enable general extensions on Solaris.  */
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif


/* Set to 1 to use the native windows API */
#define USE_WINDOWS_API 0

/* Version number of package */
#define VERSION "1.0.28"

/* Set to 1 if windows DLL is being built. */
#define WIN32_TARGET_DLL 0

/* Target processor is big endian. */
#define WORDS_BIGENDIAN 0

/* Enable large inode numbers on Mac OS X 10.5.  */
#ifndef _DARWIN_USE_64_BIT_INODE
# define _DARWIN_USE_64_BIT_INODE 1
#endif

/* Number of bits in a file offset, on hosts where this is settable. */
/* #undef _FILE_OFFSET_BITS */

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Define to 1 if on MINIX. */
/* #undef _MINIX */

/* Define to 2 if the system does not provide POSIX.1 features except with
   this defined. */
/* #undef _POSIX_1_SOURCE */

/* Define to 1 if you need to in order for `stat' and other things to work. */
/* #undef _POSIX_SOURCE */

/* Set to 1 to use C99 printf/snprintf in MinGW. */
/* #undef __USE_MINGW_ANSI_STDIO */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef ssize_t */

**Comment by evpobr** [comment]
I found this in Android SDK `stdint.h`:

```c
#if !defined __STRICT_ANSI__ || __STDC_VERSION__ >= 199901L
#  define __STDC_INT64__
#endif
typedef __int8_t      int8_t;
typedef __uint8_t     uint8_t;
typedef __int16_t     int16_t;
typedef __uint16_t    uint16_t;
typedef __int32_t     int32_t;
typedef __uint32_t    uint32_t;
#if defined(__STDC_INT64__)
typedef __int64_t     int64_t;
typedef __uint64_t    uint64_t;
#endif
```

**Comment by erikd** [comment]
There have been some changes to the configure script since the 1.0.28 release. Can someone please try current Git HEAD to see if that behaves the same?

**Comment by RuolunWeng** [comment]
hi erikd,

previous test is based on 1.0.28 release, now i just tested in currunt GIT, seems is is the same output from the terminal. 
[Résultat de Terminal.zip](https://github.com/erikd/libsndfile/files/1088047/Resultat.de.Terminal.zip)

**Comment by erikd** [comment]
Please try the topic/android-configure branch.

**Comment by RuolunWeng** [comment]
yes, it compile without any error.
it generate a libsndfile.so in /use/local/lib, i suppose that's it?
anyone has idea how can i add it to android studio project?
cause i usually works in iOS, i just drag libsndfile.a in Xcode, it works very well.

**Comment by LightSun** [comment]
@erikd can't find branch of 'topic/android-configure'
```java
$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/bugfix/sf_get_chunk_size-return
  remotes/origin/fuzz-testing
  remotes/origin/master
  remotes/origin/revert-394-sf_open_utf8
  remotes/origin/topic/1.0.29
  remotes/origin/topic/asan-cue-test
  remotes/origin/topic/opus-fuzz
  remotes/origin/topic/static-deps-build
  remotes/origin/topic/travis

```

**Comment by erikd** [comment]
The branch is gone because that patch was merged as commit c144d78fd on the master branch.

**Comment by LightSun** [comment]
@erikd as release 1.0.28 can't build for android.   Is this mean i can build the tag [c144d78]()  for android ?

**Comment by erikd** [comment]
You should build git HEAD.
