### ISSUE TITLE
Trouble installing through apt-get

### ISSUE THREAD

**Issue by kriogenx0** [erikd/libsndfile#297]
I've tried running
```sh
sudo apt-get install libsndfile
> E: Unable to locate package libsndfile
```
So then I try

```sh
sudo apt-get install libsndfile1
```
It installs, but where, how?

```sh
find /usr/ -name libsndfile*
> /usr/lib/x86_64-linux-gnu/libsndfile.so.1
> /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
```
At the end of the day my goal is to get the lib to work for ruby, with either:

```sh
gem install sndfile
gem install ruby-audio
```

https://stackoverflow.com/questions/44910504/trying-to-install-libsndfile-on-ubuntu-16

**Comment by erikd** [comment]
The command `dpkg -L <package name>` will list all files in `<package name>` and their locations.

You have installed the libsndfile libraries. If you want to build other software against that library you need to install the header files which will be in a package name like `libsndfile-dev` or `libsndfile1-dev`.

To find all the available libsndfile related packages you can run `apt-cache search libsndfile`,
