### ISSUE TITLE
question about reading WAV file

### ISSUE THREAD

**Issue by mariasmo** [erikd/libsndfile#298]
hi

i am reading a WAV file by using the read() method.

so like this:

sndfilehdl.read(buffer.data(), buffer.size())

buffer is a vector of floats: vector<float> buffer(frames*channels)

It reads fine. I send this data to a speech recognition program and i was not getting any output. after debugging it , i multiplied each frame by 32768 (which is 2^ (16 - 1)) and it worked. Why? what am i doing wrong?

The sample rate of the WAV files is 16K.

Can some one please explain what needs to be done so that I dont have to multiply with the magic number and it works with multiple sample rates and bit resolutions?

I was reading the FAQ an it says to use sf_read_short() method but I do not see that in the c++ api.
(Update: ok. i checked the c++ api and the read(short*, sf_count_t items) calls into the sf_read_short() but when i declare my vector as vector of short, it doesnt work with my speech recognition program. the only way i am able to get it working is to declare it as vector of float , read the data, and then multiply each frame with 32768 before passing it to the speech recogntion code which accepts a pointer to float)

any suggestions how to fix this on the libsndfile library calls?

thanks in advance

**Comment by erikd** [comment]
The speech recognition code has different requirements with regard to input formats from what libsndfile provides by default.

You need to figure out what those differences are and how to convert so that they are compatible.

**Comment by evpobr** [comment]
@mariasmo , what is `sndfilehdl`?
