### ISSUE TITLE
libsndfile allows writing WAV beyond its 4 GiB limit

### ISSUE THREAD

**Issue by ipatix** [erikd/libsndfile#300]
So I've just been running into this issue where my little program would create a very large WAV (SF_FORMAT_WAV) file without realizing it would go beyond the 4 GiB limit and wondered why the produced file wouldn't load up correctly in Audacity.

Could this be considered to be a bug that the "sf_write_XYZ" won't fail when writing beyond file specification limits?

I'm running the latest libsndfile in Debian Stretch (x86_64).

**Comment by erikd** [comment]
This is a feature not a bug.

*The* most likely scenario for this to happen is recording live audio to a file. If libsndfile refused to write past the 4Gig limit, a potentially unrepeatable live performance could be lost.

Once you have a WAV file that is more than 4Gig in size, you can use the [sndfile-salvage](https://github.com/erikd/libsndfile/blob/master/programs/sndfile-salvage.c) program (which should be part of the sndfile-programs package on Debian) to convert it to a format that does support files larger than 4 Gig.

**Comment by ipatix** [comment]
Oh, cool, well, I don't have a live recording but now that you mention it that does make a lot of sense (and would have in my already solved case).
Thanks for clarification.
