### ISSUE TITLE
Possible buffer overrun in sndfile-deinterleave

### ISSUE THREAD

**Issue by johnwbyrd** [erikd/libsndfile#301]
On line 70 in sndfile-deinterleave, the pathname structure is defined as a char[512].  This will cause buffer overruns on long pathnames on all platforms.  Suggested solution is to set it to char[MAX_PATH] type.

This issue was discovered by running PVS-Studio on the source base.

**Comment by erikd** [comment]
I think PVS-Studio is actually wrong here.

The only code that write to that variable is:
```
	snprintf (pathname, sizeof (pathname), "%s", argv [1]) ;
```
According to the manual page:

> The functions snprintf() and vsnprintf() write at most size bytes (including the terminating null byte ('\0')) to str.

**Comment by johnwbyrd** [comment]
OK, but won't that just truncate the path at 512 bytes?

**Comment by erikd** [comment]
Yes it will.

It should probably check the return code of `snprintf` (even if the  I *know* that the `snprintf` implementation on Windows is not C99 compliant) and error out if its too large.

**Comment by erikd** [comment]
OMFG, https://stackoverflow.com/questions/833291/is-there-an-equivalent-to-winapis-max-path-under-linux-unix

**Comment by johnwbyrd** [comment]
For clarity's sake, PVS-Studio didn't suggest using MAX_PATH; I did.  Clearly that can of worms is larger than I thought.
