### ISSUE TITLE
Compilation warnings under Visual Studio 2015 x64

### ISSUE THREAD

**Issue by johnwbyrd** [erikd/libsndfile#304]
The included warnings occur when building libsndfile under Visual Studio 2015 x64.  Nearly all of them are casting related, but not all of them.  Most of them but not all exist in the test suite, not the main library code.  Many of them indicate assumptions that sizeof( size_t ) == sizeof( int ).  It is theoretically possible that some of these assumptions might not hold for very long (longer than 2^32 bytes) sound files.

[libsndfile-warnings-vs2015-x64.txt](https://github.com/erikd/libsndfile/files/1184554/libsndfile-warnings-vs2015-x64.txt)

**Comment by erikd** [comment]
Thanks. I think the double to float and float to double ones should be ignored, but some of the others are probably worth addressing.

**Comment by evpobr** [comment]
2112 warnings under VS2017. I'll try to to something with it.

**Comment by erikd** [comment]
@evpobr That would be great. Like I said `double` to `float` and vice versa should be ignored, maybe even disabled if possible (afaiac, its simply not relevant in the libsndfile code base). Actually same for `double`/`float` to just about anything and vice versa.

Also don't think just blindly adding casts is a good solution. The best way to fix this is fix the types.

**Comment by erikd** [comment]
Wow, looking some more, some of these should just be ignored completely. Like:
```
C:\git\libsndfile\src\common.c(531): warning C4244: '=': conversion from 'sf_count_t' to 'unsigned char', 
possible loss of data
```

**Comment by evpobr** [comment]
Yes, they are just warnings, but i add casts here just to show we are sure it is not error.

**Comment by erikd** [comment]
I'm pretty sure that adding 2112 type casts is *not* the right way to address this issue. Even half that many would IMO do more harm than good in terms to code readability.

The first step would be to fix as many of these warnings by fixing the types.

**Comment by johnwbyrd** [comment]
A C++ compiler will warn on implicit casting to smaller types every time.  In 1990 I suppose you could not care when you implicitly cast an int64 type to a char.  It would be best to replace all that header_put_* business, with macro calls to a single function that always works regardless of endianness and pointer size.

**Comment by evpobr** [comment]
Tried to do that, it is to hard without rewriting a half of library. It is sad, but i think we must leave it as it is.
