### ISSUE TITLE
Build libsndfile for android on windows machine

### ISSUE THREAD

**Issue by hitendrasinh2015** [erikd/libsndfile#305]
Hi,

Can anybody help me to build libsndfile for android on windows machine.

Thanks

**Comment by erikd** [comment]
@evpobr Any clues on this?

**Comment by evpobr** [comment]
Sorry, i test under Windows and Linux only.

**Comment by hitendrasinh2015** [comment]
@evpobr , I need your help for windows then.

**Comment by evpobr** [comment]
Ask then.

**Comment by hitendrasinh2015** [comment]
:)
I tried this on windows but i am not able to build it.
https://github.com/erikd/libsndfile/blob/master/Building-for-Android.md
Do i need to install any other tools to build it on windows?(I have android ndk installed)

**Comment by evpobr** [comment]
This manual is for Linux only. You must run Linux in some virtual machine to compile.

You know, `libsndfile` was not Windows friendly very long time . With CMake it is fixed now. I hope Android builds under Windows with CMake are possible too, but it was never tested before.

You can try to make it work. This is [manual to start from](https://cmake.org/cmake/help/v3.7/manual/cmake-toolchains.7.html#cross-compiling-for-android). Make sure you have CMake 3.7 installed.

**Comment by erikd** [comment]
> You know, libsndfile was not Windows friendly very long time

libsndfile was Windows friendly. I provided (and continue to do so) a `setup.exe` program to install it.

It was not possible to *build* libsndfile on Windows, but that was because:

* The Windows C compiler was had not been updated to be compliant with the 1999 ISO C Standard.
* I don't use Windows.

**Comment by hitendrasinh2015** [comment]
@erikd , I have managed to build it from ubuntu. Can you please tell me where i can see .so file as i need that to include in my android project.

**Comment by erikd** [comment]
In the libsndfile build directry the command `find . -name \*.so` will list all the file with the `so` file extension.

**Comment by hitendrasinh2015** [comment]
I don't see any build directory. Can you please check here is the make command output.

hitendra@hitendra-H81M-DS2:~/libsnd/libsndfile-master$ **make**

Making all in Win32
make[1]: Entering directory '/home/hitendra/libsnd/libsndfile-master/Win32'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/hitendra/libsnd/libsndfile-master/Win32'
Making all in src
make[1]: Entering directory '/home/hitendra/libsnd/libsndfile-master/src'
make  all-am
make[2]: Entering directory '/home/hitendra/libsnd/libsndfile-master/src'
  CC       libsndfile_la-sndfile.lo
  CC       libsndfile_la-aiff.lo
  CC       libsndfile_la-au.lo
  CC       libsndfile_la-avr.lo
  CC       libsndfile_la-caf.lo
  CC       libsndfile_la-dwd.lo
  CC       libsndfile_la-flac.lo
  CC       libsndfile_la-g72x.lo
  CC       libsndfile_la-htk.lo
  CC       libsndfile_la-ircam.lo
  CC       libsndfile_la-macos.lo
  CC       libsndfile_la-mat4.lo
  CC       libsndfile_la-mat5.lo
  CC       libsndfile_la-nist.lo
  CC       libsndfile_la-paf.lo
  CC       libsndfile_la-pvf.lo
  CC       libsndfile_la-raw.lo
  CC       libsndfile_la-rx2.lo
  CC       libsndfile_la-sd2.lo
  CC       libsndfile_la-sds.lo
  CC       libsndfile_la-svx.lo
  CC       libsndfile_la-txw.lo
  CC       libsndfile_la-voc.lo
  CC       libsndfile_la-wve.lo
  CC       libsndfile_la-w64.lo
  CC       libsndfile_la-wavlike.lo
  CC       libsndfile_la-wav.lo
  CC       libsndfile_la-xi.lo
  CC       libsndfile_la-mpc2k.lo
  CC       libsndfile_la-rf64.lo
  CC       libsndfile_la-ogg_vorbis.lo
  CC       libsndfile_la-ogg_speex.lo
  CC       libsndfile_la-ogg_pcm.lo
  CC       libsndfile_la-ogg_opus.lo
  CC       GSM610/add.lo
  CC       GSM610/code.lo
  CC       GSM610/decode.lo
  CC       GSM610/gsm_create.lo
  CC       GSM610/gsm_decode.lo
  CC       GSM610/gsm_destroy.lo
  CC       GSM610/gsm_encode.lo
  CC       GSM610/gsm_option.lo
  CC       GSM610/long_term.lo
  CC       GSM610/lpc.lo
  CC       GSM610/preprocess.lo
  CC       GSM610/rpe.lo
  CC       GSM610/short_term.lo
  CC       GSM610/table.lo
  CCLD     GSM610/libgsm.la
  CC       G72x/g721.lo
  CC       G72x/g723_16.lo
  CC       G72x/g723_24.lo
  CC       G72x/g723_40.lo
  CC       G72x/g72x.lo
  CCLD     G72x/libg72x.la
  CC       ALAC/ALACBitUtilities.lo
  CC       ALAC/ag_dec.lo
  CC       ALAC/ag_enc.lo
  CC       ALAC/dp_dec.lo
  CC       ALAC/dp_enc.lo
  CC       ALAC/matrix_dec.lo
  CC       ALAC/matrix_enc.lo
  CC       ALAC/alac_decoder.lo
  CC       ALAC/alac_encoder.lo
  CCLD     ALAC/libalac.la
  CC       libcommon_la-common.lo
  CC       libcommon_la-file_io.lo
  CC       libcommon_la-command.lo
  CC       libcommon_la-pcm.lo
  CC       libcommon_la-ulaw.lo
  CC       libcommon_la-alaw.lo
  CC       libcommon_la-float32.lo
  CC       libcommon_la-double64.lo
  CC       libcommon_la-ima_adpcm.lo
  CC       libcommon_la-ms_adpcm.lo
  CC       libcommon_la-gsm610.lo
  CC       libcommon_la-dwvw.lo
  CC       libcommon_la-vox_adpcm.lo
  CC       libcommon_la-interleave.lo
  CC       libcommon_la-strings.lo
  CC       libcommon_la-dither.lo
  CC       libcommon_la-cart.lo
  CC       libcommon_la-broadcast.lo
  CC       libcommon_la-audio_detect.lo
  CC       libcommon_la-ima_oki_adpcm.lo
  CC       libcommon_la-alac.lo
  CC       libcommon_la-chunk.lo
  CC       libcommon_la-ogg.lo
  CC       libcommon_la-chanmap.lo
  CC       libcommon_la-windows.lo
  CC       libcommon_la-id3.lo
  CCLD     libcommon.la
/usr/bin/python ./create_symbols_file.py linux 1.0.29pre1 > Symbols.gnu-binutils
/usr/bin/python ./create_symbols_file.py darwin 1.0.29pre1 > Symbols.darwin
/usr/bin/python ./create_symbols_file.py win32 1.0.29pre1 > libsndfile-1.def
/usr/bin/python ./create_symbols_file.py os2 1.0.29pre1 > Symbols.os2
/usr/bin/python ./create_symbols_file.py static 1.0.29pre1 > Symbols.static
  CCLD     libsndfile.la
make[2]: Leaving directory '/home/hitendra/libsnd/libsndfile-master/src'
make[1]: Leaving directory '/home/hitendra/libsnd/libsndfile-master/src'
Making all in examples
make[1]: Entering directory '/home/hitendra/libsnd/libsndfile-master/examples'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/hitendra/libsnd/libsndfile-master/examples'
Making all in tests
make[1]: Entering directory '/home/hitendra/libsnd/libsndfile-master/tests'
autogen --writable utils.def
make[1]: Leaving directory '/home/hitendra/libsnd/libsndfile-master/tests'
Making all in man
make[1]: Entering directory '/home/hitendra/libsnd/libsndfile-master/man'
ln -s ./sndfile-metadata-get.1 sndfile-metadata-set.1
ln -s ./sndfile-interleave.1 sndfile-deinterleave.1
make[1]: Leaving directory '/home/hitendra/libsnd/libsndfile-master/man'
Making all in doc
make[1]: Entering directory '/home/hitendra/libsnd/libsndfile-master/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/hitendra/libsnd/libsndfile-master/doc'
Making all in regtest
make[1]: Entering directory '/home/hitendra/libsnd/libsndfile-master/regtest'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/hitendra/libsnd/libsndfile-master/regtest'
Making all in programs
make[1]: Entering directory '/home/hitendra/libsnd/libsndfile-master/programs'
  CC       sndfile-info.o
  CC       common.o
  CCLD     sndfile-info
  CC       sndfile-play.o
  CCLD     sndfile-play
  CC       sndfile-convert.o
  CCLD     sndfile-convert
  CC       sndfile-cmp.o
  CCLD     sndfile-cmp
  CC       sndfile-metadata-set.o
  CCLD     sndfile-metadata-set
  CC       sndfile-metadata-get.o
  CCLD     sndfile-metadata-get
  CC       sndfile-interleave.o
  CCLD     sndfile-interleave
  CC       sndfile-deinterleave.o
  CCLD     sndfile-deinterleave
  CC       sndfile-concat.o
  CCLD     sndfile-concat
  CC       sndfile-salvage.o
  CCLD     sndfile-salvage
make[1]: Leaving directory '/home/hitendra/libsnd/libsndfile-master/programs'
make[1]: Entering directory '/home/hitendra/libsnd/libsndfile-master'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/hitendra/libsnd/libsndfile-master'

**Comment by erikd** [comment]
`~/libsnd/libsndfile-master` is your build directory.

**Comment by hitendrasinh2015** [comment]
Yes, but i am not able see any .so file there. I check all the directories and subdirectories. What should be the problem?

**Comment by hitendrasinh2015** [comment]
Yes, but i am not able see any .so file there. I check all the directories and subdirectories. What should be the problem?

**Comment by hitendrasinh2015** [comment]
@erikd  can you please help me here?
