### ISSUE TITLE
Clamping sample values for integer formats

### ISSUE THREAD

**Issue by jkroll20** [erikd/libsndfile#309]
I ran into an [issue](https://github.com/swh/timemachine/pull/4) when writing audio signals that contain floating point values greater 1.0 to integer formats with libsndfile. This leads to integer wrap-around in WAV and corrupted encoding in FLAC files. The values should be clamped to the maximum range of the target sample format. libsndfile is probably the right place to do this, not the app generating or recording the audio. What do you think?

**Comment by erikd** [comment]
Clamping already eists. See http://www.mega-nerd.com/libsndfile/command.html#SFC_SET_CLIPPING

**Comment by jkroll20** [comment]
Thanks. I tried setting that, and something weird is happening. Wrap-around occurs when the input values go beyond -1. I modified the sine example to create a simple test: https://gist.github.com/jkroll20/22b466998c50b321af7f85506cfb8872 
This creates SF_FORMAT_PCM_24 .wav and .flac files from the same floating-point data. Only the flac file has the wraparound, not the wav. 

Am I doing something wrong? Is there file format specific clipping code in sndfile? Or could this be a problem in libflac?

**Comment by erikd** [comment]
The FLAC code path is probably missing the clipping feature.

**Comment by jkroll20** [comment]
The clipping feature isn't missing, but there is a bug in X2flacX_clip_array which clips negative values to positive values. I'll create a pull request.

**Comment by erikd** [comment]
Closing this.
