### ISSUE TITLE
Different behaviour for different input format?

### ISSUE THREAD

**Issue by eblanca** [erikd/libsndfile#312]
I have this PCM input file, and converted with sox into two different files, something32.wav (2 ch, 44 kHz, 32 bit floating point) and something16.wav (2 ch, 44 kHz, 16 bit signed integer). I took care in having a pretty loud signal and halving the peak, so the whole files had their stronger peaks at half their ranges (easy visible in audacity).
I used latest lame built with libsndfile support to encode both, got something32.mp3 and something16.mp3 - no gain at all in any step.
Then, decoded both back in wav (this was done with both madplay and mpg123, just to be sure) and loaded both in audacity. something16.wav looked the same (it kept its halved peak) but something32.wav loaded into audacity showed a full range signal, so it was somewhere amplified.

I think it was libsndfile causing this and I looked into source code to understand more.
lame is using `sf_read_int` (after `sf_command` with SFC_SET_SCALE_FLOAT_INT_READ) and this function in turn calls `host_read_f2i`. Now, the scaling value is `scale = 0x7FFFFFFF / psf->float_max` and `float_max` is the greatest float (peak) value found into the audio file, so this scaling value causes any floating point intput file to get amplified to full range.

Is there any way to alter this value and get a 1:1 scaling?
I mean, when input value is 0.5 I would like to get (2^31)/2 as a result.

[feel free to fix me if I'm wrong]

**Comment by erikd** [comment]
> Is there any way to alter this value and get a 1:1 scaling?

Yes, change LAME so if doesn't call `sf_command` with `SFC_SET_SCALE_FLOAT_INT_READ`.

**Comment by eblanca** [comment]
> Why did you do that? What is that step supposed to achieve?

I thought this was the easy way to see the signal into audacity and detect a change.

I'll try removing `sf_command` from lame and see what happens.
Thank you.

**Comment by eblanca** [comment]
I removed the `sf_command` statement from the `get_audio.c` module in lame but now, when encoding vbr files, lame always creates small 32 kbps files, with no sound at all.
Maybe removing that `sf_command` call, results in lame receiving only integer values into [ -1, 1 ] ?
