### ISSUE TITLE
run ./configure ok but make check get DSO missing...

### ISSUE THREAD

**Issue by GioMBG** [erikd/libsndfile#313]
Hi All,
./configure is seems ok but when I run make check :
`-=-=-=-=-=-=-=-=-=-= Configuration Complete =-=-=-=-=-=-=-=-=-=-=-

  Configuration summary :

    Version ....................... 1.03
    Enable debugging .............. no

  Tools :

    Compiler is GCC ............... yes
    GCC major version ............. 4

  Extra tools required for testing and examples :

    Found SNDFILE ................. yes
    Found FFTW .................... yes
    Found CAIRO ................... yes
    Found JACK .................... yes

  Installation directories :

    Program directory ............. /usr/local/bin

[root@swinger sndfile-tools-1.03]# make check
/bin/sh ./libtool --tag=CC   --mode=link gcc  -g -O2 -std=gnu99 -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Waggregate-return -Wcast-align -Wcast-qual -Wnested-externs -Wshadow -Wpointer-arith   -o src/sndfile-jackplay src/sndfile-jackplay.o -lsndfile   -ljack   -lm 
libtool: link: gcc -g -O2 -std=gnu99 -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Waggregate-return -Wcast-align -Wcast-qual -Wnested-externs -Wshadow -Wpointer-arith -o src/sndfile-jackplay src/sndfile-jackplay.o  -lsndfile -ljack -lm
/usr/bin/ld: src/sndfile-jackplay.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [src/sndfile-jackplay] Errore `
[root@swinger sndfile-tools-1.03]# 

any suggestions ?
thanks

**Comment by erikd** [comment]
The version here on Github builds correctly when configured with: `./configure --diable-jack`.

**Comment by evpobr** [comment]
This bug is unrelated to `libsndfile`, it is [sndfile-play](https://github.com/erikd/sndfile-tools) issue. Opened there as https://github.com/erikd/sndfile-tools/issues/51.
