### ISSUE TITLE
psf_fseek behaves inconsistently when psf->fileoffset != 0

### ISSUE THREAD

**Issue by foolswood** [erikd/libsndfile#320]
Ran into this when trying to get mp3 support going as it gets set by id3_skip when those tags are present (as they are in my test file).

I get behaviour (pseudocode for brevity) like:
```
seek(offset=0, whence=SEEK_CUR) -> 10
seek(offset=0, whence=SEEK_END) -> 8604437
seek(offset=0, whence=SEEK_CUR) -> 8438911
seek(offset=0, whence=SEEK_SET) -> 0
seek(offset=0, whence=SEEK_CUR) -> -165526
```

From code inspection I can see there's a bit of confusion about when we're talking about system file position and offset file position.

I'll make a branch and have a stab at tests and fixes, just thought I should document this somewhere.

**Comment by foolswood** [comment]
Branch is: https://github.com/concert/libsndfile/tree/seek_fixes
Will put up a PR once I have fixes to go with the reproducing test.

**Comment by erikd** [comment]
Closing this.
