### ISSUE TITLE
Coding style discussion

### ISSUE THREAD

**Issue by evpobr** [erikd/libsndfile#336]
@erikd, can we do some changes in code style?

The idea is to allow automatic code formatting with well known tools like `indent`, `astyle` or `clang-format`. They can be incorporated in development process as Git hook to replace our style-checking Python script.

The main problem is **space before semicolon**:  none of code formatting tools support this, space is always removed.

The second problem is **brace style**. Some tools support more options to format them, but most of them will just reformat braces to some default style. I vote for Allman, it looks similar to current style and supported anywhere. K & R is fine too.

From current style:

```c
if (datasize >= sizeof (SF_CART_INFO_16K))
{   psf->error = SFE_BAD_CART_INFO_TOO_BIG ;
    return SF_FALSE ;
    } ;
```

To Allman:

```c
if (datasize >= sizeof (SF_CART_INFO_16K))
{
    psf->error = SFE_BAD_CART_INFO_TOO_BIG;
    return SF_FALSE;
};
```

To K & R:

```c
if (datasize >= sizeof (SF_CART_INFO_16K)) {
    psf->error = SFE_BAD_CART_INFO_TOO_BIG;
    return SF_FALSE;
};
```

**Comment by erikd** [comment]
I developed this coding style over about 5 years and I've been coding in this style for over 20 years. I'm really not that keen to give it up especially since i see close to zero upsides and a number of downsides like:

* I actually like this coding style and I am used to it. Its optimized for me and I am the person who does more code in this project than anyone else.
* The current coding style is not preventing people contributing. Sure I get a slight grumble here and there but in nearly 20 years, I have never had anyone say "I'm not working on this code base because I don't like the coding style".
* Applying this would create one huge commit (maybe this would be per file) and it would not be possible to track history across that commit.

Finally, if this really was an issue I would prefer to write an indentation tool (probably in Haskell) that reformats in this style rather than switch coding styles.

**Comment by evpobr** [comment]
Ok. Then it is better to describe it CONTRIBUTING.md. I can try, but i have some questions.

**Pointer alignment:**

1. int* dummy;
2. int * dummy;
3. int *dummy;

**Varibles alignment:**

```c
int hello(void)
{
   int     a;
   int32_t a;
}
```

If there are some variables declared, they are aligned by tabs. But if there is only 1 variable, should it be aligned with tab? Or with space? I see both variants in sources.

**Comment by erikd** [comment]
Indentation should be tabs instead of spaces (pretty sure `cstyle.py` checks for that).

**Comment by evpobr** [comment]
@arthurt , @SoapGentoo , i guess it time to discuiss it again :smile:

What do you think about it?

**Comment by SoapGentoo** [comment]
@evpobr here's my opinion: pick a "simple" one (my personal preference is Allman) and have `clang-format` do the actual formatting. Enforcing `clang-format` removes any interpretation ambiguity and enforces a consistent style. And yes,
```c
if (datasize >= sizeof (SF_CART_INFO_16K))
{   psf->error = SFE_BAD_CART_INFO_TOO_BIG ;
    return SF_FALSE ;
    } ;
```
is terribly hard to read IMO and impossible to format with `clang-format`.

**Comment by evpobr** [comment]
Using the `clang-format` would be ideal, but then a huge commit overwriting all files is inevitable.

It seems to me that for a start it is worth allowing a few rules for the new code so as not to suffer every time - Allman braces style, no spaces before colons, semicolons and post-increment/post-decrement operators:

```c
static int
display_endianness (int value)
{
    switch (value)
    {
    case 1:
        break;
    default:
        break;
    }
}

```

This style will be more comfortable and will not contrast much with the existing style.

**Comment by arthurt** [comment]
Just my two cents, but I prefer K&R or other one-true-brace like styles over Allman braces. It's just a feel thing, but I dislike the whitespace gaps having the opening brace on it's own line creates.

Things from Erik's style that I like:
- Function definitions are two lines, prefix on one line, function name starting the second line.
- The non-cuddled 'else' (low priority to me but I prefer it.)
- Single-statement bodies don't require enclosing braces.
- Tabs-only as indentation, tabs as 4-char wide.
- Spaces between control statements and their predicates

Things from Erik's style I don't like:
- Spaces before semicolons. Bites me all the time, and when I get used to it, I start putting spaces before semicolons in other codebases.
- Spaces before array subscripts.

Things I'm undecided on about Erik's style
- Spaces between function names and parameters.
- Spaces before

**Comment by arthurt** [comment]
Erik's style is an acquired taste, but I don't mind it now, and the pre-commit hooks he wrote do a good job of enforcing it. I'm just maybe a bit cautious about changing it now, unsure of the benefits of the change. But, I will not oppose changing it.

**Comment by evpobr** [comment]
> I'm just maybe a bit cautious about changing it now, unsure of the benefits of the change.

Yes, for now, this will at least break two important pull requests.

> Just my two cents, but I prefer K&R or other one-true-brace like styles over Allman braces.

Both Allman and K&R styles are good for me. In fact, I would choose K&R for my project. But Allman's style is closer to the existing one, @erikd strongly opposes the K&R style, and moreover, the `cstyle.py` doesn't warn about Allman style brackets.

Maybe stop at this for now.
