### ISSUE TITLE
Building libsndfile without libvorbis dependency

### ISSUE THREAD

**Issue by MartinDelille** [erikd/libsndfile#342]
For some reason, I would like to avoid libvorbis dependency when building libsndfile (I only use PCM format). How can I do that? Is there a build parameter?

**Comment by evpobr** [comment]
Autotools:

```
./configure  --disable-external-libs
```

CMake:

```
cmake .. -DDISABLE_EXTERNAL_LIBS=ON
```

That will disable FLAC format too. No way to disable Vorbis only.

**Comment by MartinDelille** [comment]
Thanks!
