### ISSUE TITLE
Is SFC_GET_LOG_INFO documentation wrong ?

### ISSUE THREAD

**Issue by aybe** [erikd/libsndfile#345]
When I call that command with a correctly opened stream, I get an empty string which obviously makes sense to me.

It's only when I open a non-existent path, so the call fails, and then pass a null SNDFILE pointer to the command that I get a log string.

Did I miss something or documentation is wrong ?

**Comment by erikd** [comment]
Passing a NULL pointer as the SNDFILE only works the `sf_open` fails.

If `sf_open` returns non-NULL, you should use that pointer in the call to `sf_command`.

**Comment by aybe** [comment]
Yes, I understand that, what I meant was:

When there is a failure I know about the cause thanks to the log.

But when the file opens, the log is empty. Or, said differently : I expected something like 'file opened successfully, format is ... etc'.

Hope that makes sense to you :)

**Comment by erikd** [comment]
Your code should look something like:
```
  	sndfile = sf_open (pathname, SFM_READ, &info) ;
	sf_command (sndfile, SFC_GET_LOG_INFO, logbuf, sizeof (logbuf)) ;
        puts (logbuf) ;
        sf_close (sndfile) ;
```

**Comment by evpobr** [comment]
> This log buffer can often contain a good reason for why libsndfile failed to open a particular file.

Documentation is correct, log is not always contains information.

> But when the file opens, the log is empty. Or, said differently : I expected something like 'file opened successfully, format is ... etc'.

Can you make pull request? We really need help.

**Comment by erikd** [comment]
We only need a PR if there is actually something wrong with the documentation. That has not yet been confirmed.

**Comment by aybe** [comment]
I've found the error !

In http://www.mega-nerd.com/libsndfile/command.html#SFC_GET_LOG_INFO :

```
Return value:
This call will return the length of the retrieved version string.
```
This is wrong, by debugging https://github.com/erikd/libsndfile/blob/master/src/sndfile.c#L1033 as I understand C by default would return last value in case of no `return`, but in fact there is https://github.com/erikd/libsndfile/blob/master/src/sndfile.c#L1373 and effectively we get `0`.

And as I used to marshal the string from C to C# it was always empty, now I use a method similar to yours with `puts` and effectively things work as expected:

For a file that exists:

```
File : 'C:\Users\Aybe\Music\Forme - SÃ¶ndag.wav' (utf-8 converted from ucs-2)
Length : 53048084
RIFF : 53048076
WAVE
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 2
  Sample Rate   : 44100
  Block Align   : 4
  Bit Width     : 16
  Bytes/sec     : 176400
data : 53048040
End
```

For a file that does not exist:

```
File : 'C:\do_not_exists.wav' (utf-8 converted from ucs-2)
```

So, either the documentation should be changed or a `return` is missing before `snprintf`.

**Comment by erikd** [comment]
There were two handlers for `SFC_GET_LOG_INFO` (one for valid file handled and one for invalid) and one of them was incorrectly not returning the length of the log buffer. I'll fix that.

> PS Maybe in the case of a failed opening, one could append to the log something like 'file not could be opened because of ...` so we have something human-friendly.

That's what `sf_str_error (NULL)` is for.

**Comment by aybe** [comment]
Ok, thank you.
