### ISSUE TITLE
sf_read_short access violation at 0xFFFFFFFF

### ISSUE THREAD

**Issue by AlzoxX76** [erikd/libsndfile#346]
In this code : [https://pastebin.com/rGQH4Nag](url)

When I load file (a flac file) sometimes I get an error : Violation d'accès lors de la lecture de l'emplacement 0xFFFFFFFF. (It's french beceause I'm french, it is written that he has an access violation at 0xFFFFFFFF)

**Comment by evpobr** [comment]
So, where is code? Link is dead.

**Comment by AlzoxX76** [comment]
Sorry I made mistake it's [here](https://pastebin.com/rGQH4Nag)

**Comment by AlzoxX76** [comment]
The error is : 
`Exception levée à 0x512605E1 (libsndfile-1.dll) dans Test openal.exe : 0xC0000005 : Violation d'accès lors de la lecture de l'emplacement 0xFFFFFFFF.` (by the debuger)

**Comment by AlzoxX76** [comment]
It's not coincidence that the address is 0xFFFFFFFF I think, I have check the address of my file pointer but it's okey (and also the address of my vector it's okey)

**Comment by erikd** [comment]
Putting the code on pastebin is not very useful, especially since you can just paste the code here like this:
```C++
inline ALuint loadBufferSound(std::filesystem::path const& Filename)
    {
        SF_INFO FileInfos = {};
        SNDFILE* File = sf_open(Filename.generic_string().c_str(), SFM_READ, &FileInfos);
        if (!File)
            return 0;
 
        ALsizei NbSamples = static_cast<ALsizei>(FileInfos.channels * FileInfos.frames);
 
        std::vector<ALshort> Samples(NbSamples);
        if (sf_read_short(File, Samples.data(), NbSamples) < NbSamples)
            return 0;
        sf_close(File);
 
        ALenum Format;
        switch (FileInfos.channels)
        {
        case 1:  Format = AL_FORMAT_MONO16;   break;
        case 2:  Format = AL_FORMAT_STEREO16; break;
        default: return 0;
        }
        ALuint Buffer;
        alGenBuffers(1, &Buffer);
 
 
        alBufferData(Buffer, Format, Samples.data(), Samples.size() * sizeof(ALshort), FileInfos.samplerate);
 
 
        if (alGetError() != AL_NO_ERROR)
            return 0;
 
        return Buffer;
    }
```

The address that you are trying to dereference (`0xffffffff`) suggests that you are on a 32 bit system or at least the compiler is generating 32 bit code. The value `0xffffffff` is the hex version of `-1` which suggests that you are overflowing a buffer on the stack.

I have no clue about Windows, but surely the Microsoft compiler has features that would help you debug this.

**Comment by AlzoxX76** [comment]
I am on a 64 bit system and I compile in 32 bits, I have the visual studio debugger who tells me that there is a read violation at 0xFFFF

**Comment by erikd** [comment]
What I was saying is that you have a bug in your code and that you need to use whatever tools Microsoft gives you to figure this out. I don't use WIndows, so this is not something I could help with anyway.

**Comment by AlzoxX76** [comment]
It's very strange I continue programming and the bug is gone. 
To locate the bugs I use the visual studio debugger.

**Comment by erikd** [comment]
The bug in your code is almost certainly still there. On Linux with GNU GCC or Clang  I would enable AddressSanitizer which is very good and finding this kind of bug.

**Comment by AlzoxX76** [comment]
Okey,

It depends code I use, if I write a line of code useless the code generate zero error but if I not write a line of code it's work (line of code out this function)

**Comment by AlzoxX76** [comment]
Okey,

It depends code I use, if I write a line of code useless the code generate zero error but if I not write a line of code it's work (line of code out this function)

**Comment by AlzoxX76** [comment]
In code machine it's here : 
`6F8805D7  pinsrd      xmm0,eax,1  
6F8805DD  punpcklqdq  xmm0,xmm1  
6F8805E1  movaps      xmmword ptr [ebp-188h],xmm0  
6F8805E8  movdqa      xmm0,xmmword ptr [ebp-188h] `

**Comment by AlzoxX76** [comment]
If I change the name of file it's work :-|
