### ISSUE TITLE
--enable-octave silently builds without octave

### ISSUE THREAD

**Issue by janstary** [erikd/libsndfile#352]
If `./configure --enable-octave` looks for octave and does not find it, as in

```
checking for octave... no
checking for mkoctfile... no
checking for octave-config... no
```

it will continue anyway, silently building a version without Octave support.
IMHO it should fail so that the user knows it failed.

**Comment by erikd** [comment]
Whether Octave is being built or not is now reported in the configure output:
```
    Experimental code : ................... no
    Using ALSA in example programs : ...... auto
    External FLAC/Ogg/Vorbis : ............ yes
    Building Octave interface : ........... no
```

**Comment by janstary** [comment]
Thanks
