### ISSUE TITLE
Adding Opus audio in libsndfile ?

### ISSUE THREAD

**Issue by fredvs** [erikd/libsndfile#364]
Hello.

Could it be possible to integrate Opus audio in libsndfile ?
https://github.com/xiph/opus

Huh, in https://github.com/xiph/opus/blob/master/COPYING, it seems that Erik de Castro Lopo has a idea what Opus files are.  ;)

Thanks.

Fre;D

**Comment by erikd** [comment]
I would fully support the idea of someone doing this and provide guidance as needed, but this is not something I would likely find time to do in the forseeable future.

**Comment by fredvs** [comment]
Hello Erik.

Ok, I will (try to) do something.
PS: I am not a C guru.

Fre;D

**Comment by arthurt** [comment]
Willing to work on this and have some time to spare at the moment.

**Comment by fredvs** [comment]
@arthurt : Fantastic !

**Comment by arthurt** [comment]
See https://github.com/arthurt/libsndfile/tree/opus-codec 
Reading/Decode works
Writing/Encoding works
Comments/Tags work
Seeking and file length do not yet work.

Not sure if I should open a pull request yet, as it isn't done.

**Comment by erikd** [comment]
@arthurt I'll try to have a look over the weekend. Ping me if you don't see anything from me by say Monday.

**Comment by fredvs** [comment]
@arthurt : Wow.  I will test it tonight. Thanks.

Fre;D

**Comment by fredvs** [comment]
~/libsndfile-opus-codec $ ./autogen.sh
checking for autogen ... yes
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... libtoolize
checking for pkg-config ... yes
checking for python ... yes
Generating configuration files for libsndfile, please wait ... 
  aclocal 
configure.ac:327: error: macro PKG_INSTALLDIR is not defined; is a m4 file missing?
m4/ax_require_defined.m4:35: AX_REQUIRE_DEFINED is expanded from...
configure.ac:327: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1

;-(

**Comment by evpobr** [comment]
@fredvs, next time create new issue about problem. This issue is about Opus.

Library doesn't use ALSA at all, It is required for `sndfile-play` utility only. So it is not related to us. Anyway, you can disable buiding of all programs with `BUILD_PROGRAMS` set to `OFF`:

```
cmake <PATH> -DBUILD_PROGRAMS=OFF
```

**Comment by fredvs** [comment]
@evpobr . Ok, thanks for answer.  But I was thinking that maybe it has something to do with the new Opus code. (Because I do not have that problem with "official" libsndfile.)

Ok, I will do a new issue.

Fre;D

**Comment by fredvs** [comment]
Hello.

OK, tested libsndfile + Opus.
Sadly, no sound, the Opus file is not recognized.
(But using libopusfile.so it works).

[test.opus.zip](https://github.com/erikd/libsndfile/files/1855697/test.opus.zip)

**Comment by arthurt** [comment]
That file is supported:
`art@art-carbon ~/code/libsndfile $ ./programs/sndfile-info ~/Downloads/test.opus
========================================
File : /home/art/Downloads/test.opus
Length : 62705
Ogg stream data : Opus
Stream serialno : 1254499548
Opus library version: libopus 1.2.1
  OggOpus embedding version: 1
  preskip: 0 samples
  input samplerate: 48000 Hz
  gain: 0.0
  channel mapping type: 0 (mono/stereo)
  Vendor: Encoded with GStreamer Opusenc

----------------------------------------
Sample Rate : 48000
Frames      : unknown
Channels    : 2
Format      : 0x00200061
Sections    : 1
Seekable    : TRUE
Duration    : unknown`

And plays with sndfile-play. Is it possible your environment isn't set up?

**Comment by fredvs** [comment]
>  Is it possible your environment isn't set up?

Yes, I did reinstall Mint 17 64 bit yesterday, playing with ALSA  config destroy everything..
And I have lot of work to re-install everything.

Write you later when all is working again.

**Comment by fredvs** [comment]
Hello.

With a brand new os, all works better. ;-)
Even `./autogen.sh `did work out-of-the-box !
OK,` ./configure` + `make` = libsndfile.so compiled. 

But using this method with test.opus sample:

`sf_open(SoundFileName, SFM_READ, sfInfo)`

gives NULL as pointer.

With all other formats (wav, flac, ogg) the pointer is assigned.

Maybe a other method that `sf_open `mut be used for testing ?

Included the libsndfile that I get:

[libsndfile.so.1.0.29.tar.gz](https://github.com/erikd/libsndfile/files/1860828/libsndfile.so.1.0.29.tar.gz)

Fre;D

**Comment by arthurt** [comment]
First thought is make sure you are loading your compiled library in your program. I usually fake-intsall into a test prefix then modify my LD_LIBRARY_PATH environment variable to point to it.

Second, Opus support requires the --enable-experimental configure flag, otherwise it isn't built.

You can check why sf_open returned null by calling sf_strerror () on the NULL pointer. Of course, you could also just use sndfile-info program.

> 
> I see in you earlier post:
> 
>     Opus library version: libopus 1.2.1
> 
> Does it mean that libopus must be installed in system and is not compiled inside libsndfile ?

Yes, both libopus and libogg must be installed, just as libogg and libvorbis must be install for Vorbis. libopus provides the encoder and decoder, libogg provides the container support, this branch brings all the glue.

Another library from Xiph.org, libopusfile, is not used, although doing so would be really much easier than what I've done.

**Comment by fredvs** [comment]
> First thought is make sure you are loading your compiled library in your program. I usually fake-intsall into a test prefix then modify my LD_LIBRARY_PATH environment variable to point to it.

Thanks but this is not the problem, I do not use ld() but LoadLibrary() that does dynamic load of library (you may use the full path-name).
The library is loaded and all *.flac, *.wav, *ogg can be opened.

> Second, Opus support requires the --enable-experimental configure flag, otherwise it isn't built.

Ha, you did not say everything... ;-) 
That changes everything, I did not use that flag.

> Yes, both libopus and libogg must be installed, 

Yes, it was done of course. 

> Another library from Xiph.org, libopusfile, is not used, although doing so would be really much easier than what I've done

Yes, I use it for uos project: https://github.com/fredvs/uos/
The idea at beginning was to use that code for libsndfile.
libopusfile does include (AFAIK) the code of libopus ---> no dependencies of libopus.so

Thanks, Arthur, write you later with the --enable-experimental flag.

Fre;D

**Comment by fredvs** [comment]
Hello.

Aaargh, now it is speex that make trouble...

>  ~/libsndfile-opus-codec $ sudo make
> make  all-recursive
> make[1]: Entering directory '/home/fred/libsndfile-opus-codec'
> make[2]: Entering directory '/home/fred/libsndfile-opus-codec'
>   CC       src/src_libsndfile_la-ogg_speex.lo
> In file included from /usr/local/include/speex/speex.h:43:0,
>                  from src/ogg_speex.c:43:
> /usr/local/include/speex/speex_types.h:122:32: fatal error: speex_config_types.h: No such file or directory
> compilation terminated.
> Makefile:2717: recipe for target 'src/src_libsndfile_la-ogg_speex.lo' failed
> make[2]: *** [src/src_libsndfile_la-ogg_speex.lo] Error 1
> make[2]: Leaving directory '/home/fred/libsndfile-opus-codec'
> Makefile:2912: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/fred/libsndfile-opus-codec'
> Makefile:1281: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by fredvs** [comment]
Re-hello.

Ok, for speex all errors are fixed with coping speex.h into /src and add this in ogg_speex.c:
`#include "speex.h"`

But for the opus errors, even adding opus_defines.h in /src and this in ogg_opus.c:
`#include "opus_defines.h"`

There is still that errosr:

>  CCLD     src/libsndfile.la
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_close':
> ogg_opus.c:(.text+0x17a): undefined reference to `opus_multistream_encoder_destroy'
> ogg_opus.c:(.text+0x196): undefined reference to `opus_multistream_decoder_destroy'
> ogg_opus.c:(.text+0x236): undefined reference to `opus_multistream_encode_float'
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_write_samples':
> ogg_opus.c:(.text+0x3b1): undefined reference to `opus_multistream_encode_float'
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_write_header':
> ogg_opus.c:(.text+0x621): undefined reference to `opus_multistream_surround_encoder_create'
> ogg_opus.c:(.text+0x83d): undefined reference to `opus_get_version_string'
> ogg_opus.c:(.text+0xb9d): undefined reference to `opus_multistream_encoder_create'
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_read_samples':
> ogg_opus.c:(.text+0x109b): undefined reference to `opus_multistream_decode_float'
> ogg_opus.c:(.text+0x1190): undefined reference to `opus_packet_get_nb_samples'
> ogg_opus.c:(.text+0x1242): undefined reference to `opus_multistream_decode_float'
> ogg_opus.c:(.text+0x1259): undefined reference to `opus_strerror'
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_open':
> ogg_opus.c:(.text+0x13a1): undefined reference to `opus_get_version_string'
> ogg_opus.c:(.text+0x1aca): undefined reference to `opus_multistream_decoder_create'
> collect2: error: ld returned 1 exit status
> Makefile:1613: recipe for target 'src/libsndfile.la' failed
> make[2]: *** [src/libsndfile.la] Error 1
> make[2]: Leaving directory '/home/fred/libsndfile-opus-codec'
> Makefile:2912: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/fred/libsndfile-opus-codec'
> Makefile:1281: recipe for target 'all' failed
> make: *** [all] Error 2

Ho my Dog, what a hard battle.

Fre;D

**Comment by fredvs** [comment]
Re-hello.

Sorry to monopolize...

After check, ./configure write this:

`checking for opus >= 1.2.1 ... no`

But I did install opus from trunk-github and the version created is:

`libopus.so.0.6.1`

Ok, I stop to annoy you.

Good luck.

Fre;D

**Comment by arthurt** [comment]
@fredvs Sorry, have been busy again. Will be unable to work on this after next week for about a month.

> @arthurt I'll try to have a look over the weekend. Ping me if you don't see anything from me by say Monday.

@erikd Ping!

Thoughts about splitting the Xiph.org library support up?

Seek support is still pending. The BSD licenced libopusfile contains code which could be copied in to do it without *too* much work, just needs to be done.

OggPCM looks like it might be easy to support using the non-Opus part of ogg_opus.c

**Comment by fredvs** [comment]
@arthurt  No sorry, your work is perfectly working.
And now, after lot of merciless tests, all the problems with libopusfile and some external DSP libraries are gone. I wanted to make a bug report about this in the Xiph forum but did not found how to explain it (debugger do not help). 

For the seek() method, of course it will come, no stress for this.

Do you have plan to enable Opus internet URL streaming too?

With libopusfile, I use those methods to do create the web-streaming handle:

`op_test_callbacks(), op_test_open(), op_link_count().`

Would it be possible to do this with libsndfile?

And what about the Opus feature OPUS_APPLICATION_AUDIO/VOIP and friends (maybe only _AUDIO for libsndfile)?

Many thanks.

Fre,D

**Comment by tculjaga** [comment]
hi, 

i managed to build the library following your steps but im unable to produce an opus file using  generate.c in examples direcotry

**Comment by arthurt** [comment]
@tculjaga The seg-fault should be fixed. It was caused by me rushing through the writing of `ogg_opus_close()`. If `ogg_opus_write_header()` returned with failure before setting up an encoder, then `ogg_opus_close()` would seg-fault when trying to flush any buffers.

But why was `ogg_opus_write_header()` returning failure? Because Opus only supports a set number of sample rates: 8000, 12000, 16000, 24000, and 48000 Hz. I have moved this check into `ogg_opus_open()`, as `ogg_opus_write_header()` is deferred until after the first call to sf_write*

As for why Opus wasn't showing up under list_formats, it is because previously I had sf_format_check return false if sf_info.samplerate was not one of the valid rates. It would appear (if the flac format checks are to go by) that sf_format_check should not validate sample rates.

**Comment by tculjaga** [comment]
hi, Arthur, thenks for your answer!

for me it was crashing in ogg_opus_write_samples function (ogg_opus.c).

i found writelen was negative and transfn function segfauited.

not sure if its correct but.. added a writelen negative to sent it back to encode... and allowed only positive writelen to hit the transfn function.

                writelen = (len - total) / psf->sf.channels ;

                if (writelen > oopus->len - oopus->loc) {
                        writelen = oopus->len - oopus->loc ;
                        /* send to encode if writelen is negative */
                        if (writelen < 0) {
                          oopus->loc = oopus->len;
                        }
                }
                /* allow only if we have a positive writelen */
                if (writelen > 0)
                {
                        total += transfn (psf, writelen * psf->sf.channels, &(oopus->buffer [oopus->loc * psf->sf.channels]), total, ptr) ;
                        oopus->loc += writelen ;
                        } ;
                } ;

im going to test your code asap.

**Comment by tculjaga** [comment]
@arthur 

i pulled your code (removed my changes) and it still segfaults. 

writelen is still negative: 
writelen = oopus->len - oopus->loc ;

btw:
formats are listed correctly:
OGG (OGG Container format)  (extension "oga")
   Vorbis
   Opus

**Comment by arthurt** [comment]
@tculjaga Try now. I was confused as oopus->loc should never be larger than oopus->len. However, I wasn't scaling the preskip silence amount properly, so was overflowing the encode buffer in the case of lower sample rates with the preskip. I confess I had not been testing with anything other than 48000Hz sample files yet :-/

**Comment by tculjaga** [comment]
@arthur You are the man!

it does work quite stable. I linked the library into freeswitch mod_sndfile and im able to record in opus format.

one stupid question... i see that for ogg format we have oga extension registered. So, regardless if its vorbis, opus or speex (in the future) ... we will end up in a .oga file ?

**Comment by arthurt** [comment]
> one stupid question... i see that for ogg format we have oga extension registered. So, regardless if its vorbis, opus or speex (in the future) ... we will end up in a .oga file ?

That is correct, using only the context of an Ogg container, libsndfile suggests .oga

However, when iterating all the simple formats using the sf_command argument of SFC_GET_SIMPLE_FORMAT, one of the simple formats is SF_FORMAT_OGG | SF_FORMAT_OPUS with an extension of ".opus"

**Comment by fredvs** [comment]
@erikd : Ping (?)

**Comment by erikd** [comment]
Yes? Is this ready for me to review?

**Comment by fredvs** [comment]
>  Is this ready for me to review?

Huh, it seems that Arthur is blocked with seek() and there is a unsolved question : should we use code from libopusfile.so or (more root) libopus.so ?

**Comment by erikd** [comment]
in the case of Vorbis, libsndfile uses libvorbis directly instead of using libvorbisfile. I seem to remember that was because libsndfile need to provide a virtual I/O layer to all supported file formats.

Seeking in Vorbis is a huge pain in the neck and I don't expect Opus to be much different. Feel free to use Vorbis as a reference for seeking.

**Comment by arthurt** [comment]
I'm away travelling in Central America at the moment, so I haven't been working on this as much for the moment.

> here is a unsolved question : should we use code from libopusfile.so or (more root) libopus.so ?

libopusfile links to libogg and libopus itself. The work I've done uses libopus and libogg rather than libopusfile. My reasons were that since libopusfile only does decoding, libogg and libopus would have to be used directly anyways, and it would be similar to how Vorbis, Speex and OggPCM are supported in libsndfile. Further libopusfile contains a sample rate converter and channel mixer/demixer, which I think are possibly out-of-scope for libsndfile.

Usefully libopusfile is licensed under a BSD-3 clause license, so it is LGPL compatible possible to use it as a guide for code in libsndfile. Xiph.org's opus-tools is also BSD-3 clause.

@erikd Is the libsndfile-devel mailing list a good place to discuss things?

**Comment by erikd** [comment]
If libopusfile is decode only, then its not the right choice for libsndfile.

Yes, the libsndfile-devel mailing list is a good place to discuss things, but I'm actually more likely to see if here.

**Comment by arthurt** [comment]
Okay, I think the branch https://github.com/arthurt/libsndfile/tree/opus-codec is ready to start being reviewed.

Seek support is complete, and uses code adapted from Opusfile.
Better build system changes are maybe a good idea.

**Comment by erikd** [comment]
Busy right now. If you don't see something from me by Monday, please ping me again. Might also be worthwhile doing a proper PR.

**Comment by fredvs** [comment]
Hello Arthur.

I did this on Linux Mint 18 64 bit:

$ ./autogen.sh >>>>> OK

> checking for autogen ... yes
> checking for autoconf ... yes
> checking for automake ... yes
> checking for libtool ... libtoolize
> checking for pkg-config ... yes
> checking for python ... yes
> Generating configuration files for libsndfile, please wait ... 
>   aclocal 
>   libtoolize --automake --force
>   autoheader
>   automake --add-missing 
> configure.ac:38: installing 'build-aux/compile'
> configure.ac:33: installing 'build-aux/missing'
> Makefile.am: installing 'build-aux/depcomp'
>   autoconf

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

$ ./configure --enable-experimental >>>>> OK

>  Configuration summary :
> 
>     libsndfile version : .................. 1.0.29pre1
> 
>     Host CPU : ............................ x86_64
>     Host Vendor : ......................... pc
>     Host OS : ............................. linux-gnu
> 
>     CFLAGS : ..............................  -O2 -pipe -Wall -Wextra -Wpointer-arith -Wcast-align -Wcast-qual -Wshadow -Wwrite-strings -Wundef -Wuninitialized -Winit-self -Wdeclaration-after-statement -Wvla -Wbad-function-cast -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Waggregate-return 
>     CXXFLAGS : ............................  -O2 -pipe -Wall -Wextra -Wpointer-arith -Wcast-align -Wcast-qual -Wshadow -Wwrite-strings -Wundef -Wuninitialized -Winit-self -Wctor-dtor-privacy -Wnon-virtual-dtor -Woverloaded-virtual -Wreorder -Wsign-promo
>     CPPFLAGS : ............................ 
>     LDFLAGS : .............................  -Wl,-O1 -Wl,--as-needed -Wl,--no-undefined -Wl,--gc-sections
> 
>     Experimental code : ................... yes
>     Using ALSA in example programs : ...... auto
>     External FLAC/Ogg/Vorbis : ............ yes
>     Building Octave interface : ........... no
> 
>   Tools :
> 
>     C Compiler Vendor is : ................ gnu (5.4.0)
>     CXX Compiler Vendor is : .............. gnu (5.4.0)
> 
>     Sanitizer enabled : ................... no
>     Stack smash protection : .............. no
> 
>   Installation directories :
> 
>     Library directory : ................... /usr/local/lib
>     Program directory : ................... /usr/local/bin
>     Pkgconfig directory : ................. /usr/local/lib/pkgconfig
>     HTML docs directory : ................. /usr/local/share/doc/libsndfile
> 
> Compiling some other packages against libsndfile may require
> the addition of '/usr/local/lib/pkgconfig' to the
> PKG_CONFIG_PATH environment variable.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

$ make >>>>> Not OK:

>   CCLD     src/libsndfile.la
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_calculate_page_duration':
> ogg_opus.c:(.text+0x354): undefined reference to `opus_packet_get_nb_samples'
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_write_out':
> ogg_opus.c:(.text+0x3be): undefined reference to `opus_multistream_encoder_ctl'
> ogg_opus.c:(.text+0x3e6): undefined reference to `opus_multistream_encode_float'
> ogg_opus.c:(.text+0x50b): undefined reference to `opus_strerror'
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_close':
> ogg_opus.c:(.text+0xa65): undefined reference to `opus_multistream_encoder_destroy'
> ogg_opus.c:(.text+0xa92): undefined reference to `opus_multistream_decoder_destroy'
> ogg_opus.c:(.text+0xb9c): undefined reference to `opus_multistream_encode_float'
> ogg_opus.c:(.text+0xc54): undefined reference to `opus_multistream_encode_float'
> ogg_opus.c:(.text+0xcc3): undefined reference to `opus_strerror'
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_read_refill':
> ogg_opus.c:(.text+0x10a1): undefined reference to `opus_multistream_decode_float'
> ogg_opus.c:(.text+0x11c6): undefined reference to `opus_packet_get_nb_samples'
> ogg_opus.c:(.text+0x125d): undefined reference to `opus_multistream_decode_float'
> ogg_opus.c:(.text+0x1274): undefined reference to `opus_strerror'
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_write_header':
> ogg_opus.c:(.text+0x1b14): undefined reference to `opus_get_version_string'
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_seek':
> ogg_opus.c:(.text+0x21b8): undefined reference to `opus_multistream_decoder_ctl'
> src/.libs/src_libsndfile_la-ogg_opus.o: In function `ogg_opus_open':
> ogg_opus.c:(.text+0x27a9): undefined reference to `opus_get_version_string'
> ogg_opus.c:(.text+0x28f2): undefined reference to `opus_multistream_surround_encoder_create'
> ogg_opus.c:(.text+0x2929): undefined reference to `opus_multistream_encoder_ctl'
> ogg_opus.c:(.text+0x2965): undefined reference to `opus_multistream_encoder_ctl'
> ogg_opus.c:(.text+0x2988): undefined reference to `opus_multistream_encoder_ctl'
> ogg_opus.c:(.text+0x2b0e): undefined reference to `opus_strerror'
> ogg_opus.c:(.text+0x2b66): undefined reference to `opus_multistream_encoder_create'
> ogg_opus.c:(.text+0x2b7b): undefined reference to `opus_strerror'
> ogg_opus.c:(.text+0x2bae): undefined reference to `opus_multistream_encoder_ctl'
> ogg_opus.c:(.text+0x2bb8): undefined reference to `opus_strerror'
> ogg_opus.c:(.text+0x2c19): undefined reference to `opus_strerror'
> ogg_opus.c:(.text+0x30d8): undefined reference to `opus_multistream_decoder_create'
> ogg_opus.c:(.text+0x30ec): undefined reference to `opus_strerror'
> ogg_opus.c:(.text+0x3149): undefined reference to `opus_multistream_decoder_ctl'
> collect2: error: ld returned 1 exit status
> Makefile:1631: recipe for target 'src/libsndfile.la' failed
> make[2]: *** [src/libsndfile.la] Error 1
> make[2]: Leaving directory '/home/fred/libsndfile-opus-codec'
> Makefile:2930: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/fred/libsndfile-opus-codec'
> Makefile:1299: recipe for target 'all' failed
> make: *** [all] Error 2

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

?

Fre;D

**Comment by fredvs** [comment]
Hello.

It seems that the compilation is ok.
Only that warning:

> src/ogg_opus.c: In function ‘ogg_opus_close’:
> src/ogg_opus.c:1159:10: warning: ‘len’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>    nbytes = opus_multistream_encode_float (oopus->u.encode.state, oopus->buffer,
>           ^
> src/ogg_opus.c:1122:6: note: ‘len’ was declared here
>   int len ;
>       ^

So I guess that the problem should come at linking.
(But libopus.so is installed.)

Aaaargh, why with C nothing may work "out-of-the-box" ?

Fre;D

**Comment by fredvs** [comment]
Hello.

OK, I get it.

Sorry to annoy you with this but maybe it could be useful for other people.

When you compile-install opus library from last github-release, after:

`$ sudo make install`

----> opus.pc is installed in /usr/local/lib/pkgconfig/opus.pc

But, if you edit that file, there is:

---> Version: unknown

Change it with:

---> Version: 1.2.1

Yep, `./configure --enable-experimental`  find opus.

Now if you do not use the last opus library but the one provided by Debian distro:

`$ sudo apt install libopus-dev`

Here, opus.pc with be installed in /usr/lib/x86_64-linux-gnu/pkgconfig

And with this:

---> Version: 1.1.2

Change it with:

---> Version: 1.2.1

Yep, `./configure --enable-experimental`  find opus.

Yep++ compilation and linking are ok.

;-)

Now the mercyless deep and hard tests.

For me, only one word: perfect.

Seek() is working like charm, with integer or float resolution.
All the DSP applied are working (even those that crash with libopusfile.so).

IMHO, this opus addition in SndFile will give a big boost for the Opus projet.

Many thanks Arthur.

Fre;D
 


/usr/lib/x86_64-linux-gnu/pkgconfig/opus.pc

/usr/local/lib/pkgconfig/opus.pc


Version: 1.1.2

with 1.2.1

**Comment by ousia** [comment]
@erikd. I know that I’m only an average user (highly interested in having _Opus_ support 😀).

You mentioned that you were interested in reviewing the patch from @arthurt.

Would it be possible that you review that contribution?

Many thanks for your excellent work.

**Comment by fredvs** [comment]
Hello everybody.
Happy new year!

Do you have some news about libsndfile + opus files ?

Thanks.

Fre;D

**Comment by arthurt** [comment]
It's basically done, but stuck because in order to pass the test suite, Opus 1.3 is needed, and versioning works everywhere except for Opus as built by Microsoft's `vcpkg`, the only way to use anything without gouging your eyeballs out on Windows.

**Comment by evpobr** [comment]
I didn't find simple way to fix it.

**Comment by fredvs** [comment]
Ok, Thanks Arthur.

> the only way to use anything without gouging your eyeballs out on Windows.

The same here with LLVM-clang on Windows, I loose all my hair to make it works (and still problems with linking).

FreD;

**Comment by gaby64** [comment]
could anyone provide a windows build?

**Comment by fredvs** [comment]
Hello.

Sorry for that question but I did not find the right parameter to use:

What parameter to use with `./configure` to force to use `clang` compiler instead of `gcc`?

Thanks.

**Comment by nagua** [comment]
Hey @arthurt it seems the opus inside vcpkg was updated to 1.3. Any other issues remaining for this feature to be ready?

**Comment by arthurt** [comment]
@nagua Opus support has been merged into master by @erikd, and so (unless something bad happens) should be a part of the next release. I do not know when that will be.

**Comment by erikd** [comment]
We can still improve Opus support between now and the release.

**Comment by fredvs** [comment]
OK, congrats, wow and many thanks.
