### ISSUE TITLE
sf_error returning an internal-only error code

### ISSUE THREAD

**Issue by BenjiWiebe** [erikd/libsndfile#365]
My understanding is that sf_error should return one of five error numbers, SF_ERR_\*.
It seems that it will return a more-specific internal error code in at least this one condition, which is fine,
except that 1) it isn't to spec, and 2) the SFE_\* internal error codes are not accessible outside of libsndfile's own code.

Is this a bug, or am I misunderstanding something?

I'd like to be able to specify the file type via the SF_INFO RAW type, if opening the file normally returns SF_ERR_UNRECOGNISED_FORMAT.

Here's the demo:
```
#include <stdio.h>
#include <sndfile.h>
int main()
{
    char *fname = "mwe.raw";
    SF_INFO info = {0};
    SNDFILE *sfin = sf_open(fname, SFM_READ, &info);
    if(sfin == NULL)
    {
        printf("Failed opening %s\n", fname);
        int err = sf_error(NULL);
        printf("  sf errno = %d\n", err);
        printf("  sf error = %s\n", sf_strerror(NULL));
        printf("  SF_ERR_UNRECOGNISED_FORMAT = %d\n", SF_ERR_UNRECOGNISED_FORMAT);
    }
    else
    {
        printf("Make %s contain junk to test this bug.\n", fname);
        printf("  dd if=/dev/urandom of=%s bs=1k count=1\n", fname);
    }
    return 0;
}
```

**Comment by BenjiWiebe** [comment]
On my system, the output of the above program is:
```
Failed opening mwe.raw
  sf errno = 21
  sf error = File contains data in an unknown format.
  SF_ERR_UNRECOGNISED_FORMAT = 1
```

The expected output is:
```
Failed opening mwe.raw
  sf errno = 1
  sf error = File contains data in an unknown format.
  SF_ERR_UNRECOGNISED_FORMAT = 1
```
i.e. the errno should be the same as SF_ERR_UNRECOGNISED_FORMAT

**Comment by erikd** [comment]
> My understanding is that sf_error should return one of five error numbers, SF_ERR_*.

Sorry, that is a *mis*-understanding. `sf_error` can return any error value and calling `sf_str_error` with that value will return a string describing the error.

**Comment by BenjiWiebe** [comment]
@erikd So to test for all unrecognised/unknown format errors, I need to actually test if the errno == 21, instead of being able to use a SF_\* macro?
