### ISSUE TITLE
don't know how to make src/test_endswap.c

### ISSUE THREAD

**Issue by janstary** [erikd/libsndfile#369]
With current git, `make` fails immediately with
```
don't know how to make src/test_endswap.c
```
There is `src/test_endswap.def` and `src/test_endswap.tpl`, so I speculate it is
supposed to get generated from those, but the rules are not on the Makefile.

(Other `src/test_*` files are just plain C files, why is this one special?)

**Comment by evpobr** [comment]
This is [AutoGen](https://www.gnu.org/software/autogen/manual/autogen.html), and `test_endswap.c` is generated from `test_endswap.def` and `test_endswap.tpl`.

[RTFM](https://github.com/erikd/libsndfile/blob/master/README.md) please.

**Comment by janstary** [comment]
That's not it: I do run autogen and configure before.

```
$ env AUTOCONF_VERSION=2.69 AUTOMAKE_VERSION=1.15 sh ./autogen.sh
checking for autogen ... yes
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... libtoolize
checking for pkg-config ... yes
checking for python ... yes
Generating configuration files for libsndfile, please wait ... 
  aclocal 
  libtoolize --automake --force
  autoheader
  automake --add-missing 
  autoconf
```

and

```
$ ./configure
[...]
```

But then:

```
$ make
make: don't know how to make src/test_endswap.c (prerequisite of: all)
Stop in /home/hans/src/libsndfile
```

**Comment by evpobr** [comment]
I see no problem here. Give more info about system, configure logs etc. Try CMake build toolchain.

**Comment by janstary** [comment]
In 1.0.28, `src/test_endswap.c` and others get generated just fine.
Can https://github.com/erikd/libsndfile/commit/e6c42ff0270b965ed785a5c5c6bf0051792fba27#diff-c949f93d03f44a4217d7a138f9e2e54a have changed this?

**Comment by erikd** [comment]
I just tried this.
```
git clone https://github.com/erikd/libsndfile
cd libsndfile/
 ./autogen.sh && ./configure && make check
```

The file `src/test_endswap.c` was definitely generated and I can see the endswap behavior being tested when I run ``src/test_main`.

**Comment by janstary** [comment]
I just did the very same, and it didn't. Please help me debug it.

At which phase exactly does `src/test_endswap.c` get generated?
Is it the `autogen.sh` run? On my system, that says:

```
checking for autogen ... yes
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... libtoolize
checking for pkg-config ... yes
checking for python ... yes
Generating configuration files for libsndfile, please wait ... 
  aclocal 
  libtoolize --automake --force
  autoheader
  automake --add-missing 
  autoconf
```

Which one of _those_ is the one generating the file?
Can you pelase point me to the right place in the source?

**Comment by erikd** [comment]
The build rules are in the top level `Makefile.am` https://github.com/erikd/libsndfile/blob/master/Makefile.am#L384-L397

This is possibly using GNU make-isms.

**Comment by janstary** [comment]
Yes, I believe that's it. In 1.0.28, it was a simple suffix rule:

```
.def.c:
        autogen --writable $<
```

Now it's this, and contrary to the comment, it doesn't work.
In fact, it does work with `gmake`, as opposed to `make`.
(This could have occured to me earlier, sorry).

I believe it's a regression: libsndfile used to compile just fine with any make.

**Comment by erikd** [comment]
There has been a bunch of churn on those make rules, mainly because it was so hard to get right.

I really don't want to futz with this again but if you want to please go ahead. However you need to make sure that `test_endsawp.c` get rebuilt if either of `test_endswap.def` or `test_endswap.tpl` files is touched. @SoapGentoo may have something to add.

**Comment by janstary** [comment]
This is what does exactly that (right?):

```
test_endswap.c: test_endswap.def test_endswap.tpl

.SUFFIXES: .def .c

.def.c:
        autogen --writable $<
```

**Comment by SoapGentoo** [comment]
@janstary what OS are you using? This sounds like a BSD/Solaris thing (i.e. non-GNU make). And yes, `%.c : %.def %.tpl` is a GNUism and Automake usually warns about it (https://lists.gnu.org/archive/html/automake/2007-07/msg00048.html)
I am personally also in favour of the suffix rules, even though they suck from a developer point-of-view. Also, you rules are only cover half of the picture, what about all the other `.def` files? I have a branch with a "linearised" dependency chain: https://github.com/SoapGentoo/libsndfile/tree/portable-suffix-rules Could you try that please?
