### ISSUE TITLE
Problem importing WAV files

### ISSUE THREAD

**Issue by sciurius** [erikd/libsndfile#370]
All WAV files produced by my Zoom R24 are rejected by libsnd (and libsnd using tools like Ardour).

Given how many years the Zoom R-series have been on the market, if the files were really invalid there would have been a lot of complaints.

The attached WAV file (truncated to make it smaller, unrelated to the error) gives the following sndfile-info output:
`Length : 400000
RIFF : 31239256 (should be 399992)
WAVE
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 2
  Sample Rate   : 44100
  Block Align   : 4
  Bit Width     : 16
  Bytes/sec     : 176400
LIST : 393164
    *** Found weird-ass zero marker. Jumping to end of chunk.
Request for header allocation of 786328 denined.
    *** Offset is now : 0x5FFFC
*** Unknown chunk marker (1D6AC60) at position 393212. Exiting parser.

Error in WAV file. No 'data' chunk marker.`

Inspection with a hex tool shows that the LIST chunk is correctly sized, and that the data chunk therefore starts at 0x5FFF8. In the non-truncated file, the data chunk is also correctly sized.

[x1.wav.gz](https://github.com/erikd/libsndfile/files/1808688/x1.wav.gz)

[Full file](http://www.squirrel.nl/pub/xfer/uploads/3C4z-Dl_UD1uXaQEwU1ouxTw.WAV)

**Comment by erikd** [comment]
This is "libnsdfile", "libsnd" is another library.

As for the error you're seeing, this is due to your device producing invalid files, or at the very least, files that interpret the very loose (and poor quality) WAV file specs differently to `libsndfile` and most other software.
The extremely large `LIST` chunk may be causing the parser to hit a corner case that then cause the parse to fail.

If you or someone else can come up with a clean patch to handle this (almost certainly broken) file (preferably with a test) I'll happy apply it.

**Comment by sciurius** [comment]
Thanks for your reply.
The LIST chunk may be weird, and large, but the SubchunkSize is correct so there should be no problems to skip past it.
Does libsndfile try to interpret the contents of the LIST? It is all zeroes, is that allowed?

**Comment by sciurius** [comment]
This trivial fix cures the problem. All tests pass.

[wavskip.patch.txt](https://github.com/erikd/libsndfile/files/1810130/wavskip.patch.txt)

**Comment by sciurius** [comment]
It seems that the chunk is not correctly skipped when a zero marker is encountered.
The following trivial patch fixes the problem for the Zoom files.
All existing tests (still) pass.

[wavskip.patch.txt](https://github.com/erikd/libsndfile/files/1811152/wavskip.patch.txt)

**Comment by x42** [comment]
Similar crash, even with this fix (1.0.26-288-g65eabcbf) using a file from a Zoom handheld device:


```
File : /home/rgareus/Downloads/MONO-002.WAV
Length : 27293176
RIFF : 27293168
WAVE
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 1
  Sample Rate   : 44100
  Block Align   : 2
  Bit Width     : 16
  Bytes/sec     : 88200
LIST : 393164
    *** ��N
            : 50466568
Request for header allocation of 786320 denied.
*** Unknown chunk marker (19A75F8) at position 393212. Exiting parser.
*** Chunk size 4292673536 > file length 27293176. Exiting parser.

Error in WAV file. No 'data' chunk marker.
```

It works fine with libsndfile-1.0.27:
```
File : /home/rgareus/Downloads/MONO-002.WAV
Length : 27293176
RIFF : 27293168
WAVE
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 1
  Sample Rate   : 44100
  Block Align   : 2
  Bit Width     : 16
  Bytes/sec     : 88200
LIST : 393164 (too long)
data : 26899960
End

----------------------------------------
Sample Rate : 44100
Frames      : 13449980
Channels    : 1
Format      : 0x00010002
Sections    : 1
Seekable    : TRUE
Duration    : 00:05:04.988
Signal Max  : 23260 (-2.98 dB)
```

@erikd I have reported this to you by email on 06/15/2017 01:16 AM +0200 -- I cannot publicly share the file which causes the issue (it's from a Mixbus customer),

**Comment by erikd** [comment]
@x42 I can't seem to find any such email. Is it not possible to anonymize this file by overwriting the audio data with zero bytes? Its just PCM data, so no real codec involved.

**Comment by x42** [comment]
I'll see if I can do that. meanwhile I've re-sent the email

**Comment by x42** [comment]
Github does not allow attaching the file, so here it is: audio-data starts at 0x00060000, I've zeroed it starting 0x00060010:  http://robin.linuxaudio.org/tmp/zoom_sndfile_bug.wav.gz

Once unzipped, it plays fine with mplayer, ffmpeg.. and tools using libsndfile 1.0.27, but not libsndfile 1.0.28 or later.

the `*** ��N`  comes from the "%M" in src/wavlike.c:1035

**Comment by x42** [comment]
PS. should I open a new bug-report, or is this the same underlying issue?

**Comment by erikd** [comment]
Yes, please open another issue.

**Comment by sciurius** [comment]
Peculiar... The size of the LIST is exactly the same as the LIST subchunk of the Zoom R24 WAVs.
@x42 What handheld device did you use?

**Comment by x42** [comment]
The list-chunksize being identical and the `request for header allocation .. denied` is why I thought the issues are related if not the same.
