### ISSUE TITLE
autogen.sh does not produce configure script

### ISSUE THREAD

**Issue by arunk** [erikd/libsndfile#372]
I cloned the latest version of libsndfile and ran

    $ ./autogen.sh

This is the output I got:

    checking for autogen ... 
    You must have GNU autogen installed to compile libsndfile.
    Download the appropriate package for your distribution,
    or get the source tarball at ftp://ftp.gnu.org/pub/gnu/
    no 
    checking for autoconf ... yes
    checking for automake ... yes
    checking for libtool ... libtoolize
    checking for pkg-config ... yes
    checking for python ... yes

But I don't see a configure script in the main folder. I tried running `autoconf` which produced a configure file, but when I run this file I get errors.

    checking whether configure should try to set CFLAGS/CXXFLAGS/CPPFLAGS/LDFLAGS... yes
    configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."/build-aux

**Comment by evpobr** [comment]
```
checking for autogen ... 
You must have GNU autogen installed to compile libsndfile.
Download the appropriate package for your distribution,
or get the source tarball at ftp://ftp.gnu.org/pub/gnu/
```

You're missing [autogen tool](https://www.gnu.org/software/autogen/).

Install it and you will get your script. Something like:

```
sudo apt-get install autogen
```

**Comment by arunk** [comment]
Not sure what the embarassed emoji is, but i wish i could insert it here. Thanks @evpobr ! :*) closest i can come to blushing cheeks.

**Comment by arunk** [comment]
Could someone provide me the configure script for cross-compiling this for an STM32F discovery board?
I tried 

    export CC=arm-none-eabi-gcc
    ./configure --host=arm-unknown-linux-gnueabi

But i get this:

checking for arm-none-eabi-gcc... arm-none-eabi-gcc
checking whether the C compiler works... no

Looking at config.log provides nothing useful.

Thanks

**Comment by erikd** [comment]
Your C (cross) compiler does not work. That's what "undefined reference" means. No configure script can fix that.

**Comment by arunk** [comment]
I'm using the cross-compiler with which I'm able to compile programs and flash it to my board. I guess I was wondering if there are more configuration switches, or other environment variables I need to define besides CC to get this to work.

**Comment by erikd** [comment]
It would not surprise me if you need to define both `CFLAGS` and `LDFLAGS`.

**Comment by arunk** [comment]
@erikd have tried searching around for what `CFLAGS` and `LDFLAGS` to use, but haven't found anything helpful. I found [this](https://stackoverflow.com/questions/19419782/exit-c-text0x18-undefined-reference-to-exit-when-using-arm-none-eabi-gcc) SO question, so I tried to manually add `--specs=nosys.specs` to the configure script in the ac_compile variable. But that didn't help either. Could you point me to what these settings ought to be? Thanks.

**Comment by arunk** [comment]
@erikd set `export LDFLAGS="specs=nosys.specs"` and that solved the configure problem. Running into other errors during make, which I will create a new issue for. Thanks for your help!
