### ISSUE TITLE
Winmm.lib vs winmm ?

### ISSUE THREAD

**Issue by 7890** [erikd/libsndfile#377]
https://github.com/erikd/libsndfile/blob/4a59daf7e7726bece36188108f281cbb6434df32/CMakeLists.txt#L481
When building with MXE there is an error shown for Winmm.
However changing Winmm.lib to winmm seemed to work.

**Comment by erikd** [comment]
@evpobr ?

**Comment by evpobr** [comment]
Buzy next two days, then fix it.

17 мар. 2018 г. 3:13 пользователь "Erik de Castro Lopo" <
notifications@github.com> написал:

**Comment by 7890** [comment]
Thank you @evpobr,
That was super quick!
I hope it won't break cmake build on windows.

For reference, here is what i get for winmm in the _build directory:
```
egrep -r winmm *
CMakeFiles/sndfile-play.dir/linklibs.rsp:libsndfile.a -lwinmm -Wl,-Bstatic -lm -Wl,-Bdynamic -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 
Binary file sndfile-play.exe matches
```
from MXE home
```
find | grep winmm
./usr/i686-w64-mingw32.static/lib/libwinmm.a
```

**Comment by evpobr** [comment]
> I hope it won't break cmake build on windows.

It [won't](https://ci.appveyor.com/project/evpobr/libsndfile/build/1.0.29pre1-197).

**Comment by 7890** [comment]
good :)
The cmake build is great. I also like the tests a lot.
Thanks again
