### ISSUE TITLE
Can't compile with cmake, in an external directory

### ISSUE THREAD

**Issue by LuoZhongYao** [erikd/libsndfile#392]
~/.temp ❯❯❯ tar xf ~/Download/libsndfile-1.0.28.tar.gz 
~/.temp ❯❯❯ cd libsndfile-1.0.28/
~/.t/libsndfile-1.0.28 ❯❯❯ mkdir build
~/.t/libsndfile-1.0.28 ❯❯❯ cd build/
~/.t/l/build ❯❯❯ cmake ..
-- The C compiler identification is GNU 8.0.1
-- The CXX compiler identification is GNU 8.0.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
/usr/bin/grep: configure.ac: No such file or directory
CMake Error at CMakeLists.txt:25 (string):
  string sub-command STRIP requires two arguments.

CMake Error at CMakeLists.txt:26 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

-- libsndfile version : 
-- Running autoheader to create src/config.h.in
-- Post processing src/config.h.in
/usr/bin/grep: /home/z/.temp/libsndfile-1.0.28/CMakeFiles/config.h.in: No such file or directory
CMake Error at CMakeLists.txt:54 (if):
  if given arguments:

    "GREATER" "0"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "/home/z/.temp/libsndfile-1.0.28/build/CMakeFiles/CMakeOutput.log".
~/.t/l/build ❯❯❯ uname -a
Linux localhost.localdomain 4.16.4-300.fc28.x86_64 #1 SMP Tue Apr 24 22:15:13 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
~/.t/l/build ❯❯❯ cmake --version
cmake version 3.11.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
~/.t/l/build ❯❯❯

**Comment by evpobr** [comment]
v1.0.28 has rudimental CMake support. Try to build from git master.

**Comment by LuoZhongYao** [comment]
master is ok.
