### ISSUE TITLE
Missing codes between SF_STR_TRACKNUMBER and SF_STR_GENRE ?

### ISSUE THREAD

**Issue by repalov** [erikd/libsndfile#401]
Is it ok that adjacent constants
SF_STR_TRACKNUMBER has decimal code **9**, and 
SF_STR_GENRE has decimal code **16**
?

https://github.com/erikd/libsndfile/blob/7ea3f9d8746000cc82c016d0b5d48452bb80e9fe/src/sndfile.h.in#L251-L252

**Comment by evpobr** [comment]
Perhaps it was done by mistake, but in this case it is pretty safe.

We cannot change it without breaking compatibility with existing apps so let's leave it as it is.

Thanks anyway.
