### ISSUE TITLE
Autotools builds fail if pkg-config version < 0.27

### ISSUE THREAD

**Issue by evpobr** [erikd/libsndfile#402]
New Travis CI builds fail with error:

    configure.ac:335: error: macro PKG_INSTALLDIR is not defined; is a m4 file missing?
    m4/ax_require_defined.m4:35: AX_REQUIRE_DEFINED is expanded from...
    configure.ac:335: the top level
    autom4te: /usr/bin/m4 failed with exit status: 1

@SoapGentoo, can you help?

**Comment by erikd** [comment]
pkg-cionfig version 0.27 was released in 2012.

Why are we using an Ubuntu version that old for Travis?

**Comment by evpobr** [comment]
I guess Travis image has pkg-config 0.26, so script tries to upgrade it from `pa:cz.nic-labs/knot-dns` repo, but it seems like it fails now. I don't know why.

**Comment by erikd** [comment]
I suspect the easiest fix is to upgrade the version of Ubuntu that travis builds on.

**Comment by evpobr** [comment]
It is. But there is no newer image yet.

**Comment by erikd** [comment]
Using Xenial works and the change has been merged. Closing this. Thanks!

**Comment by SoapGentoo** [comment]
wow, I wasn't aware Xenial is actually working at this point. It seems that it might be experimental at this stage: https://github.com/travis-ci/travis-ci/issues/7260#issuecomment-354350596

**Comment by erikd** [comment]
Trusty is over 4 years old at this point. There have been two Ubuntu LTS releases since Trusty.

**Comment by SoapGentoo** [comment]
You're preaching to the choir. The fact that Travis is "in the process of making Trusty the default" says a lot about Travis and the state it's in.

**Comment by erikd** [comment]
> Yes, Xenial is completely experimental and could be broken at any time.

Xenail was released on 2016. If Travis can't provide a reasonably up-to-date base OS, they we will probably need to file a new CI.
