### ISSUE TITLE
#include "sfconfig.h" superfluous in examples/generate.c?

### ISSUE THREAD

**Issue by d3592182** [erikd/libsndfile#411]
Howdy,

I'm trying out using the dll in vs2017 and examples/generate.c fails with `#include "sfconfig.h"` not found.

If I comment it out, it compiles and runs too. VLC can't play the resulting w64 files but I reckon that's unrelated.

So my report is... maybe that include line is superfluous, maybe even incorrect in generate.c

**Comment by evpobr** [comment]
Hm, i forgot to add `generate` example to CMakeLists.txt. How did you get it?

**Comment by evpobr** [comment]
And i dont' see `#include "sfconfig.h"` there. Maybe you sources are outdated?

**Comment by d3592182** [comment]
Terribly sorry! I was looking at the 1.0.28 tarball sources.
