### ISSUE TITLE
How to open an ogg vorbis or flac file in libsndfile?

### ISSUE THREAD

**Issue by d3912120** [erikd/libsndfile#413]
Hi, I'm happy to see that vorbis to pipe works https://github.com/erikd/libsndfile/issues/110 and hope the same is true for flac. I'm still at the beginning of understanding libsndfile though, mainly working with examples to learn.

https://github.com/erikd/sndfile-tools/blob/master/src/mix-to-mono.c uses `sf_open` to open the input file. If I pass an ogg vorbis or flac file, it does not work, file info is NULL.

How can I open an ogg vorbis or flac file in libsndfile?

**Comment by erikd** [comment]
How did you get libsndfile? Did you compile it from source? On what OS?

libsndfile uses the libFLAC for handling FLAC files and libogg/libvorbis/libvoribsenc for handling Ogg/Vorbis files.

Installing the required libraries is documented in the README of this repo.

**Comment by d3912120** [comment]
Thank you for replying!

I got http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28-w64-setup.exe and extracted it using innoextract.

I'm on Win64, VS2017. I included the library properly by following instructions at https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2017 (the Create a client app that uses the DLL part)

mix-to-mono compiles fine (I copied it and mixed it with sndfile-tools/common.c in an empty project. It opens wav files just fine.

I was assuming that the above has flac and ogg vorbis built-in without the need for dll files. But now that I compile and run `examples/list_formats.c`, I can see that this is not the case.

The official binaries are built without flac/oggvorbis? Or they need DLL files to be present?

By the way: I tried replacing `sf_open` with `sf_wchar_open` and that command would not be found/compile fails. `error C3861: 'sf_wchar_open': identifier not found`

**Comment by d3912120** [comment]
Oh boy.

I didn't copy the actual `libsndfile-1.dll` file into the exe's folder. I just assumed I did because I'm used to code not working at all when the dll of used libraries isn't present. Copying the dll makes FLAC and OGG appear in the list of `list_formats.c`

**Comment by evpobr** [comment]
Don't waste your time, use [Vcpkg package manager](https://github.com/Microsoft/vcpkg).

If you want to use Vcpkg with Visual Studio solutions, set up user-wide intergation (Described in README,md).

Then install `libsndfile` package with:

    ./vcpkg install libsndfile:x64-windows

That's all. Build your solution, all dependency DLLs will be copied to output directory.
