### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by d3592182** [erikd/libsndfile#417]
I saw a typo yesterday and forgot where so i decided to report this one as long as i remember its location

https://github.com/erikd/libsndfile/blob/7ea3f9d8746000cc82c016d0b5d48452bb80e9fe/tests/virtual_io_test.c

line 90

    	**	This will brack badly for files over 2Gig in length, but

should be

    	**	This will break badly for files over 2Gig in length, but

**Comment by evpobr** [comment]
Make [pull request](https://help.github.com/articles/about-pull-requests/) please. You can [edit this file directly in browser](https://help.github.com/articles/editing-files-in-your-repository/). Name commit as we usually do:

```
tests/vrtual_io_test.c: Fix typo

Closes #417
```
