### ISSUE TITLE
Reduce size of libsndfile.so?

### ISSUE THREAD

**Issue by fredvs** [erikd/libsndfile#419]
Hello.

Could it be possible to add a option to the linker to reduce the size of the binary-library?

In the Pascal world, we call this "SmartLinking".

In fact, it is done using the **--gc-sections** parameter at linking.
http://sourceware.org/binutils/docs/ld/Options.html

> ‘--gc-sections’ decides which input sections are used by examining symbols and relocations. The section containing the entry symbol and all sections containing symbols undefined on the command-line will be kept, as will sections containing symbols referenced by dynamic objects. Note that when building shared libraries, the linker must assume that any visible symbol is referenced. Once this initial set of sections has been determined, the linker recursively marks as used any section referenced by their relocations.

Example: gcc --gc-sections -o test.so test.o

Thanks.

Fre;D

**Comment by erikd** [comment]
First you need to convince me that this has any effect at all. I somehow doubt that it will. Secondly, if you do find things that can be dropped at link time like this, it would probably be a better idea to delete the source code that generated this un-necessary sections.

**Comment by fredvs** [comment]
> First you need to convince me that this has any effect at all.
With pleasure!  But for this I need help.
After ./configure, where on what file is the script for the compiler?
I need to add `--gc-sections`
Example: `gcc --gc-sections -o libsnfile.so libsnfile.o`

> it would probably be a better idea to delete the source code that generated these un-necessary sections.
Of course and I have no doubt that your code is clean.
But you will be impressed by the amount of garbage that the compiler (gcc, fpc, ..., even clang) can produce.

You may test it with a simple "Hello world" test.
Try `gcc -o helloworld.bin helloworld.o` vs `gcc --gc-sections -o helloworld.bin helloworld.o`

Fre;D

**Comment by erikd** [comment]
Sorry, but that is not convincing me.

If you want to see progress on this issue, then you need to figure out how do it in the libsndfile build system, show that it makes differences and then show me how to do it so I can test if for myself.

**Comment by brianlheim** [comment]
@fredvs if you use CMake you can use CMAKE_C_FLAGS like it says in the readme. Otherwise your compiler and the configure script should both have options for inserting additional compilation flags.

**Comment by erikd** [comment]
Yeah, sure, if you can show me that it makes a worthwhile difference with CMake, I'd may be motivated enough to make it work the autoconf build system.

**Comment by evpobr** [comment]
https://github.com/erikd/libsndfile/blob/2d658815e33331837ad9411e7ad8a3cb630f3426/configure.ac#L551

**Comment by erikd** [comment]
@fredvs it is already part of the autoconf build as shown by @evpobr .

Closing this.

**Comment by fredvs** [comment]
> @fredvs it is already part of the autoconf build as shown by @evpobr 

Ooops, ok (and so you was already convinced!)

Sorry for the noise.

Fre;D

**Comment by fredvs** [comment]
Hello.

For info: on a FreeBSD multi-arch system (that can run 64 and 32 bit apps), running a 32 bit application compiled with `--gc-sections will fail.

This because FreeBSD use `ld`(from Linux) with garbage collector not compatible with FreeBSD multi-arch design.

(I did give a patch for ld to correct this but FreeBSD team ignore it.)

To resume: libsnfile.so 32 bit for FreeBSD will not work on a FreeBSD 64 bit multi-arch if compiled with --gc-sections..

Fre;D
