### ISSUE TITLE
issue report

### ISSUE THREAD

**Issue by niugx** [erikd/libsndfile#428]
hi，

i found a issue，i want  to confirm whether it is vulnerability，who i can contact for this issue?

thanks

**Comment by evpobr** [comment]
The author, @erikd, So, what's the problem to report it here?

**Comment by niugx** [comment]
i leaved a message to erikd by gitter,  i have not received message from him，so, as it is a potential vulnerability, can i report the issue to by gitter?

**Comment by evpobr** [comment]
Send email.
