### ISSUE TITLE
Hardcoded Cue Limit of 1000

### ISSUE THREAD

**Issue by conradjones** [erikd/libsndfile#430]
Is there a reason for the hardcoded cue limit of 1000 ? 

It's at odds with documentation which says 'There is also an SF_CUES_VAR #define that allows reading/writing more than 100 cue markers.'  granted the SF_CUES_VAR define will allow reading more than 100 cues, but if there is more than 1000 they will never get read by the library when the chunks are processed.

I need to support any number of cues. Is there any appetite for a PR which allows dynamically allocating the buffer passed to SFC_GET_CUE ? 

I build the library myself and will be removing the 1000 limit from my build, I would prefer it upstream though or at least configurable upstream.. thoughts ?

`case cue_MARKER :
					parsestage |= HAVE_other ;

					{	uint32_t thisread, bytesread, cue_count, position, offset ;
						int id, chunk_id, chunk_start, block_start, cue_index ;

						bytesread = psf_binheader_readf (psf, "4", &cue_count) ;
						psf_log_printf (psf, "%M : %u\n", marker, chunk_size) ;

						if (cue_count > 1000)
						{	psf_log_printf (psf, "  Count : %u (skipping)\n", cue_count) ;
							psf_binheader_readf (psf, "j", (cue_count > 20 ? 20 : cue_count) * 24) ;
							break ;
							} ;`

**Comment by erikd** [comment]
> Is there a reason for the hardcoded cue limit of 1000 ?

The need to be a limit. Having no limit would likely provide a vector for a Denial-of-Service attack.

That said, `1000` may be too small. What do you suggest?

**Comment by brianlheim** [comment]
Could there be a function that takes a count and offset? Then the cues could be read in chunks up to any limit. IIUC this would be `O(count + offset)` time (maybe not, if the number of cues is cached) but would have the added benefit of being able to support queries of the form "get the `n`th cue" without requiring `O(n)` memory.

**Comment by erikd** [comment]
> Could there be a function that takes a count and offset?

That is a *large* change. Changing a constant is a small change.

**Comment by brianlheim** [comment]
Just a suggestion. Changing a hardcoded constant to a larger hardcoded constant isn't exactly a great solution IMO unless you increase it to the theoretical limit.

**Comment by erikd** [comment]
This is fixed in commit ba8a7577c6ac7 .
