### ISSUE TITLE
Use CreateFileA instead of CreateFile

### ISSUE THREAD

**Issue by aholzinger** [erikd/libsndfile#442]
Line  791 of
https://raw.githubusercontent.com/erikd/libsndfile/master/src/file_io.c:

CreateFile is used which is a #define and thus is depending on the UNICODE #define. When compiling file_io.c with UNICODE defined this leads to CreateFileW which isn't intended.

It would be better to use CreateFileA - which is the real function name and not a #define - instead.

**Comment by erikd** [comment]
@evpobr Maybe you could respond to this.
