### ISSUE TITLE
Some inconsistencies in the code

### ISSUE THREAD

**Issue by ManSoSec** [erikd/libsndfile#445]
We noticed 2 inconsistencies in the code:

1) An if condition is missing here:
https://github.com/erikd/libsndfile/blob/master/src/gsm610.c#L570
```C
if (count != writecount)
			break ;
```
While it is done in many other locations like:
https://github.com/erikd/libsndfile/blob/master/src/ima_adpcm.c#L965
https://github.com/erikd/libsndfile/blob/master/src/g72x.c#L546
and many other locations

================================================================

2) Missing input argument check (format variable)
https://github.com/erikd/libsndfile/blob/master/src/common.c#L551
```C
if (! format)
		return psf_ftell (psf) ;
```

While it is done here:
https://github.com/erikd/libsndfile/blob/master/src/common.c#L961

**Comment by erikd** [comment]
Are you reporting a bug? If so, what exactly is the bug?

**Comment by ManSoSec** [comment]
I am concluding based on inconsistencies in your code and by static analysis and I guess they are bugs. For example, the second case, if `format` is NULL, `while ((c = *format++))` might issue a null dereference and system crash while a similar check is performed in `psf_binheader_readf`. The first case seems to me causing malfunction rather than security implication.

**Comment by ManSoSec** [comment]
Well, I agree that fuzz testing is more useful, but static analysis may let you find some bugs that you cannot find easily by fuzzers. These 2 cases that I reported are based on the inconsistencies in your code so it takes you a few minutes to take a look. The reason I reported them is to help to minimize inconsistency in your code and find potential bugs. If you think they are useless, just ignore my report and close this issue :-)

Thanks!

**Comment by erikd** [comment]
Unless you can provide an input file that causes libsndfile to misbehave, these are not bugs.

I have looked at the two things you pointed out, and I agree they are "inconsistencies" but this code base is pretty comprehensively tested and I trust the tests.

However, I do accept code clean up patches, as long as all the tests pass. Submit patches for this and I will merge them (assuming the tests pass).

**Comment by rbtcollins** [comment]
The first looks like a bug; the second is dealing with different semantics on read vs write.

**Comment by erikd** [comment]
The first is an extra sanity check that is probably not necessary, but has now been added.

The second is a check that a pointer is not NULL in a function that is not directly exposed via the API. Since there is no way to called this function from outside the library, it again is probably not necessary, but again, has now been added.

Neither of these issues of any concern.
