### ISSUE TITLE
can't link ogg vorbis and flac libraries on ubuntu

### ISSUE THREAD

**Issue by Stolaine** [erikd/libsndfile#446]
I am getting this error while i rum "make" command

I read here that it might be an issue with the linking of the libraries
https://stackoverflow.com/questions/21973748/libsndfile-linking-error-with-libvorbis-and-libogg-when-compiling-on-mac-10-6-sn

similar solution is given in this issue also
https://github.com/erikd/libsndfile/issues/96

but none of them seems to be helpful

i am using ubuntu and trying to build wav2letter++

[ 10%] Building CXX object CMakeFiles/Train.dir/src/runtime/Distributed.cpp.o
[ 10%] Linking CXX executable Train
/usr/local/lib/libsndfile.a(flac.c.o): In function `sf_flac_meta_get_vorbiscomments':
flac.c:(.text+0xd3a): undefined reference to `FLAC__metadata_object_vorbiscomment_find_entry_from'
/usr/local/lib/libsndfile.a(flac.c.o): In function `sf_flac_error_callback':
flac.c:(.text+0x11ae): undefined reference to `FLAC__StreamDecoderErrorStatusString'
/usr/local/lib/libsndfile.a(flac.c.o): In function `flac_write_strings':
flac.c:(.text+0x138c): undefined reference to `FLAC__metadata_object_new'
flac.c:(.text+0x14dc): undefined reference to `FLAC__metadata_object_vorbiscomment_entry_from_name_value_pair'
flac.c:(.text+0x14f8): undefined reference to `FLAC__metadata_object_vorbiscomment_append_comment'
flac.c:(.text+0x1547): undefined reference to `FLAC__stream_encoder_set_metadata'
/usr/local/lib/libsndfile.a(flac.c.o): In function `flac_write_header':
flac.c:(.text+0x15e7): undefined reference to `FLAC__stream_encoder_init_stream'
flac.c:(.text+0x1604): undefined reference to `FLAC__StreamEncoderInitStatusString'
/usr/local/lib/libsndfile.a(flac.c.o): In function `flac_close':
flac.c:(.text+0x1886): undefined reference to `FLAC__metadata_object_delete'
flac.c:(.text+0x18a5): undefined reference to `FLAC__stream_encoder_finish'
flac.c:(.text+0x18b5): undefined reference to `FLAC__stream_encoder_delete'
flac.c:(.text+0x18e6): undefined reference to `FLAC__stream_decoder_finish'
flac.c:(.text+0x18f5): undefined reference to `FLAC__stream_decoder_delete'
/usr/local/lib/libsndfile.a(flac.c.o): In function `flac_enc_init':
flac.c:(.text+0x1a1c): undefined reference to `FLAC__stream_encoder_delete'
flac.c:(.text+0x1a21): undefined reference to `FLAC__stream_encoder_new'
flac.c:(.text+0x1a61): undefined reference to `FLAC__stream_encoder_set_channels'
flac.c:(.text+0x1aaf): undefined reference to `FLAC__stream_encoder_set_sample_rate'
flac.c:(.text+0x1af4): undefined reference to `FLAC__stream_encoder_set_bits_per_sample'
flac.c:(.text+0x1b36): undefined reference to `FLAC__stream_encoder_set_compression_level'
/usr/local/lib/libsndfile.a(flac.c.o): In function `flac_read_header':
flac.c:(.text+0x1bc5): undefined reference to `FLAC__stream_decoder_delete'
flac.c:(.text+0x1bca): undefined reference to `FLAC__stream_decoder_new'
flac.c:(.text+0x1bf9): undefined reference to `FLAC__stream_decoder_set_metadata_respond_all'
flac.c:(.text+0x1c46): undefined reference to `FLAC__stream_decoder_init_stream'
flac.c:(.text+0x1c64): undefined reference to `FLAC__stream_decoder_process_until_end_of_metadata'
flac.c:(.text+0x1c99): undefined reference to `FLAC__stream_decoder_delete'
flac.c:(.text+0x1cb1): undefined reference to `FLAC__stream_decoder_get_decode_position'
/usr/local/lib/libsndfile.a(flac.c.o): In function `flac_read_loop':
flac.c:(.text+0x1fe9): undefined reference to `FLAC__stream_decoder_get_state'
flac.c:(.text+0x2004): undefined reference to `FLAC__StreamDecoderStateString'
flac.c:(.text+0x207b): undefined reference to `FLAC__stream_decoder_process_single'
flac.c:(.text+0x208e): undefined reference to `FLAC__stream_decoder_get_state'
flac.c:(.text+0x20a9): undefined reference to `FLAC__StreamDecoderStateString'
/usr/local/lib/libsndfile.a(flac.c.o): In function `flac_write_s2flac':
flac.c:(.text+0x24f1): undefined reference to `FLAC__stream_encoder_process_interleaved'
/usr/local/lib/libsndfile.a(flac.c.o): In function `flac_write_i2flac':
flac.c:(.text+0x2655): undefined reference to `FLAC__stream_encoder_process_interleaved'
/usr/local/lib/libsndfile.a(flac.c.o): In function `flac_write_f2flac':
flac.c:(.text+0x2805): undefined reference to `FLAC__stream_encoder_process_interleaved'
/usr/local/lib/libsndfile.a(flac.c.o): In function `flac_write_d2flac':
flac.c:(.text+0x2dfc): undefined reference to `FLAC__stream_encoder_process_interleaved'
/usr/local/lib/libsndfile.a(flac.c.o): In function `flac_seek':
flac.c:(.text+0x331b): undefined reference to `FLAC__stream_decoder_seek_absolute'
/usr/local/lib/libsndfile.a(ogg.c.o): In function `ogg_read_first_page':
ogg.c:(.text+0x1c): undefined reference to `ogg_stream_reset'
ogg.c:(.text+0x28): undefined reference to `ogg_sync_reset'
ogg.c:(.text+0x39): undefined reference to `ogg_sync_buffer'
ogg.c:(.text+0x132): undefined reference to `ogg_sync_wrote'
ogg.c:(.text+0x14c): undefined reference to `ogg_sync_pageout'
ogg.c:(.text+0x163): undefined reference to `ogg_page_bos'
ogg.c:(.text+0x1ac): undefined reference to `ogg_stream_clear'
ogg.c:(.text+0x1be): undefined reference to `ogg_page_serialno'
ogg.c:(.text+0x1d2): undefined reference to `ogg_stream_init'
ogg.c:(.text+0x1f0): undefined reference to `ogg_stream_pagein'
ogg.c:(.text+0x231): undefined reference to `ogg_stream_packetout'
/usr/local/lib/libsndfile.a(ogg.c.o): In function `ogg_open':
ogg.c:(.text+0x381): undefined reference to `ogg_sync_clear'
ogg.c:(.text+0x391): undefined reference to `ogg_stream_clear'
/usr/local/lib/libsndfile.a(ogg.c.o): In function `ogg_close':
ogg.c:(.text+0x40f): undefined reference to `ogg_sync_clear'
ogg.c:(.text+0x41f): undefined reference to `ogg_stream_clear'
/usr/local/lib/libsndfile.a(ogg.c.o): In function `ogg_stream_classify':
ogg.c:(.text+0x442): undefined reference to `ogg_sync_init'
/usr/local/lib/libsndfile.a(ogg.c.o): In function `ogg_page_classify':
ogg.c:(.text+0x63c): undefined reference to `ogg_page_serialno'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_read_header':
ogg_vorbis.c:(.text+0x49): undefined reference to `vorbis_block_clear'
ogg_vorbis.c:(.text+0x59): undefined reference to `vorbis_dsp_clear'
ogg_vorbis.c:(.text+0x69): undefined reference to `vorbis_comment_clear'
ogg_vorbis.c:(.text+0x79): undefined reference to `vorbis_info_clear'
ogg_vorbis.c:(.text+0x89): undefined reference to `vorbis_info_init'
ogg_vorbis.c:(.text+0x99): undefined reference to `vorbis_comment_init'
ogg_vorbis.c:(.text+0xbf): undefined reference to `vorbis_synthesis_headerin'
ogg_vorbis.c:(.text+0x123): undefined reference to `vorbis_comment_query'
ogg_vorbis.c:(.text+0x189): undefined reference to `ogg_sync_pageout'
ogg_vorbis.c:(.text+0x1a3): undefined reference to `ogg_sync_buffer'
ogg_vorbis.c:(.text+0x20a): undefined reference to `ogg_sync_wrote'
ogg_vorbis.c:(.text+0x237): undefined reference to `ogg_stream_pagein'
ogg_vorbis.c:(.text+0x257): undefined reference to `ogg_stream_packetout'
ogg_vorbis.c:(.text+0x2b0): undefined reference to `vorbis_synthesis_headerin'
ogg_vorbis.c:(.text+0x35b): undefined reference to `vorbis_comment_query'
ogg_vorbis.c:(.text+0x461): undefined reference to `vorbis_synthesis_init'
ogg_vorbis.c:(.text+0x47f): undefined reference to `vorbis_block_init'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_write_header':
ogg_vorbis.c:(.text+0x4f5): undefined reference to `vorbis_info_init'
ogg_vorbis.c:(.text+0x53d): undefined reference to `vorbis_encode_init_vbr'
ogg_vorbis.c:(.text+0x577): undefined reference to `vorbis_comment_init'
ogg_vorbis.c:(.text+0x598): undefined reference to `vorbis_comment_add_tag'
ogg_vorbis.c:(.text+0x710): undefined reference to `vorbis_comment_add_tag'
ogg_vorbis.c:(.text+0x74b): undefined reference to `vorbis_analysis_init'
ogg_vorbis.c:(.text+0x76f): undefined reference to `vorbis_block_init'
ogg_vorbis.c:(.text+0x78b): undefined reference to `ogg_stream_init'
ogg_vorbis.c:(.text+0x7be): undefined reference to `vorbis_analysis_headerout'
ogg_vorbis.c:(.text+0x7db): undefined reference to `ogg_stream_packetin'
ogg_vorbis.c:(.text+0x7f5): undefined reference to `ogg_stream_packetin'
ogg_vorbis.c:(.text+0x80f): undefined reference to `ogg_stream_packetin'
ogg_vorbis.c:(.text+0x895): undefined reference to `ogg_stream_flush'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_close':
ogg_vorbis.c:(.text+0x94e): undefined reference to `vorbis_analysis_wrote'
ogg_vorbis.c:(.text+0x96a): undefined reference to `vorbis_analysis'
ogg_vorbis.c:(.text+0x97c): undefined reference to `vorbis_bitrate_addblock'
ogg_vorbis.c:(.text+0x99f): undefined reference to `ogg_stream_packetin'
ogg_vorbis.c:(.text+0x9c2): undefined reference to `ogg_stream_pageout'
ogg_vorbis.c:(.text+0xa30): undefined reference to `ogg_page_eos'
ogg_vorbis.c:(.text+0xa72): undefined reference to `vorbis_bitrate_flushpacket'
ogg_vorbis.c:(.text+0xa98): undefined reference to `vorbis_analysis_blockout'
ogg_vorbis.c:(.text+0xab3): undefined reference to `vorbis_block_clear'
ogg_vorbis.c:(.text+0xac3): undefined reference to `vorbis_dsp_clear'
ogg_vorbis.c:(.text+0xad3): undefined reference to `vorbis_comment_clear'
ogg_vorbis.c:(.text+0xae3): undefined reference to `vorbis_info_clear'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `ogg_vorbis_open':
ogg_vorbis.c:(.text+0xb7c): undefined reference to `vorbis_version_string'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_read_sample':
ogg_vorbis.c:(.text+0x13e5): undefined reference to `vorbis_synthesis_read'
ogg_vorbis.c:(.text+0x1422): undefined reference to `vorbis_synthesis_pcmout'
ogg_vorbis.c:(.text+0x144b): undefined reference to `ogg_sync_pageout'
ogg_vorbis.c:(.text+0x1499): undefined reference to `ogg_stream_pagein'
ogg_vorbis.c:(.text+0x14b7): undefined reference to `ogg_stream_packetout'
ogg_vorbis.c:(.text+0x14ea): undefined reference to `vorbis_synthesis'
ogg_vorbis.c:(.text+0x1510): undefined reference to `vorbis_synthesis_blockin'
ogg_vorbis.c:(.text+0x1561): undefined reference to `vorbis_synthesis_read'
ogg_vorbis.c:(.text+0x159e): undefined reference to `vorbis_synthesis_pcmout'
ogg_vorbis.c:(.text+0x15c3): undefined reference to `ogg_page_eos'
ogg_vorbis.c:(.text+0x160f): undefined reference to `ogg_sync_buffer'
ogg_vorbis.c:(.text+0x1648): undefined reference to `ogg_sync_wrote'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_write_samples':
ogg_vorbis.c:(.text+0x177f): undefined reference to `vorbis_analysis_wrote'
ogg_vorbis.c:(.text+0x179b): undefined reference to `vorbis_analysis'
ogg_vorbis.c:(.text+0x17ad): undefined reference to `vorbis_bitrate_addblock'
ogg_vorbis.c:(.text+0x17d0): undefined reference to `ogg_stream_packetin'
ogg_vorbis.c:(.text+0x17f3): undefined reference to `ogg_stream_pageout'
ogg_vorbis.c:(.text+0x1861): undefined reference to `ogg_page_eos'
ogg_vorbis.c:(.text+0x18a3): undefined reference to `vorbis_bitrate_flushpacket'
ogg_vorbis.c:(.text+0x18c9): undefined reference to `vorbis_analysis_blockout'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_write_s':
ogg_vorbis.c:(.text+0x1952): undefined reference to `vorbis_analysis_buffer'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_write_i':
ogg_vorbis.c:(.text+0x1a5d): undefined reference to `vorbis_analysis_buffer'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_write_f':
ogg_vorbis.c:(.text+0x1b6a): undefined reference to `vorbis_analysis_buffer'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_write_d':
ogg_vorbis.c:(.text+0x1c69): undefined reference to `vorbis_analysis_buffer'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_end':
ogg_vorbis.c:(.text+0x1f06): undefined reference to `vorbis_comment_clear'
ogg_vorbis.c:(.text+0x1f18): undefined reference to `vorbis_info_clear'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `free_stream_set':
ogg_vorbis.c:(.text+0x1f98): undefined reference to `ogg_stream_clear'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `find_stream_processor':
ogg_vorbis.c:(.text+0x203f): undefined reference to `ogg_page_serialno'
ogg_vorbis.c:(.text+0x20cd): undefined reference to `ogg_page_eos'
ogg_vorbis.c:(.text+0x21f1): undefined reference to `ogg_stream_init'
ogg_vorbis.c:(.text+0x2208): undefined reference to `ogg_stream_pagein'
ogg_vorbis.c:(.text+0x221f): undefined reference to `ogg_stream_packetout'
ogg_vorbis.c:(.text+0x2279): undefined reference to `vorbis_comment_init'
ogg_vorbis.c:(.text+0x228b): undefined reference to `vorbis_info_init'
ogg_vorbis.c:(.text+0x22a2): undefined reference to `ogg_stream_packetout'
ogg_vorbis.c:(.text+0x22b5): undefined reference to `ogg_stream_clear'
ogg_vorbis.c:(.text+0x22ca): undefined reference to `ogg_stream_init'
ogg_vorbis.c:(.text+0x22d6): undefined reference to `ogg_page_eos'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_length_get_next_page':
ogg_vorbis.c:(.text+0x2331): undefined reference to `ogg_sync_buffer'
ogg_vorbis.c:(.text+0x236c): undefined reference to `ogg_sync_wrote'
ogg_vorbis.c:(.text+0x2388): undefined reference to `ogg_sync_wrote'
ogg_vorbis.c:(.text+0x239b): undefined reference to `ogg_sync_pageout'
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o): In function `vorbis_length_aux':
ogg_vorbis.c:(.text+0x2402): undefined reference to `ogg_sync_init'
ogg_vorbis.c:(.text+0x24af): undefined reference to `ogg_stream_pagein'
ogg_vorbis.c:(.text+0x250a): undefined reference to `vorbis_synthesis_headerin'
ogg_vorbis.c:(.text+0x2547): undefined reference to `ogg_stream_packetout'
ogg_vorbis.c:(.text+0x2560): undefined reference to `ogg_page_granulepos'
ogg_vorbis.c:(.text+0x25e8): undefined reference to `ogg_sync_clear'
collect2: error: ld returned 1 exit status
CMakeFiles/Train.dir/build.make:724: recipe for target 'Train' failed
make[2]: *** [Train] Error 1
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/Train.dir/all' failed
make[1]: *** [CMakeFiles/Train.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by evpobr** [comment]
Your libsndfile version is tooo old. Try latest master.

**Comment by erikd** [comment]
Ubuntu ships libsndfile. Why do you not just installed the official package from Ubuntu?
```
sudo apt install libsndfile libsndfile-dev
```

**Comment by Stolaine** [comment]
> 
> 
> Ubuntu ships libsndfile. Why do you not just installed the official package from Ubuntu?
> 
> ```
> sudo apt install libsndfile libsndfile-dev
> ```

so we don't have to build libsndfile with cmake?

**Comment by erikd** [comment]
If you can install a package from your Linux distribution, why would you build it yourself?

The only reason to build it yourself is if you want to build the *very latest version* or if you want to contribute to libsndfile yourself.

**Comment by Stolaine** [comment]
I installed the package but still getting the same error. Is it because I have two libsndfile library in my system?

**Comment by erikd** [comment]
You should probably remove the one you installed in `/usr/local`.

**Comment by evpobr** [comment]
> > Ubuntu ships libsndfile. Why do you not just installed the official package from Ubuntu?
> > ```
> > sudo apt install libsndfile libsndfile-dev
> > ```
> 
> so we don't have to build libsndfile with cmake?

CMake is working more or less stable in master branch.

**Comment by Stolaine** [comment]
> 
> 
> You should probably remove the one you installed in `/usr/local`.

i removed the libsndfile.a file from /usr/local/lib/ 
and i have libsndfile1 and libsndfile1-dev package installed 
now if i run the make command for wav2letter - it can't find libsndfile.a
How to make libsndfile1 available ?

**Comment by evpobr** [comment]
> now if i run the make command for wav2letter - it can't find libsndfile.a

Maybe you've deleted the right one? Reinstall `libsndifle-dev` package.

It is very likely your installation is buggy now, if you use `make install` here and there. But if yu really need to go further `FindSNDFILE.cmake` script of wav2letter understands `SNDFILE_INC_DIR` and `SNDFILE_LIB_DIR` variables:

    cmake .. -DSNDFILE_INC_DIR=/usr/lib/x86_64-linux-gnu/ -DSNDFILE_LIB_DIR=/usr/include/

**Comment by Stolaine** [comment]
> 
> 
> > now if i run the make command for wav2letter - it can't find libsndfile.a
> 
> Maybe you've deleted the right one? Reinstall `libsndifle-dev` package.
> 
> It is very likely your installation is buggy now, if you use `make install` here and there. But if yu really need to go further `FindSNDFILE.cmake` script of wav2letter understands `SNDFILE_INC_DIR` and `SNDFILE_LIB_DIR` variables:
> 
> ```
> cmake .. -DSNDFILE_INC_DIR=/usr/lib/x86_64-linux-gnu/ -DSNDFILE_LIB_DIR=/usr/include/
> ```

This helps and the error is not coming anymore. Thanks
