### ISSUE TITLE
sf_read**** behaviour

### ISSUE THREAD

**Issue by vlazzarini** [erikd/libsndfile#454]
This is not a bug report but maybe a documentation issue. 

With the sf_read***() functions, I would have expected that if a buffer is not completely
filled, the samples at the end position would not be cleared. Say, if we request cnt samples/frames
to be read, and there is only N samples/frames available, then cnt-N samples/frames would be
garbage from a previous call to sf_read***(). However, it does not appear so: these samples/frames
are 0. 

I am happy with this feature, but I was looking at the API reference and could not find any mention of
this behaviour. Is it possible to clarify this in the documentation? Thx

**Comment by evpobr** [comment]
Yes, i see it. @erikd , do we need to document it?

**Comment by erikd** [comment]
I suspect that this was added to make debugging easier.

Since its is there, I would suggest that updating the documentation (with a reason, ie debugging) would be a good idea.
