### ISSUE TITLE
Timestamps in file formats

### ISSUE THREAD

**Issue by rodri** [erikd/libsndfile#471]
It seems that (tested in version 1.0.28) some file formats include timestamps (like 32 bit floating point wav) while others do not (like 16 bit signed integer wav).
Timestamps are problematic because if I generate 2 identical files and compare them, with: "diff file1.wav file2.wav", the output will be that they are different, and this is caused by the timestamps, verified with: "diff <(hd file1.wav) <(hd file2.wav)".
Since the file system already has file modification times, could it be possible to (optionally or not) remove timestamps (or at least set them to zero) in all formats that support it? I do not know whether some standards mandate them, but in that case setting them to zero should work.

**Comment by erikd** [comment]
Tools like `diff` and `cmp` are not really suited for use on audio files.

If you are interested in differences in the actual audio data of two files, there is a program `sndfile-cmp` in the `programs/'` directory which only compares the audio data of two sound files.

If you are interested in differences in the file meta data, you should compare the outputs of `sndfile-info` on the files.

For things more complicated that either of the above, you may need to write your own program.

As for the suggestion of doing complicated things with time stamps, I would first want to see why the above suggestions are insufficient.

**Comment by rodri** [comment]
The use case that moved me to open the issue is: I am developing a program, and in its tests it writes some sound files to a directory. Then I would want to do: `diff -r dir1/ dir2/`, and see whether the files it produces are identical to the ones it produced by a previous version (to avoid regressions).

That is my ideal view. But, it could be enough with the above suggestions, and let me write a script to compare all files one by one with `sndfile-cmp`. This might be the most practical and easiest solution.

Thank you.
