### ISSUE TITLE
cannot open rsrc

### ISSUE THREAD

**Issue by mgood7123** [erikd/libsndfile#474]
libsdnfile returns -1 for "/sdcard/ReSampler/SPD.mp3/..namedfork/rsrc" even tho it succesfully opens "/sdcard/ReSampler/SPD.mp3" with an fd of 56

```
// pfile->path.c = "/sdcard/ReSampler/SPD.mp3"
// oflag = 0
fd = open (pfile->path.c, oflag) ;
// fd = 56
```

```
// pfile->path.c = "/sdcard/ReSampler/SPD.mp3/..namedfork/rsrc"
// oflag = 0
fd = open (pfile->path.c, oflag) ;
// fd = -1
```

libsndfile\src\file_io.c:125 `	count = snprintf (psf->rsrc.path.c, sizeof (psf->rsrc.path.c), "%s/..namedfork/rsrc", psf->file.path.c) ;`

**Comment by erikd** [comment]
This bug report is not very useful to me unless there is enough information for me to reproduce it.

Your bug report should above all else, include reproduction steps.
