### ISSUE TITLE
Newly written file reports 0 frames

### ISSUE THREAD

**Issue by normvcr** [erikd/libsndfile#478]
x86_64, 16 GB RAM.  Installed libsndfile via system installer:
Name         : libsndfile
Version      : 1.0.28
Release      : 10.fc30
Architecture : x86_64
Size         : 627 k
Source       : libsndfile-1.0.28-10.fc30.src.rpm
Repository   : @System
From repo    : anaconda
Summary      : Library for reading and writing sound files
URL          : http://www.mega-nerd.com/libsndfile/

After writing to a file (using C++ interface), and calling writesync(), the frames() method shows 0 frames.  However, after closing and reopening the file on disk, the frame count is correct.  Here is the output of sndfile-info:
========================================
File : t.wav
Length : 3184
RIFF : 3176
WAVE
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 1
  Sample Rate   : 7000
  Block Align   : 2
  Bit Width     : 16
  Bytes/sec     : 14000
data : 3140
End

----------------------------------------
Sample Rate : 7000
Frames      : 1570
Channels    : 1
Format      : 0x00010002
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:00.224
Signal Max  : 15870 (-6.30 dB)

**Comment by erikd** [comment]
Your understanding of [sf_write_sunc](http://www.mega-nerd.com/libsndfile/api.html#write_sync) is incorrect. That function is designed to flush data in the O/S buffers to disk.

It seems that what you want is to flush `libsndfile`'s buffers to disk. What you want is either the [SFC_UPDATE_HEADER_NOW](http://www.mega-nerd.com/libsndfile/command.html#SFC_UPDATE_HEADER_NOW) or [SFC_SET_UPDATE_HEADER_AUTO](http://www.mega-nerd.com/libsndfile/command.html#SFC_SET_UPDATE_HEADER_AUTO) command used with `command` function/method of the C++ interface.

**Comment by normvcr** [comment]
Thanks.  I should have explored the command() routine.
When I call command() with, SFC_UPDATE_HEADER_NOW, the command() method returns 0, indicating the command was not successful.  However,

 strError() returns "No Error."

As earlier, a subsequent call to the frames() method still returns 0,rather than 1570.  Here is a short program that reproduces this:

```
#include "sndfile.hh"
#include <iostream>
#include <assert.h>

using namespace std;

int main( int argc, char* argv[] )
{
  const char outFilename[] = "T.wav";
  const int outFormat = SF_FORMAT_WAV  + SF_FORMAT_PCM_16;
  const int outChannels = 1;
  const double outSampleRate = 7000;
  
  SndfileHandle outsnd( outFilename,
			SFM_WRITE,
			outFormat,
			outChannels,
			outSampleRate );
  
  assert( outsnd );
  
  const size_t odone = 1570;
  signed short outbuf[ odone ];
				      
  const sf_count_t numFramesWritten = outsnd.writef( outbuf, odone );
  cout << "numFramesWritten= " << numFramesWritten << endl;
  assert( odone == numFramesWritten );
  
  outsnd.writeSync();

  // This returns 0, indicating failure
  const int cret = outsnd.command( SFC_UPDATE_HEADER_NOW, nullptr, 0 );
  cout << "command(SFC_UPDATE_HEADER_NOW)= " << cret << endl;

  // This indicates no error occurred.
  cout << "strError()= " << outsnd.strError() << endl;

  // Header has not been updated: returns 0
  cout << "outfile frames= " << outsnd.frames() << endl;
  
  return 0;
}// main

```

**Comment by njh** [comment]
Documentation says:
> Return value: 0

http://www.mega-nerd.com/libsndfile/command.html#SFC_UPDATE_HEADER_NOW

This is the same as lots of the other command responses (non-zero meaning error).

**Comment by normvcr** [comment]
OK, so the frames field of the header is not updated.  Not a big deal.  After closing and reopening the file, the frames field is correct.  Question is, do we want the frames field to be updated on the fly?

**Comment by erikd** [comment]
> Question is, do we want the frames field to be updated on the fly?

If you don't need it, don't use it. When the call `sf_close` the header fields will be updated correctly.

If you do need it you will know why.

**Comment by normvcr** [comment]
Sounds good to me.  Great library, does what I need.  Many thanks for the comments from both of you.
