### ISSUE TITLE
Endian values in SF_BROADCAST_INFO structure

### ISSUE THREAD

**Issue by njh** [erikd/libsndfile#481]
Hi,

I have been taking a look into implementing #479 

I was looking at the existing code and there doesn't seem to be any code that deals with converting the endianness of the multi-byte integers?

* `uint32_t	time_reference_low ;`
* `uint32_t	time_reference_high ; `
* `short		version ; `
* `uint32_t	coding_history_size ;`

[EBU Tech 3285](https://tech.ebu.ch/docs/tech/tech3285.pdf) doesn't mention endianness at all - but I presume that all fields are little-endian - the same as the rest of the WAVE file?

I am not sure I have ever used libsndfile and SF_BROADCAST_INFO on a big endian processor.

Is this a bug? Or is it the responsibility of the person reading/writing the SF_BROADCAST_INFO structure to do the conversion. (not sure this works for the `version` and `coding_history_size`  fields).

nick.

**Comment by erikd** [comment]
Yes, all multi-byte fields of WAV files are little endian.

I really do not think there is a bug. This code was all written and tested on a big endian system when I had such a system. You are probably looking at something like:
```
	bytesread = psf_binheader_readf (psf, "224422",
					&(wav_fmt->format), &(wav_fmt->min.channels),
					&(wav_fmt->min.samplerate), &(wav_fmt->min.bytespersec),
					&(wav_fmt->min.blockalign), &(wav_fmt->min.bitwidth)) ;
```
which does not explicitly set the endianness (using "E" in the format string for big endian "e" for little). The endianness setting is not needed, because the endianness settings are cached within the `SF_INFO` struct.

I am pretty sure that if you added a `E` (to set big endian) to the above (or any other format string) would cause the tests to fail.

**Comment by njh** [comment]
I am sure that the main WAV file code is correct correctly on Big Endian systems - it is just the Broadcast Wave Format / `bext` extension that I am not sure about.

Maybe I will do some real-world testing on a Raspberry Pi using a example BWF from a third-party source.

Note that the `psf_binheader_*` functions aren't used at all in `broadcast.c` - it just seems to `memcpy` the whole SF_BROADCAST_INFO structure out of memory.

**Comment by erikd** [comment]
Pretty sure all the the RPis are little endian.

> Note that the psf_binheader_* functions aren't used at all in broadcast.c - it just seems to memcpy the whole SF_BROADCAST_INFO structure out of memory:

Yeah, that assumes whoever receives that data can do the right encoding/decoding and that is unlikely.

**Comment by njh** [comment]
Oh! I hadn't realised that ARM is mixed endian / normally run little endian.
Big Endian is effectively dead then?

Wonder if this is worth looking into / fixing then.

**Comment by erikd** [comment]
Yeah, big endian is mostly dead. More recent PPC and Arm machines are now LE and Sparc is effectively dead as an arcitecture.

**Comment by njh** [comment]
#wontfix

**Comment by njh** [comment]
Sorry, I got this completely wrong. There is indeed code to do the endian conversion of the integers in SF_BROADCAST_INFO. I was just looking in completely the wrong place.

* Read: https://github.com/erikd/libsndfile/blob/master/src/wavlike.c#L755
* Write: https://github.com/erikd/libsndfile/blob/master/src/wavlike.c#L794
