### ISSUE TITLE
Read wav-gsm610 file, the buffer needs to be larger than frames, otherwise there will be exceptions

### ISSUE THREAD

**Issue by gongjianbo** [erikd/libsndfile#482]
Read wav-gsm610 file, the buffer needs to be larger than frames, otherwise there will be exceptions. In addition, when gsm610 reads most data at one time, it also crashes. Strangely, the PCM format can be read properly.

```
SndfileHandle snd("filepath/wav-gsm610.wav");
//if you use a larger buffer, you can read it normally, such as "short[snd.frames() * 2]".
short * buffer=new short[snd.frames()];  //audio data channels=1
int read_count=0;
while(read_count<snd.frames()){
       const int read_len=snd.read(buffer+read_count,1024 * 10); //gsm610 can not read too large
       read_count+=read_len;
}

```

**Comment by gongjianbo** [comment]
It may be delayed for a while before a crash occurs.

**Comment by erikd** [comment]
Do you also get an error is you run the `sndfile-info` program (in the git repo) on that file?

**Comment by gongjianbo** [comment]
========================================
File : wav-gsm610.wav
Length : 3895
RIFF : 3887
WAVE
fmt  : 20
  Format        : 0x31 => WAVE_FORMAT_GSM610
  Channels      : 1
  Sample Rate   : 11025
  Block Align   : 65
  Bit Width     : 0
  Bytes/sec     : 2239
  Extra Bytes   : 2
  Samples/Block : 320
fact : 4
  frames  : 18751
*** 'data' chunk should be an even number of bytes in length.
data : 3835
End
*** Warning : data chunk seems to be truncated.

----------------------------------------
Sample Rate : 11025
Frames      : 19200
Channels    : 1
Format      : 0x00010020
Sections    : 1
Seekable    : FALSE
Duration    : 00:00:01.741
Signal Max  : 0 (-inf dB)

**Comment by gongjianbo** [comment]
> Do you also get an error if you run the `sndfile-info` program (in the git repo) on that file? If you do not get an error, what is the output?

I posted the result of sndfile-info. Data from http://samples.mplayerhq.hu/A-codecs/libsndfile-samples/wav-gsm610.wav.

**Comment by gongjianbo** [comment]
What should I do when the length of the 'data' chunk is odd?

**Comment by erikd** [comment]
If `sndfile-info` reads the file correctly, then it is much more likely to be a bug in your program. I suggest using a tool like Valgrind on the the address sanitizer options for GCC/Clang to debug this.

**Comment by gongjianbo** [comment]
I'm using msvc2015. The code is just a simple ’read()‘ operation.

**Comment by gongjianbo** [comment]
Msvc2015-32bit debug exception message:  0x0C0000005: Access conflict occurred while writing address 0x09B17000...(Google Translate)

**Comment by erikd** [comment]
What is the output of `sndfile-info` on that file?

**Comment by gongjianbo** [comment]
I have given this information in my previous reply.

**Comment by erikd** [comment]
Your code is logically flawed.
```
	while (read_count < snd.frames ())
	{	const int read_len = snd.read(buffer+read_count,1024 * 10) ; 
```
The `buffer` array has space for `frames` items. However, if the first read returns less than `frames` items,  the second call will overflow `buffer`.

**Comment by gongjianbo** [comment]
Sure enough, I changed the second parameter to run normally.谢谢你的解答!
