### ISSUE TITLE
Error reading simple WAV file pcm_s16le in debian stretch

### ISSUE THREAD

**Issue by emilio-molina** [erikd/libsndfile#484]
The file is this one: https://storage.googleapis.com/bmat-rd-storage/test.wav

Encoded with ffmpeg 3.2.14-1~deb9u1 (from a mp3) into a wav @8000hz pcm_s16le mono .

OS: debian 9.9
libsndfile-dev: 1.0.27-3 (the one installed with apt-get by default)
g++ version: 6.3.0-18+deb9u1 (idem)

I don't find `sndfile-info` (does not seem to be installed along with libsndfile-dev), but I share a very simple c++ program to reproduce my error:

```
#include <iostream>
#include <vector>
#include <sndfile.hh>

using namespace std;

int main()
{
    SNDFILE *sf;
    SF_INFO info;
    info.format = 0; // pcm_s16le
    sf = sf_open("test.wav", SFM_READ, &info);
    cout << "info.frames: " << info.frames << endl;
    cout << "info.channels: " << info.channels << endl;
    std::vector<double> signal;
    int framesize=16;
    signal.reserve(framesize);
    int size_read = (int)sf_read_double(sf, &signal[0], framesize);
    cout << "size_read: " << size_read << endl;
}
```

I compile it as `g++ -Wall -Wextra -o test -lsndfile test.cpp`

The output is:
```
$ ./test
info.frames: 0
info.channels: 0
size_read: 0
```

In a different OS (debian 8.11, g++ 4.9.2, libsndfile 1.0.25) the output is:
```
$ ./test
info.frames: 1044062
info.channels: 1
size_read: 16
```

**Comment by erikd** [comment]
The `sndfile-info` program is part of the `sndfile-programs` packages.

From the symptoms you show, I suspect the first is on a 32 bit OS (possibly with an incorrectly compiled libsndfile) and the second is on a 64 bot OS.

I would also suggest you install `sndfile-programs` and use `sndfile-info`.

**Comment by erikd** [comment]
If `sndfile-info` works correctly on the 64 bit OS but not on the 32 bit OS, then that is a Debian bug, not a libsndfile bug.

**Comment by emilio-molina** [comment]
I am able to reproduce the error using docker (image `debian:9.9`), and just by installing:

```
apt-get update
apt-get install build-essential
apt-get install libsndfile-dev
apt-get install sndfile-programs
```

Inside this docker container, I run:

```
# uname -a
Linux 5cdf59b24858 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux

# sndfile-info test.wav
Error : Not able to open input file test.wav.
File : test.wav
Length : 2089042
RIFF : 2089034
WAVE
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 1
  Sample Rate   : 8000
  Block Align   : 2
  Bit Width     : 16
  Bytes/sec     : 16000
LIST : 866
  INFO
    IART : Strip Sounds
  *** ICMT : 546 (too big)
Have 0 marker at position 952 (0x3B8).

Error in WAV file. No 'data' chunk marker.
```

However, in a "healthy" OS I get:

$ sndfile-info test.wav

```
Version : libsndfile-1.0.25

========================================
File : test.wav
Length : 2089042
RIFF : 2089034
WAVE
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 1
  Sample Rate   : 8000
  Block Align   : 2
  Bit Width     : 16
  Bytes/sec     : 16000
LIST : 866
  INFO
    IART : Strip Sounds
    ICMT : Soft bouncy opening builds in energy to boisterous finale. From Orpheus in the Underworld, LC 26429, ISRC: GB-22P-13-039-03, Offenbach, Jacques, Contentes - Crianças, Romantismo (séc. XIX e XX), Slapstick, Crianças - Pequenas, Crianças alegres, Clássico-Arranjos Novos, Clássico-Instrumentos-solo, Desenhos Animados, Excêntrico-espirituoso-comédia, Absorto, Despreocupado, Otimista, Positivo, Feliz, Contente, feliz, Piano, Main version, Commercial 29/30 sec, formation: Small formation tempo: Medium tempo sound: Natural (organic) sound
    ICOP : (c) Imagem Production Music
    ICRD : 2013
    IGNR : Children/Classical Genres/Comedy/Film Styles/Historical
    INAM : CAN CAN
    IPRD : BHCL 39 - SIMPLIFIED: PLAYFUL PIANO
    *** IPRT : 4
    ISFT : Lavf57.56.101
    *** ITCH : 24
data : 2088124
End

----------------------------------------
Sample Rate : 8000
Frames      : 1044062
Channels    : 1
Format      : 0x00010002
Sections    : 1
Seekable    : TRUE
Duration    : 00:02:10.508
Signal Max  : 28956 (-1.07 dB)
```

Is it confirmed that it is a debian bug?

**Comment by erikd** [comment]
They are both on `x86_64`? Are they different versions of libsndfile?

**Comment by emilio-molina** [comment]
Yes, they are both on `x86_64`. In the failing case it is libsndfile `1.0.27-3`, in the working case it is  `1.0.25-9.1+deb8u4`

**Comment by emilio-molina** [comment]
Please, note that the file can be downloaded in case it is convenient:

https://storage.googleapis.com/bmat-rd-storage/test.wav

**Comment by erikd** [comment]
The version in Debian testing (1.0.28-6) works correctly.

Version 1.0.27 (from the git tag) doesn't, so I do not expect the Debian version to work either.

**Comment by emilio-molina** [comment]
So version 1.0.27 has a bug, but 1.0.28 already fixed the problem, isn't it?

**Comment by erikd** [comment]
Correct!

**Comment by emilio-molina** [comment]
I tried to remove the metadata (flag `-map_metadata -1` in ffmpeg) from the WAV file and it worked, so that seemed to be the problem... I will work without metadata to avoid this problem.

I have processed many similar files, and in most cases it didn't crash. Do you think the content might be corrupted anyway (the audio samples)? Just to know if I should repeat all the processing for all files.

Thanks a lot!

**Comment by emilio-molina** [comment]
For some file with long metadata, in version 1.0.27, could it happen that:

`int size_read = (int)sf_read_double(sf, &signal[0], framesize);`

indeed reads audio samples, but these audio samples are corrupted?

**Comment by erikd** [comment]
That file triggers a bug in that version. I don't remember the details of the bug and how it may affect some files.
