### ISSUE TITLE
Extended libsndfile?

### ISSUE THREAD

**Issue by fredvs** [erikd/libsndfile#485]
Hello.

In a other issue (https://github.com/erikd/libsndfile/issues/258) there is reference to library mpg123.
That library gives methods for basic DSP, like equalizer, volume-change.

Of course those methods can easily be done by the main application after decoding the audio-file.

But if those DSP are done by libsndfile himself directly after decoding, IMHO, it would produce a faster result than to make it by the main application.

What do you think?

Fre;D

**Comment by erikd** [comment]
`libsndfile` is for reading and writing sound files. Other capabilities belong elsewhere.
