### ISSUE TITLE
Windows CMake issue

### ISSUE THREAD

**Issue by otristan** [erikd/libsndfile#486]
There has been recent changes regarding CMake support that broke some stuff on Windows.

It used to be LibSndFileConfig.cmake and now it's SndFileConfig.cmake.

Make sense according to usual library naming convention.

Still the folder created in Program Files when installing the lib is still libsnfile which  break cmake auto finding of the cmake config file.

Renaming the dir to sndfile fixes the issues.

Don't know what is the best thing to do here.

It breaks as well the compatibility for the .dll name with previous version so this might be problematic as well.

Thanks !

**Comment by erikd** [comment]
@evpobr Maybe this is something you can answer?

**Comment by evpobr** [comment]
> Still the folder created in Program Files when installing the lib is still libsnfile which break cmake auto finding of the cmake config file.

Well, you're right, this breaks package config search. But only well you install to default location on Windows platform.

Unfortunately, changing project name to `libsndfile` will break other things. For example, i use a variable `CMAKE_INSTALL_DOCDIR` which is constructed as `DATAROOTDIR/doc/${PROJECT_NAME}`. So we will fix one thing breaking another thing.

My advise for you - use `CMAKE_INSTALL_PREFIX` and install libsndfile somewhere else e.g `C:\install`. Then you will have installation directory `C:\install` with subdirectories:

```
`C:\install\include`
`C:\install\lib`
```

and everything should work.

> It breaks as well the compatibility for the .dll name with previous version so this might be problematic as well.

If you need  `libsndfile-1.dll` output name use `ENABLE_COMPATIBLE_LIBSNDFILE_NAME` option set to `ON`.

**Comment by otristan** [comment]
ok good to know for ENABLE_COMPATIBLE_LIBSNDFILE_NAME

> But only well you install to default location on Windows platform.
Well, this seems to be a real issue because that what most people will do, right ?

If the dir name is only used for cmake so it should be sndfile. 
@erikd is the dir name important for other stuff  ? Besides what it used to be for many years

Or you should probably get back to the previous naming with libsndfile all the way.

**Comment by erikd** [comment]
I don't use the CMake build system. For all real POSIX systems I recommend the Autotools build system. As far as I am concerned, the CMake build system is mainly present because it works better on WIndows that Autotools.

**Comment by evpobr** [comment]
> Well, this seems to be a real issue because that's what most people will do, right ?

What people? You do, i don't.  I use Vcpkg package manager to deal with libraries on Windows platform.

> Or you should probably get back to the previous naming with libsndfile all the way.

Please no.

> If the dir name is only used for cmake so it should be sndfile.

Ok, i will take a look. This will take time. Until then, use `CMAKE_INSTALL_PREFIX\CMAKE_PREFIX_PATH\SndFile_DIR` options.

**Comment by otristan** [comment]
My remark was meant as most people that use libsndfile source will use cmake and don't define custom option.
if you use Vcpkg, then you don't use libsndfile own cmake, so sure, by avoiding the issue you don't get the issue :)

I don't mind the new naming. I just want something that works out of the box.

Thanks for taking my report into consideration.

**Comment by erikd** [comment]
@otristan Does that fix it for you?

**Comment by otristan** [comment]
if mandatory using a custom CMAKE_INSTALL_PREFIX is a fix then yes it fixes it for me.
Still I don't consider this a proper fix.

**Comment by evpobr** [comment]
@otristan , #488.

**Comment by otristan** [comment]
Silly me. Didn't see that they were a commit. Trying now.

**Comment by otristan** [comment]
All good.
Thanks !
