### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by SmiVan** [erikd/libsndfile#490]
As everyone knows, Python 2.7 is getting deprecated [in a couple months](https://pythonclock.org/).

As of right now, it's not possible to automatically build the library from source without Python 2.7.

The following files contain references to Python 2.7 and will need to be updated to support Python 3, according to my quick grep:
- autogen.sh
- make_lite.py
- programs/test-sndfile-metadata-set.py
- Scripts/cstyle.py
- src/binheader_writef_check.py
- src/create_symbols_file.py

**Comment by erikd** [comment]
All of those are already python3 compatible even if they do not specifically invoke `python3`.

**Comment by SmiVan** [comment]
Oh, that's great! 
Then I guess all that needs to be done is to reroute them to the python3 interpreter.

Is the plan to do that exactly when old python gets dropped then?

**Comment by erikd** [comment]
On Debian and Ubuntu systems (what I know best) `/usr/bin/python` can be configured to point to either python2 or python3.

**Comment by SmiVan** [comment]
This issue is effectively closed, as compilation should be fine in all correct modern environments.
