### ISSUE TITLE
sf_seek() is really slow

### ISSUE THREAD

**Issue by morrolinux** [erikd/libsndfile#491]
Hi
I'm using `sf_seek` to seek a 2 hours audio track in `ogg` format. 
I've noticed that the seek time actually increases somehow proportionally to the time I seek to. 
For instance, if I seek to the first few minutes it's instantaneous, but if I seek for, say, the 50th minute it can take up to 10 seconds to get there. 
Am I doing something wrong / can you reproduce this issue?

**Comment by morrolinux** [comment]
Sorry I forgot to specify I'm on Arch Linux with `libsndfile  1.0.28-2` from official repo (not AUR)

**Comment by erikd** [comment]
Yeah, known issue, seeking on Ogg files is slow. Fixing that is a lot of work that I have not got around to yet.

**Comment by LittleHuba** [comment]
As mentioned in https://github.com/xournalpp/xournalpp/issues/1458#issuecomment-538132306 this is actually already solved but waiting to be included in a release...
