### ISSUE TITLE
cmake builds static library by default

### ISSUE THREAD

**Issue by dgrisham** [erikd/libsndfile#494]
Hey! Been trying to build the [`extempore`](https://github.com/digego/extempore/issues/367) project, and think I may have found an issue while trying to build `libsndfile` in the process. The README mentioned that `cmake` should build dynamic libraries by default (i.e. `BUILD_SHARED_LIBS=ON` by default). However, when I build with:

```
$ mkdir CMakeBuild && cd CMakeBuild
$ cmake .. -DBUILD_PROGRAMS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DENABLE_CPACK=OFF -DENABLE_PACKAGE_CONFIG=OFF
$ make
```

I get the static `libsndfile.a`, and not `libsndfile.so`. However, when I add the `-DBUILD_SHARED_LIBS=ON` option to `cmake`, the `.so` file builds.

Not sure what the fix is, or whether this is a docs vs. implementation issue.

**Comment by dgrisham** [comment]
Ah, and here's my system info in case it's relevant (running Arch  Linux):

```
$ cmake --version
cmake version 3.15.4

$ uname --kernel-release
5.3.7-arch1-1-ARCH
```

**Comment by erikd** [comment]
@evpobr ?

**Comment by evpobr** [comment]
Documentation issue.
