### ISSUE TITLE
[Cmake] target was not found

### ISSUE THREAD

**Issue by XavierSchiller** [erikd/libsndfile#500]
The Following Errors Occurred while generating Cmake Build Files:
```
CMake Error at CMakeLists.txt:17 (add_executable):
  Target "Xai" links to target "Vorbis::VorbisEnc" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:17 (add_executable):
  Target "Xai" links to target "FLAC::FLAC" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:17 (add_executable):
  Target "Xai" links to target "Opus::Opus" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

Project Root CMake:

```
cmake_minimum_required(VERSION 3.5)

project(Xai LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Qt5 COMPONENTS Widgets REQUIRED)
find_package(SndFile REQUIRED)

add_executable(Xai
  main.cpp
)

target_link_libraries(Xai
  Qt5::Widgets 
  SndFile::sndfile
)
```

Platform: Ubuntu 18.04
Compiler: GCC

**Comment by evpobr** [comment]
@XavierSchiller , FLAC Vorbis and Opus development packages are installed?

**Comment by XavierSchiller** [comment]
@evpobr Yes. Following the instructions, I used the following to do so:
```
sudo apt install autoconf autogen automake build-essential libasound2-dev \
  libflac-dev libogg-dev libtool libvorbis-dev libopus-dev pkg-config python
```

**Comment by XavierSchiller** [comment]
Is there something wrong or...?

**Comment by evpobr** [comment]
It is bug. Current SndFile config module implementation is very stupid and requires all dependencies CMake config packages installed, but when they are almost never installed with `-dev` packages. It means you need to compile all required libraries using CMake and install it.

There is no official guide how to handle this situation. I have some ideas, but it will take time.

Probably the only way to do it right is Vcpkg package manager. It should works on Linux platform.

**Comment by XavierSchiller** [comment]
I'll compile all the packages for now, and keep an eye open on the `CMake` build script later on. I'm closing this issue for now.
