### ISSUE TITLE
FindFLAC.cmake issues

### ISSUE THREAD

**Issue by rlyon01** [erikd/libsndfile#505]
Currently building sndfile.dll from github repsitory using cmake 3.16.3 and VS2019 on windows 10. When attempting to link in opus, flac, vorbis, vorbisenc and ogg I have found a few issues.

**FindFLAC.cmake: line 61**
```
    set (FLAC_DEFINITIONS -DFLAC__NO_DLL)
```

Causes visual studio to use a compiler option -D"-DFLAC__NO_DLL". After changing line to 

```
    set (FLAC_DEFINITIONS FLAC__NO_DLL)
```

the correct compiler option is generated. Not sure what impact this will have on other targets.

**FindFLAC.cmake: Lines 72-73**
```
    Ogg::Ogg
    $<$<BOOL:${WIN32}>:wsock32>
```
Causes the following error

```
CMake Error at cmake/FindFLAC.cmake:67 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```
Commented out line 73.

Then cmake generates vs2019 files correctly and I can build sndfile.dll. Don't see why libflac_static requires winsock library?

Regards ...

**Comment by evpobr** [comment]
@rlyon01 

> Don't see why libflac_static requires winsock library?

Hm, i found nothing in FLAC repo...

But i think the problem was wrong library. Can you check [this branch](https://github.com/evpobr/libsndfile/tree/cmake-improvements)?

**Comment by evpobr** [comment]
Did some tests, we can remove `FLAC__NO_DLL` and `wsock32` completely.
