### ISSUE TITLE
Problems parsing Wave64

### ISSUE THREAD

**Issue by jkcalhoun** [erikd/libsndfile#508]
Two issues:

1) w64_read_header() accounts for the header size twice for each of levl_HASH16, list_HASH16, junk_HASH16, bext_HASH16, MARKER_HASH16, and SUMLIST_HASH16, once in the switch statement and again when reading past these chunks (by subtracting 24 from dword below):

		if (chunk_size > 0 && chunk_size < 0xffff0000)
		{	dword = chunk_size ;
			psf_binheader_readf (psf, "j", dword - 24) ;
			} ;

This results in erroneously landing 24 bytes short of the next chunk marker. I've fixed this locally by deleting the line 

					chunk_size -= 24 ;

from each of the affected cases in the switch statement.

2) Instead of simply skipping past unknown chunks, w64_read_header() enters its "done parsing" state whenever an unknown chunk marker is encountered. Because Wave64 is designed to be user-extensible (via use of a GUID you can invent your own chunk types without fear of collision with someone else's), this is unfriendly, especially when an unknown chunk marker occurs before the 'data' chunk. Better just to skip over unknown chunk types and keep going.

I fixed this locally by deleting the line:

					done = SF_TRUE ;

from the default case in the switch statement.

**Comment by erikd** [comment]
Do the tests still pass?

**Comment by jkcalhoun** [comment]
> Do the tests still pass?

They do.

**Comment by jkcalhoun** [comment]
See pull request #509

**Comment by jkcalhoun** [comment]
[Silence-list-then-data.w64.zip](https://github.com/erikd/libsndfile/files/4156921/Silence-list-then-data.w64.zip)

**Comment by evpobr** [comment]
I think its was fixed, but issue not closed due wrong commit message. Closing now.
