### ISSUE TITLE
Unversioned lib for Android

### ISSUE THREAD

**Issue by showlabor** [erikd/libsndfile#51]
Hi Erik,

on Android you can't easily handle versioned libraries. It would be great to either have a general configure option to build an unversioned libsndfile or to check for an Android target in configure and then set

libsndfile_la_LDFLAGS = -no-undefined -avoid-version

instead of the usual

libsndfile_la_LDFLAGS = -no-undefined -version-info @SHARED_VERSION_INFO@ @SHLIB_VERSION_ARG@

Kind regards,
Felix

**Comment by erikd** [comment]
Closing this since the fix should be on the Android side.
