### ISSUE TITLE
connecting to simulator in gdb

### ISSUE THREAD

**Issue by jenewari** [erikd/libsndfile#510]
hello,

can anybody help? I use to load my program under target sim in gdb but recently when i try to connect to the simulator I have the error bellow
Undefined target command: "sim".  Try "help target".
This problem started I think after trying to install some packages.

need help how to roll back in ubuntu or making "target sim" connect again.

**Comment by erikd** [comment]
This is a gdb issue not a libsndfile issue. I don't have any clue how to solve this.
