### ISSUE TITLE
Libsndfile and Mac OS Catalina?

### ISSUE THREAD

**Issue by fredvs** [erikd/libsndfile#517]
Hello.

Does it exist binary LibSndfile-64.dylib working for Mac OS Catalina?

All the LibSndfile-64.dylib that I found on the net are not compatible.

Thanks.

**Comment by fredvs** [comment]
Re-hello.

With last Mac OS Catalina and his new Security lock down, it is nearly impossible for a non-guru to install a library "nude" (without included the static libraries, like libFLAC, libogg, libvorbis, ... etc).

So the perfect solution would be to have LibSndfile-64.dylib with included the needed static libraries inside.

Thanks.

Fre;D

**Comment by erikd** [comment]
I really do not see this as a libsndfile issue, but a MacOS issue. 

Is something like Brew not a solution?

Regardless, the solution is not going to come from me as I do not use Mac. The is something for the Mac users to solve.

**Comment by fredvs** [comment]
Hello Erik.

Hum, ok, Apple decided to make life of developers even more complicated than before, imho, it is very sad.

PS: I dont have a Mac too and yes, it is something for a Mac-guru.
Anyway if, by chance, somebody has more infos how to compile libsnfile for Mac Catalina, I would be very happy to add those infos for our libsndfile users.

Thanks.

Fre;D

**Comment by erikd** [comment]
First you were asking for a binary and now you are asking for build info?

Building libsndfile for Mac should be trivial, with both the autotool and the cmake build system.

**Comment by fredvs** [comment]
> First you were asking for a binary and now you are asking for build info?

Yes because for the first question you responded no, so I try with a second.

;-)

> Building libsndfile for Mac should be trivial...

Ho, not sure, but ok, I will wait that a Mac-guru appears.

Thanks and take good care of yourself.

Fre;D
