### ISSUE TITLE
Why sf_count_t is not unsigned?

### ISSUE THREAD

**Issue by MartinDelille** [erikd/libsndfile#518]
I don't understand why `sf_count_t` is a signed int.

**Comment by erikd** [comment]
First thing to remember is that this API was designed in the late 1990s, and as a C API, I was following the conventions of other existing C APIs like the standard C library and the POSIX one.

Specifically, `sf_read_*` was , modeled after the POSIX `read` function from the standard C library:
```
ssize_t read(int fildes, void *buf, size_t nbyte);
```
and from the man page:
```
RETURN VALUE
   Upon successful completion, these functions shall return a non-negative integer
   indicating the  number  of bytes actually read. Otherwise, the functions shall
   return −1 and set errno to indicate the error.
````

**Comment by MartinDelille** [comment]
Ok thanks!

And what if the C++ wrapper would use unsigned type and throw exceptions?

**Comment by erikd** [comment]
I don't use the C++ wrapper. Even when coding in C++, I use the C API.

In languages which have proper support for exceptions (like Haskell, which has exceptions as well as good alternatives) I avoid the use of exceptions (and use the alternatives). 

However, I do think that the C++ API (which is basically undocumented) should stick as close to the (at least somewhat documented) C API.

I also wonder if a more advanced C++ API could not exist outside this repo.

**Comment by MartinDelille** [comment]
In fact I'm personaly using [Qt](https://www.qt.io/) and could eventually publish my code. Would you _advertise_ a Qt wrapper if I do so?

**Comment by erikd** [comment]
I have not done that for a bunch of other wrappers of libsndfile, mainly because there are so many of them that I would never be able to keep up with them. However if you publish yours, I sure search for "Qt libsndfile" will turn it up.

**Comment by MartinDelille** [comment]
Ok thank for the feedback and your library!
