### ISSUE TITLE
opening psd files on macOS get stuck in loop and crash

### ISSUE THREAD

**Issue by adcxyz** [erikd/libsndfile#526]
Hello, 
while using libsndfile for finding soundfiles in folders with other files, 
I encountered a psd file that makes sndfile-info hang indefinitely (macOS 10.13.6)
I put the file at
https://cloud.medienhaus.udk-berlin.de/f/913278ac7f604563855f/?dl=1

This is a file from 2008 which still has a macOS resource fork; I suspect this bug is related to #340 .
Background: 
My main programming environment is SuperCollider, v 3.11.0, on macOS 10.13.6, 
which does all its soundfile handling with libsndfile 1.0.28, so I was doing the 
pathmatching there.
Searching usable soundfiles on archival disks is extremely useful for a current project,
so the risk of getting stuck and crashing on rare kinds of non-soundfiles is a showstopper.  
I have a workaround in SC for now, but hopefully this is easy to fix in libsndfile, so other projects using libsndfile also benefit from a real fix.

**Comment by adcxyz** [comment]
For reference, the issue reported for SuperCollider is #supercollider/supercollider/issues/4979.
To report the bug more precisely: running 
```sndfile-info ~/Desktop/DragonFyrAll.psd ``` in terminal 
hangs for a long time, then reports segmentation fault 11.

**Comment by erikd** [comment]
Can't reproduce this on Linux:
```
> ./programs/sndfile-info DragonFyrAll.psd 
Error : Not able to open input file DragonFyrAll.psd.
File : DragonFyrAll.psd
Length : 22362463

Format not recognised.
```
I suspect there is a resource fork missing.

**Comment by adcxyz** [comment]
Hi @erikd, 
Thanks for looking into this! 

The response you get is the correct one that should also come on macOS, 
it is an old photoshop file that sndfile-info should know to ignore. 
(my use case is about scavenging large file archives for soundfiles)

> Error : Not able to open input file DragonFyrAll.psd.
> File : DragonFyrAll.psd
> Length : 22362463

I don't know much about it, 
but maybe the resourcefork part is not copied when the file is unzipped on linux? 
could you get access to a macOS machine to test?

**Comment by erikd** [comment]
The problem is that there is a resource fork (a Mac specific thing) for that file and libsndfile tried to parse all resource forks in case the file is a Sound Designer II file. If you can get me the resource fork, I can probably fix this.

**Comment by adcxyz** [comment]
OK, I copied the resourceFork as a separate file, and you can get it from here: 
https://cloud.medienhaus.udk-berlin.de/f/9443b51ab7f0409e8cb7/
