### ISSUE TITLE
install problem 

### ISSUE THREAD

**Issue by adammaj1** [erikd/libsndfile#527]
Hi,

I have  
OS: Ubuntu 20.04 LTS x86_64 
 Kernel: 5.4.0-37-generic 
bash 5.0.16
gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2) 

I try to install library. after  make I have some errors : 

`
make[1]: Entering directory '/home/a/libsndfile'
make[2]: Entering directory '/home/a/libsndfile'
  CC       src/libsndfile_la-wavlike.lo
In file included from /usr/include/string.h:495,
                 from src/wavlike.c:23:
In function ‘strncpy’,
    inlined from ‘wavlike_subchunk_parse’ at src/wavlike.c:1033:9:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ output may be truncated copying 256 bytes from a string of length 2047 [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:2858: src/libsndfile_la-wavlike.lo] Error 1
make[2]: Leaving directory '/home/a/libsndfile'
make[1]: *** [Makefile:3102: all-recursive] Error 1
make[1]: Leaving directory '/home/a/libsndfile'
make: *** [Makefile:1448: all] Error 2
`

Any tips?

**Comment by erikd** [comment]
> all warnings being treated as errors

If you drop `-Werror` that will be a warning.
