### ISSUE TITLE
cmake: Multiple dependencies are autodetected only

### ISSUE THREAD

**Issue by diizzyy** [erikd/libsndfile#535]
Hi,
I'm not sure how granual this needs to be but multiple "optional" dependencies gets pulled in if they're detected which isn't ideal and causes issues when packaging.

A few examples:
alsa, sndio, speex(doesn't seem to get used at all?), sqlite, external (ogg, vorbis, flac, opus)

cmake, master branch
OS: FreeBSD 13-CURRENT

**Comment by evpobr** [comment]
Hi.

To build standard libsndfile package you need Ogg, Vorbis, FLAC and Opus to enable all supported formats. You need also ALSA (or Sndio for BSD-familily OS) to build one of the programs (sndfile-play).

All other things are experimental or rarely used.

**Comment by diizzyy** [comment]
Hi,
Yes, however these should be set (on/off or true/false) rather than pulling in stuff it finds?

**Comment by evpobr** [comment]
I cannot understand you. Some example?

**Comment by diizzyy** [comment]
Just because alsa, sndio etc is installed/found doesn't necessarily mean that you want libsndfile to pull it in.

**Comment by evpobr** [comment]
libsndfile doesn't use all of them. Look at `sndfile-play` `main` function, there are many mutually exclusive ifdefs to select available API.

I agree with you, this code is overcomplicated. Probably it is much better to use specialized library, maybe PortAudio. But due the lack of developers it is very low priority task.
