### ISSUE TITLE
Incorrect documentation in the header file on sf_command

### ISSUE THREAD

**Issue by SmiVan** [erikd/libsndfile#540]
https://github.com/erikd/libsndfile/blob/af49a5021cb0130f7034c3461c0998940ff99180/src/sndfile.h.in#L630-L632

This clearly is not [the correct documentation](http://www.mega-nerd.com/libsndfile/command.html), and is probably copied over from the next function by accident.

https://github.com/erikd/libsndfile/blob/af49a5021cb0130f7034c3461c0998940ff99180/src/sndfile.h.in#L635-L637

**Comment by evpobr** [comment]
Thanks @SmiVan !
