### ISSUE TITLE
opus test failures on BE platforms

### ISSUE THREAD

**Issue by SoapGentoo** [erikd/libsndfile#581]
Hi @erikd 
we're seeing test failures on big-endian platforms in Gentoo:
```
    float_scaled_test              : opus.opus ............... 

Line 237: sf_open (SFM_READ) failed : File contains data in an unimplemented format.

File : opus.opus
Length : 2483
Ogg stream data : Opus
Stream serialno : 818667452
Opus library version: libopus 1.3.1
Opus : Unknown / unsupported embedding scheme version: 16777216.

FAIL: tests/pedantic-header-test.sh
```
with the 1.0.29 release

**Comment by evpobr** [comment]
@arthurt ?

**Comment by arthurt** [comment]
Looking

**Comment by arthurt** [comment]
https://bugs.gentoo.org/719020

**Comment by SoapGentoo** [comment]
correct, I'm reporting that bug

**Comment by arthurt** [comment]
Yup, just linking it here for reference :-)

Took me a while to get a BE sandbox to play in, but yes, it is an endian issue, but more generally an integer pointer aliasing issue when parsing OggOpus header packets. Testing, but I should have a PR today to fix it.

**Comment by SoapGentoo** [comment]
@arthurt thanks, tested it on our SPARC machine, tests pass now :+1:
