### ISSUE TITLE
Add support for Xiph's Opus codec

### ISSUE THREAD

**Issue by erikd** [erikd/libsndfile#69]
I started this some time ago, but got busy on other things. If anyone has some spare cycles and would like to work on this, I can publish my work-in-progress branch for them to continue the effort.

I do hope to get back to this, but I have no idea when that will be.

**Comment by erikd** [comment]
Actually the work in progress branch is of little use. What I need is a stripped down and simplified version of opusenc and opusdec. I have in-progress versions of these but they need a lot more work.

**Comment by gudvinr** [comment]
@erikd how is it going?
There is [libopusenc](https://github.com/xiph/libopusenc) that can be used as source implementation.

**Comment by ousia** [comment]
@erikd, I wonder whether this issue may be closed, since it seems that the discussion is taking place at  #364.

**Comment by erikd** [comment]
Yes, closing.
