### ISSUE TITLE
Cannot open WAV files created by recent ffmpeg in SFM_RDWR mode due to string data in the header

### ISSUE THREAD

**Issue by AlisterH** [erikd/libsndfile#80]
Ffmpeg is pretty ubiquitous, and it creates WAV files with string data in the header.  Libsndfile will not open these in RDWR mode, which is rather perplexing for end users.  
I see an old discussion where it was suggested to allow opening these files in RDWR mode to edit just the audio data: http://music.columbia.edu/pipermail/linux-audio-dev/2004-August/009674.html

**Comment by erikd** [comment]
Closing this.
