### ISSUE TITLE
Linking error when building on mac osx

### ISSUE THREAD

**Issue by benderillo** [erikd/libsndfile#96]
System: OSX 10.9.5 Macericks
libsndfile version: libsndfile-1.0.25
Problem:
I needed to build libsndfile with support for ogg, flac, vorbis. So I downloaded, built and installed all necessary libraries.
Then ran "./configure" for the libsndfile and made sure that it found all the external libraries:
  Configuration summary :
    libsndfile version : .................. 1.0.25
    Host CPU : ............................ i386
    Host Vendor : ......................... apple
    Host OS : ............................. darwin13.4.0
    Experimental code : ................... no
    Using ALSA in example programs : ...... no
    External FLAC/Ogg/Vorbis : ............ yes
  Tools :
    Compiler is GCC : ..................... yes
    GCC version : ......................... 4.2.1
When I ran "make" I got the following linking error:
:info:build Undefined symbols for architecture x86_64:
:info:build   "_ogg_page_eos", referenced from:
:info:build       _ogg_vorbis_open in ogg_vorbis.o
:info:build       _vorbis_close in ogg_vorbis.o
:info:build       _vorbis_read_sample in ogg_vorbis.o
:info:build       _vorbis_write_samples in ogg_vorbis.o

After some googling around I found the following page and patch for the configure script that solves it: https://trac.macports.org/ticket/42846 
It was missing library dependency error. And the patch solved linking problem.
Compilation continued and I received another error:
sndfile-play.c:61:11: fatal error: 'Carbon.h' file not found
        #include <Carbon.h>
Googling led me to the following page that contains patch to sndfile-play.c that solves the compile error: https://trac.macports.org/ticket/33409

I created this issue to let know that the version 1.0.25 has issues building on mac osx and there are fixes exist that work. So, maybe author of libsndfile would consider including these fixes into next release of the library.

**Comment by erikd** [comment]
A version of that patch was applied to the Git version some time ago.

See: https://github.com/erikd/libsndfile/blob/master/configure.ac
