### ISSUE TITLE
Is there Ogg support for sf_get_string()?

### ISSUE THREAD

**Issue by MattGuerrette** [erikd/libsndfile#97]
Not a huge issue, but I've been outputting some ogg files from Audacity and noticed some of the information that should be embedded in the ogg file (such as the genre, for example) is not actually retrieved using sf_get_string(). However, some of the information is there such as the Title, Album, and Artist.

**Comment by erikd** [comment]
There definitely is support for this in the version here on Github. Not when it was added, but I'd be a little surprised if it wasn't added when Ogg/Vorbis support was added.

**Comment by erikd** [comment]
I've just tested this and both Ogg/Vorbis and FLAC have sf_get/set_string() support and it will be in the next release.
